### ISSUE TITLE
Transferring Armor/Materials between characters causes incorrect item stacking

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#232] opened 2015-05-29 02:19 UTC
In this example, I'm going to move 7 green special ammo from left to middle. 
![image](https://cloud.githubusercontent.com/assets/3769123/7875122/c09c3528-056d-11e5-91b5-b38ebd5f281a.png)

After successfully moving the 7 green special ammo synth to the character in the middle, you can see that the right stack now shows 27, which of course is impossible.
![image](https://cloud.githubusercontent.com/assets/3769123/7875162/3f153bc0-056e-11e5-9232-1b7f83c06b66.png)

Pressing F5 or refreshing solves the problem.

**Comment by Mulchman** [comment] 2015-06-17 16:59
@dasilva333 is there any programmatic way to know the max stack limit for a particular consumable/material? Or would we have to have an internal method for tracking such a thing?

**Comment by Mulchman** [comment] 2015-06-17 17:01
I'll take a look at this and see if I can figure it out.

**Comment by dasilva333** [comment] 2015-06-17 17:01
I'm not sure actually, I think there might be a definition files somewhere that tells us the maxStackSize for a particular given itemHash however I haven't seen it and I'm not sure how I would begin to start implementing enforcing of the proper stack sizes. Assuming the API gives us that info it's just a matter of implementing extra logic at the Item.js transfer level to stack the items properly.

**Comment by Mulchman** [comment] 2015-06-17 17:15
Looks like the TGfD ItemDefs might need to be updated (?). Looking at the destiny.plumbing consumable feed (http://destiny.plumbing/items/en/Consumable.json), there's indeed a maxStackSize value.

> "211861343":
> {
>     "hash":211861343,
> 	"name":"Heavy Ammo Synthesis",
> 	"description":"Single-use Ghost manufacturing package. Instantly replenish heavy weapon ammunition.",
> 	> "icon":"http://bungie.net/common/destiny_content/icons/b67087079a950013dfbdf6e0ebaeb245.jpg",
> 	"tier":"Common",
> 	"type":"Consumable",
> 	"subType":"Consumable",
> 	"bucket":"BUCKET_CONSUMABLES",
> 	"maxStackSize":100
> }

**Comment by Mulchman** [comment] 2015-06-17 17:17
What generates the data that's put into itemDefs.js?

**Comment by dasilva333** [comment] 2015-06-17 17:19
Delete this line from your update_definitions.js to create new itemDefs file with that property included:
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/build/update_definitions.js#L25

Expect that property to be there in future versions.

**Comment by Mulchman** [comment] 2015-06-17 17:31
Yeah, I changed (locally)

> delete obj.maxStackSize;

to

> obj.maxStackSize = encodeURIComponent(obj.maxStackSize);

**Comment by dasilva333** [comment] 2015-06-17 17:33
no its fine just get rid of the delete statement, there's no need to encode that field because its just a number not text or anything. I only need to run it through an encoding if there's characters displayed. thanks

**Comment by Mulchman** [comment] 2015-06-17 18:43
Gotcha. I'm also seeing why another bug exists when you split a stack through a transfer and then try to use either split to do further transfers: there's no cloning or new item creation happening when splitting.

**Comment by dasilva333** [comment] 2015-06-17 19:14
@Mulchman exactly I've known that for a while but again I'm out of ideas as to how to actually fix it. Good luck bud

**Comment by Mulchman** [comment] 2015-06-17 21:29
Is there a trick to getting the UI updated when adding to one of the characters' items() array? Can I poke the ko.observable stuff somehow? Even when changing the primaryStat value, I have to remove and re-add the item which is not good as the internal ordering changes.

**Comment by Mulchman** [comment] 2015-06-17 22:42
Mind checking this out and helping to figure out why the y.items.push() doesn't work? http://pastebin.com/2AtP7nwf

For testing I take all heavy out of vault then transfer a partial stack from a player to the vault. It's supposed to leave the original stack in place, decrement the original stack primaryStat value, create a new stack and move it to the vault. The result is nothing visually. No new stack is seen in the vault and the original stack doesn't get its value decremented.

**Comment by Mulchman** [comment] 2015-06-19 19:02
Anyone interested in testing? Changes are in my fork. You have to run update_definitions.js first though so maxStackSize gets put in itemDefs.cs correctly.

Transferring/splitting is all in there now. No clue if it's doing the correct things behind the scenes with respect to what the companion app does, but everything's tracked correctly for me so far. This is why I'm asking for testing before making a pull request.

**Comment by Mulchman** [comment] 2015-06-24 20:40
It's ready to test again. No update_definitions.js needed. Just grab my fork and try to break transferring consumables/materials.

**Comment by M3Rocket** [comment] 2015-06-24 23:39
Going to download and test right now. Sorry--been in meetings all day.

**Comment by M3Rocket** [comment] 2015-06-24 23:52
Seems to work well--stacking looks all cleaned up. I think it's ready for release. Nice job @Mulchman!

**Comment by Mulchman** [comment] 2015-06-25 02:16
Cool. Appreciate the testing!

**Comment by M3Rocket** [comment] 2015-06-26 01:30
@Mulchman Just D/L'ed your merged version from the original branch, and it seems that there is a bug. Transferring stacks now does not bring up the Transfer Dialog Box but immediately moves the entire stack.

**Comment by Mulchman** [comment] 2015-06-26 02:28
Thanks for the feedback! I'll check it out as soon as I can.

**Comment by Mulchman** [comment] 2015-06-26 16:31
@M3Rocket : just want to confirm you don't have **Auto Transfer Stacks** enabled?

I'm testing @dasilva333 's repo and things seem okay, but I'm not being too thorough. Can you provide a bit more information for reproducing?

**Comment by M3Rocket** [comment] 2015-06-26 19:00
@Mulchman Doh! I don't know why that was checked? I never use Auto Transfer Stacks. Sorry for the alarm. 

Back to regular programming...

**Comment by Mulchman** [comment] 2015-06-26 19:30
Ha. Closing... coming soon whenever a new version is released.

**Closed by Mulchman** 2015-06-26 19:30 UTC
Labels: enhancement
