### ISSUE TITLE
Moving multiple stacked items results in wrong number displayed

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#220] opened 2015-05-22 17:46 UTC
I think it's more a display problem than the actual calculation, but when you move items from multiple stacks to another, it results in the number shown incorrectly when the stack is reduced below the max stack size. Refreshing restores the correct number. 

Example, moving 63 Spinmetal from two stacks of 233 on left to single 26 right:
![image](https://cloud.githubusercontent.com/assets/3769123/7776283/9f9ea6c0-006e-11e5-83a2-1452bdda74f8.png)

Transfer box dialog:
![image](https://cloud.githubusercontent.com/assets/3769123/7776301/af902b4e-006e-11e5-8d92-daae4054407c.png)

Results:
![image](https://cloud.githubusercontent.com/assets/3769123/7776311/d086080a-006e-11e5-92fd-a2f5f5f5c5c2.png)

When transferring an amount into a stack that isn't maxed (transfer 50 to a stack of 160), the opposite occurs where instead showing two stacks (one at 200, the other at 10), it shows one stack of 210. Refresh solves the problematic display.

**Comment by Mulchman** [comment] 2015-06-19 19:03
Anyone interested in testing? Changes are in my fork. You have to run update_definitions.js first though so maxStackSize gets put in itemDefs.cs correctly.

Transferring/splitting is all in there now. No clue if it's doing the correct things behind the scenes with respect to what the companion app does, but everything's tracked correctly for me so far. This is why I'm asking for testing before making a pull request.

**Comment by M3Rocket** [comment] 2015-06-19 20:04
I'll look at it @Mulchman

**Comment by Mulchman** [comment] 2015-06-19 20:13
Thanks @M3Rocket 

Found a bug due to not checking for -1 return value of _.indexOf(). Fix will be in soon.

**Comment by M3Rocket** [comment] 2015-06-19 22:07
Been trying the beta. I think you have to force a refresh AFTER the items are transferred. Otherwise, the destination always shows two stacks even when there's supposed to be one. And the problem compounds when you click on one of the stacks in the destination and then transfer it to another destination.

**Comment by Mulchman** [comment] 2015-06-19 22:12
Can you give me a test case I can reproduce locally?

**Comment by Mulchman** [comment] 2015-06-19 22:13
Okay, just saw what I think you're describing by splitting a stack from a character (not the vault) to another character (not the vault).

**Comment by M3Rocket** [comment] 2015-06-19 22:17
Going to transfer 90 Relic Iron from left to right:
![2015-06-19_150921](https://cloud.githubusercontent.com/assets/3769123/8264008/ddf0338e-1695-11e5-8c8b-ee6dfc30a5f7.png)

Result is two stacks in destination. And the count is wrong on source:
![2015-06-19_150922](https://cloud.githubusercontent.com/assets/3769123/8264019/fe223e9a-1695-11e5-92aa-8357e4731607.png)

I then clocked on the stack of 90 on the right and transferred 50 to the left:
![2015-06-19_150923](https://cloud.githubusercontent.com/assets/3769123/8264026/1aa11d02-1696-11e5-862b-ecedf8229f0d.png)

Finally, I hit refresh to clear everything up:
![2015-06-19_150924](https://cloud.githubusercontent.com/assets/3769123/8264031/29cf09b0-1696-11e5-8817-73e4d54e6477.png)

**Comment by Mulchman** [comment] 2015-06-19 22:47
I believe I've fixed it. Please try again!

**Comment by Mulchman** [comment] 2015-06-19 23:20
Just pushed a bug fix for the cleanup (*shift left*) code.

**Comment by Mulchman** [comment] 2015-06-19 23:24
Ugh. It's gotten more broken. Don't waste your time testing.

**Comment by M3Rocket** [comment] 2015-06-19 23:27
OK. Let me know when it's more stable. I'll be checking every couple of hours.

**Comment by Mulchman** [comment] 2015-06-19 23:51
Pushed another fix when transferred are chained together (like player -> vault -> player) and new stacks got created visually due to maxStackSize getting hit with the first transfer.

**Comment by Mulchman** [comment] 2015-06-19 23:58
I won't be able to fix everything until next week most likely so I wouldn't bother testing. Most of the problems now are related to crossing stack boundaries. Transfer function might need to be taken off of the Item 'class' and made a 'static'/'global' somewhere else so that keeping the original reference doesn't matter.

**Comment by M3Rocket** [comment] 2015-06-20 00:27
Roger that. Will check back next week.

**Comment by Mulchman** [comment] 2015-06-22 21:33
@M3Rocket thanks again for the quick turnaround testing on Friday.

I've gone over things in my head during the weekend and just need some time to program. I'll update when I have something stable.

**Comment by Mulchman** [comment] 2015-06-23 04:50
I think it's real close. If anyone's available to test, please try.

**Comment by M3Rocket** [comment] 2015-06-23 05:27
Just DL'ed and testing. Looks like the numbers are correct now in terms of transferring. But stacking is still off. But the calcs are correct.
![2015-06-22_222549](https://cloud.githubusercontent.com/assets/3769123/8299481/df12fce8-192d-11e5-9b7a-23f2bbc21c33.png)

**Comment by Mulchman** [comment] 2015-06-23 05:29
Repro case please- how did you arrive at that

**Comment by M3Rocket** [comment] 2015-06-23 05:30
Just edited with case: Started with 90 on left, 130 right. Transferred 80 to right then 50 back to left.

**Comment by Mulchman** [comment] 2015-06-23 05:33
Can you jump in the slack chat if you're available? I just did the same and things look ok (?). I had some extras chilling in the vault, to make numbers match, but other than that it looked the same.

**Comment by Mulchman** [comment] 2015-06-23 06:35
Discovered something interesting screen sharing w/ @M3Rocket : Bungie API allows you to transfer more than a stacks worth at a time.

**Comment by Mulchman** [comment] 2015-06-23 22:22
Besides transferring an amount greater than the stack's maxStackSize, has anyone found any bugs?

**Comment by Mulchman** [comment] 2015-06-24 20:41
It's ready to test again. No update_definitions.js needed. Just grab my fork and try to break transferring consumables/materials.

**Comment by Mulchman** [comment] 2015-06-26 19:30
Closing... coming soon whenever a new version is released.

**Closed by Mulchman** 2015-06-26 19:30 UTC
Labels: bug
