### ISSUE TITLE
Doesn't work with iOS 9 beta

### ISSUE THREAD

**Issue by jpdyson** [dasilva333/TowerGhostForDestiny#243] opened 2015-06-09 21:22 UTC
Bugs are certainly expected in this scenario, and it's not even clear where the error lies, but the application doesn't work in iOS 9 dev preview 1. 

The UI is scaled for 640x1136, and nothing seems tapable.

**Comment by dasilva333** [comment] 2015-06-09 22:51
Unfortunately i won't be able to test it because I'm jailbroken so don't expect a fix any time soon, thanks for the report I'll keep this open

**Comment by jpdyson** [comment] 2015-06-10 00:11
I'll try and update you as the dev preview builds progress. I suspect the issue is with Hydration. 

[Please pardon brevity or typos; sent on the go]

**Comment by r3b3lspy** [comment] 2015-06-11 15:07
The application actually works on iPad iOS 9 and it will open correctly and load all inventory, unfortunately your pop up with the new features legend it is impossible to close, the X button does. Of do anything, the action is missing

**Comment by dasilva333** [comment] 2015-06-11 15:32
@r3b3lspy  Are you saying you can't close the Tower Ghost for Destiny Updates popup? The x button on the corner of the pop up is not necessary to close it simply tap the pop up anywhere and it should close. Please clarify clearly so I can understand the problem. thanks

**Comment by r3b3lspy** [comment] 2015-06-11 15:42
Yes that is correct, everything loads beautifully and then the popup of doom will show and it is impossible to lose, no matter where you tap.

**Comment by enyo** [comment] 2015-07-09 09:46
I can confirm this behavior. It's the same with iOS preview 1, 2 and 3.

**Comment by danielcampo** [comment] 2015-07-20 20:22
I can confirm that the app is unusable on the latest iOS 9 dev build 13A4293g (Posted Date July 8, 2015).

Unable to get passed the login screen— the buttons do not launch an action, no matter where you tap on the screen. Therefore, unable to proceed passed this view.

**Comment by danielcampo** [comment] 2015-07-20 20:23
I should add that I'm on a GSM iPhone 5 (Model A1428).

**Comment by dasilva333** [comment] 2015-07-20 20:45
Perhaps the issue will fix itself when I remove Hydra, stay tuned for more updates

**Comment by Oddworld7** [comment] 2015-07-21 21:02
Please men! I'm on ipad air 2, ios 9 beta i can't tap anything. I can't log in :( please try to fix it pleasee .

**Comment by payote** [comment] 2015-07-22 16:14
Can't expect everything to work when you run a beta build of iOS...

For me, I'm on an iPad Air 2, iOS 9 beta 4 - it's impossible to tap the Xbox Live or Playstation Network buttons to login to a Bungie.net account - the app updated to the latest build, but the login window that appears cannot be used or closed. I also experienced the "unclosable" 'popup of doom' on beta 3.

![img_0028](https://cloud.githubusercontent.com/assets/382934/8830575/c0a8d788-3051-11e5-9fe5-4765a49b697a.PNG)

**Comment by dasilva333** [comment] 2015-07-23 14:17
I changed the what's new to not show on IOS to see if you guys could progress any further and it seems everything else is un clickable after that. I can't test it myself because I can't upgrade to iOS 9 since I'm jailbroken but I've assigned @ssoriche who will be trying a way to sideload the app with debugging to help me figure it out. 

Link to anyone who is interested in trying to sideload TGD debug on ios 9:
https://www.reddit.com/r/jailbreak/comments/39bpwp/fluff_ios_9_allows_users_to_sideload_apps/

**Comment by payote** [comment] 2015-07-23 14:46
Hey Richard,

Thanks for the updated build (2.8.9) - on my iPad Air 2, iOS 9 beta 4, I'm still seeing the "What's new" popup - and I'm still unable to close it. The app doesn't seem to respond to any touch events at all, doesn't make a difference whether the app is in portrait or landscape view.
![img_0029](https://cloud.githubusercontent.com/assets/382934/8853154/399f0d76-310e-11e5-9c37-342dc9faa0e7.PNG)

On an iPhone 6 running iOS 9 beta 4, the same issue exists - popup displays and can't be closed.
![img_6127](https://cloud.githubusercontent.com/assets/382934/8853306/e44c9784-310e-11e5-95ab-9b871874b04f.PNG)

**Comment by dasilva333** [comment] 2015-07-23 14:54
@payote that's what I just said; earlier builds had the What's New disabled so you can try to get to the login page but even so the login page is unresponsive so it doesn't matter whether the What's New is unresponsive or the login page doesn't work either way it's unusable and requires further research

**Comment by tehkemo** [comment] 2015-07-23 15:34
![image](https://cloud.githubusercontent.com/assets/587959/8854506/82afb41e-3160-11e5-932c-43a9ad203c25.png)
If you update the app, sign in and then update to iOS 9 PB2 you'll most likely get stuck on the state above. Also the app is not responding to any taps in both landscape and portrait.

**Comment by payote** [comment] 2015-07-23 15:38
Sorry Richard, I misread your earlier reply.

**Comment by payote** [comment] 2015-07-23 18:50
By the way - I'm not sure the sideloading for iOS 9 you mention will be possible, since the executable container is actually provided by Adobe Build.

**Comment by danielcampo** [comment] 2015-07-23 18:58
I can confirm that the what's new dialog box is still popping up on iOS as
of 7/23/2015 @ 2:57 EST :

[image: Inline image 1]

Still unable to close– landscape or portrait.

Device: GSM iPhone 5 (Model A1428)
OS Build: iOS 9 Beta 4

**Comment by dasilva333** [comment] 2015-07-23 19:01
Closing out this ticket until IOS 9 is officially released, the results are not good when trying to compile the app for IOS 9 using 'phonegap build ios' returns an error message regarding IOS 8.4. I'll revisit compatibility once a final version has been released by Apple. Thanks for everyone's help and feedback stay tuned

**Closed by dasilva333** 2015-07-23 19:01 UTC
Labels: bug
