### ISSUE TITLE
TGD 1.8.9 Android on Galaxy Note 4 - intermittent unresponsiveness

### ISSUE THREAD

**Issue by smstephe** [dasilva333/TowerGhostForDestiny#55] opened 2015-04-17 15:37 UTC
This unfortunately has very few details as there seems to be nothing specific that causes it.  Sometimes I can select several items in quick succession then I have to tap on the next item 2-20 times to get it selected.  Other times I have trouble selecting the first item and have to tap multiple times to get it to respond.  The issues seems to have decreased over the past week with updates (it used to be every item I tried to select had this problem), but still occurs the majority of times I'm using the app.  I wish I had more details to give you.

**Comment by weborican** [comment] 2015-04-19 15:05
I have the same problem on my Nexus, and it is still happening on 1.9.8. It works, but it can take many taps to get some items to respond. It happens very often, to it is not something that is hard to reproduce.

**Comment by Jlear3** [comment] 2015-04-21 16:19
Same thing for galaxy s6 edge. Sometimes it's great, not always.

**Comment by dasilva333** [comment] 2015-04-24 22:49
Hey guys I added a few performance tweaks as of 2.1.0 can you still confirm if it's still unresponsive? Thanks @Jlear3 @weborican @smstephe

**Comment by weborican** [comment] 2015-04-25 17:32
Much, much less often, but it is still there. There was a build (if I remember correctly) that had an almost immediate response to a tap, and that felt very solid. Recent builds though, have a slight delay on taps, which may be why we are experiencing this as we quickly tap around different items.

I will also say that this delay is much less on my iPhone 6 (especially the tap that brings up the bottom banner, the tap to make it go away is about the same on both).

**Comment by dasilva333** [comment] 2015-04-28 23:33
Hey guys I'm closing this issue, as of 2.1.8 I reduced the loading times of some devices from 60+ seconds to 12 seconds, a lot has been done under the hood to make it faster and more responsive than even 2.1.7. If there's a more specific problem anyone is having please open a new issue. Thanks everyone

**Closed by dasilva333** 2015-04-28 23:33 UTC
Labels: enhancement

**Comment by weborican** [comment] 2015-04-29 15:17
I can confirm that on version 2.1.9 both iPhone and Android tapping delays are exactly the same, and I can't reproduce the unresponsive behavior on Android.

**Comment by smstephe** [comment] 2015-04-29 15:38
Definite improvement. Now usable, it isn't perfect, but I think bungie
might be to blame there.
