### ISSUE TITLE
Bungie Patch 1.2 causes maxed items to not show up in the Progress filter

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#192] opened 2015-05-15 23:05 UTC
Since the Bungie 1.2 patch this morning, the "yellow fully upgraded border" surrounding the following is now showing as not fully upgraded:

1. Legendary Weapons 
2. Legendary Armor
3. Exotic Armor

Strangely, fully leveled Exotic Weapons still show the correct yellow border. Wonder if this has something to do with the new HoW light level? Meaning come Tuesday next week, those weapons would NOT be "fully leveled" anymore. But then why do fully leveled Exotic Weapons still have the correct yellow border?

![tgd_bug](https://cloud.githubusercontent.com/assets/3769123/7663250/3999a3c2-fb1c-11e4-88d2-e8669e2a2308.png)

**Comment by M3Rocket** [comment] 2015-05-15 23:07
I'm noticing the same issue on Bungie's web site. So may be a bug on their end.

**Comment by digitaljhelms** [comment] 2015-05-15 23:08
This has been a long standing bug with Destiny. I have quite a few Exotic and Legendary weapons maxed out, either assigned to a character or in the Vault, that do not have the yellow border...

**Comment by M3Rocket** [comment] 2015-05-15 23:15
Hmmm. I have a screen shot from yesterday, and it worked just fine for me then.

**Comment by pattont** [comment] 2015-05-20 12:24
With HoW your legendary weapons are now now longer maxed out because you can put etheric light and raise their DMG. I'm not sure why the exotics do not do that as well with the border, but if you spend the exotic shard and the glimmer, you will get the 365 and the gold border. The rest remain "unmaxed".

**Comment by dasilva333** [comment] 2015-05-20 13:00
Hey guys with the changes introduced in HoW I do notice a problem with how the progress fitler is behaving, treating maxed items as full xp but showing the gold border on it regardless. I'll rename the title and get it fixed thanks

**Comment by dasilva333** [comment] 2015-05-21 15:33
I confirmed this is an issue with the API not much I can do to fix it, I made some improvements but it's still broken due to bad data I'm getting. Closing ticket until Bungie fixes it on their end

**Closed by dasilva333** 2015-05-21 15:33 UTC
Labels: bug
