### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by Dazlaah** [dasilva333/TowerGhostForDestiny#508] opened 2015-12-14 22:24 UTC
Soooooooo close. Was really hoping that this update would see this great app working again as it used too but sadly not. 

Im running it on ipad 2 and i can live with turning it portrait so that the white screen doesnt appear but it still doesnt load fully. It loads 75% of my vault, 20% of my first character and 5% of my second and none of my third. 

If you can help it would be appreciated as this is a great app and very very useful.

**Comment by weborican** [comment] 2015-12-15 01:47
The white screen only occurs if you launch the app for the first time (as in after force quitting it by double tapping on the home button and sliding it out of the way) whilst on landscape mode. If force quit the app, then launch it on portrait mode you'll be OK until you force quit the app again. If you are one of the many that always quits all apps then you will have this problem on every launch (FYI, you don't need to quit apps on iOS devices, that is handled internally by the system).

I'm also running on an iPad 2 and everything is loading just fine. Have you tried uninstalling and reinstalling the app?

**Comment by Dazlaah** [comment] 2015-12-15 15:20
Ah the old uninstall and reinstall trick, gave it a try worked like a charm. I shall never understand why apps need this, but thank you sir all is back to normal.

**Comment by weborican** [comment] 2015-12-15 16:08
The idea behind the "reinstall trick" isn't necessarily because of a corrupted app, but more because of a messed up data file. Uninstalling an app is the easiest way on iOS to blow away that data file, which is analogous to deleting a bad preferences file on a PC.

**Comment by dasilva333** [comment] 2015-12-21 22:45
Duplicate of issue #471 problem already fixed as of 3.7.0.2 let me know if there's still any problems. Thanks guys

**Closed by dasilva333** 2015-12-21 22:45 UTC
