### ISSUE TITLE
No icons on 3.7.0.1 for new weapons

### ISSUE THREAD

**Issue by villiansv** [dasilva333/TowerGhostForDestiny#514] opened 2015-12-20 20:25 UTC
Using 3.7.0.1 on Firefox, MIDA, Plan C, Hard Light have no icons or a meaningful tooltip. They can be moved around, though.

**Comment by DMWill** [comment] 2015-12-20 20:41
I'd love to test this one for ya, but I can't get FF to update to 3.7 no matter how long I wait or what I try.  Anyway, I can say on the standalone windows app (3.7.0.1), there are also no icons.  However, I definitely have tooltips, and they can be transferred too.  I know this isn't a ton of help, but I thought knowing it wasn't just FF was some consolation.

**Comment by nessus42** [comment] 2015-12-20 22:57
I am also experiencing this issue in 3.7.01 in Firefox. The problem is even worse in the latest version that is available for Chrome (in the Google Chrome store). In the Chrome version, some of the newly introduced year-two versions of year-one exotics don't appear at all. For a while I thought that I had somehow lost some of my gear!

Another problem with 3.7.0.1 is that the tooltips for any items are now sometimes missing important information that they used to have (and still have in the Chrome version).

**Comment by DMWill** [comment] 2015-12-21 03:48
I was able to get Firefox to update TGFD to the latest version.  Now I see what you guys were talking about.  The icons are there now though (for me), following the update.  I confirm that tooltips show absolutely nothing but the name and icon for these Year 1 upgraded weapons you mention.  Both the standalone (windows) version and the extension for Chrome (I use it in Opera) have working tooltips.  Many of the additional perks listed in the tooltips are completely missing from nearly everything in all versions I've tested; doesn't include android or iOS.

**Comment by Chase100488** [comment] 2015-12-21 06:47
Quick Question How Did U Guys Get Yours To Update? Mine Is Still At 3.6.9.0 TGD And I Turned The Auto Refresh And Auto Update Off And On But Nothing Changed? I'm Using The Firefox Version Since I Finally Got It Working So I Was Just Curious Thanks In Advance If U Can Help

**Comment by nessus42** [comment] 2015-12-21 19:37
@Chase100488 Well, it's kind of a pain in the butt. Firefox won't install the new version b/c it says that it's not signed by a trusted authority. You can go to the security preferences and tell it to install such extensions anyway, but Firefox then still refuses, but it gives you instructions on how to edit a hidden setting that you get to via a magic URL. Once you do that, you can install the latest version of Tower Ghost into Firefox.

**Comment by dasilva333** [comment] 2015-12-21 23:00
Problem should be fixed as of 3.7.0.2 let me know if anyone still has a problem with missing icons

As for the Firefox issue this is the link that provides instruction on how to enable untrusted addons:
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-can-i-do-if-firefox-disables-an-installed-unsigned-add-on

**Closed by dasilva333** 2015-12-21 23:00 UTC

**Comment by nessus42** [comment] 2015-12-22 00:11
3.7.0.2 fixes the most egregious issues. For me (using Firefox), the new Year 1 exotics have empty tooltips, however. And many of the other tooltips, although informationally complete (or so it seems), often have some broken icons next to the informational text.
