### ISSUE TITLE
3.2.8 wont even load

### ISSUE THREAD

**Issue by lllgurulll** [dasilva333/TowerGhostForDestiny#405] opened 2015-09-25 01:48 UTC
Please provide a link to 3.2.7 so i can access my profile again. I am done accepting upgrades for this app.

**Comment by lllgurulll** [comment] 2015-09-25 12:14
Found a link for 3.2.4 to get me by but auto update is officially disabled now.   Sure hope this gets sorted out

**Comment by dasilva333** [comment] 2015-09-25 18:01
@lllgurulll Try 3.2.9 Are you on Chrome?

**Comment by binkley33w20** [comment] 2015-09-25 20:26
Updated to 3.2.9 on android 5.0.1 with same results. Will not load.

**Comment by ealaney** [comment] 2015-09-25 20:59
I also have the problem. TGD 3.2.9 on Android 5.0 / Samsung Galaxy S5. The app is stuck on the "loading arsenal from Bungie" screen. Willing to help with testing, if needed.

**Comment by lllgurulll** [comment] 2015-09-25 21:01
No, I only use android.  This won't load at all.  Just stays on the green
loading bar indefinitely.  Uninstalled and reinstalled multiple times and
tried on more than one android device.  I'm using 3.2.4 now as it works.

**Comment by dasilva333** [comment] 2015-09-25 21:43
@lllgurulll can you test 3.2.5 and let me know if that works for you? ill be developing a debug apk to figure out why it's not loading further instructions will be provided later. Thanks guys

**Comment by locolos1982** [comment] 2015-09-25 21:51
I'm in the same situation. The app stays at the loading screen as well.

**Comment by dasilva333** [comment] 2015-09-25 22:03
Guys I tried 3.2.9 on my android device and I can't reproduce any loading issues.

Install this on your android device:
https://build.phonegap.com/apps/1398768/download/android

Visit jsconsole.com

type :listen 783F3A78-A017-4760-8838-98FB1B7DEEB9

Open the app and load it up, if you see any errors or crashes provide a log of that here.

Thanks guys

**Comment by locolos1982** [comment] 2015-09-25 22:11
What does that do

**Comment by dasilva333** [comment] 2015-09-25 22:48
the link is for tgd 3.2.9 debug build visiting the site will connect you to the app and allow you to provide me with error logs. thanks again

**Comment by locolos1982** [comment] 2015-09-25 22:54
Ok that link isn't working for me.

**Comment by locolos1982** [comment] 2015-09-25 22:55
I guess I will just have to wait until the next update

**Comment by dasilva333** [comment] 2015-09-25 22:56
Oh sorry the link was set to private, it's been fixed now try it again it should download an apk

**Comment by ealaney** [comment] 2015-09-25 23:23
I installed the debug build, went to jsconsole.com <http://jsconsole.com/>, entered the “listen” command, and then ran the debug build.  The app initialized, told me that it found an updated build, and proceeded to perform an in-place update.  After that, the app continued and - of course - loaded my data successfully.  Prior to all this, I had done all of the following in an attempt to get the data to load:
1. Reboot phone
2. Clear cache
3. Clear all data
4. Uninstall / reinstall

Eric

**Comment by binkley33w20** [comment] 2015-09-25 23:49
Installed debug build and once the app opened it found the update and works
now. Prompted me to remove remote script. Won't even pretend I know how to
do that.

**Comment by dasilva333** [comment] 2015-09-25 23:51
Good feedback @ealaney and @binkley33w20  I'm building another apk this time without Hydration, same link. I'm not sure why that would make a difference but it's not used in the store version. So this time you'll be testing 3.2.9 with jsconsole and w/o Hydra. If the app prompts you to update just uninstall that one and install this new apk all together. Thanks for your help and here's the new listen hash:

8C3B4AA0-B7B3-48B7-B4B3-01248F987C36

**Comment by dasilva333** [comment] 2015-09-26 00:18
I figured it out, thanks for your help guys, expect it fixed by 3.3.1

**Comment by dasilva333** [comment] 2015-09-26 00:48
Here's a link to 3.3.1 if you'd like to get it before it hits stores: 
https://build.phonegap.com/apps/1426365/download/android
thanks again let me know if there's still problems after this so I can reopen it

**Closed by dasilva333** 2015-09-26 00:48 UTC
Labels: bug

**Comment by ealaney** [comment] 2015-09-26 01:08
Works great! Thanks for the super response!

Eric A. Laney 
813-731-1369 mobile
