### ISSUE TITLE
most of screen is blank

### ISSUE THREAD

**Issue by kiplimw** [dasilva333/TowerGhostForDestiny#479] opened 2015-11-30 23:15 UTC
This is a great app, but it started showing 3/4 of the portrait display as a white screen on a IPad with OS 9.1 (13B143).

I re-installed, but it did not help.

**Comment by dasilva333** [comment] 2015-12-01 14:59
duplicate of issue #471 please leave feedback there while I track the issue. thanks

**Closed by dasilva333** 2015-12-01 14:59 UTC
