### ISSUE TITLE
Attempt to equip decoherant engram

### ISSUE THREAD

**Issue by r3mus** [dasilva333/TowerGhostForDestiny#182] opened 2015-05-14 17:28 UTC
Here's a screenshot - should be all you need. (This time I checked for dupes first :)

![screenshot_551](https://cloud.githubusercontent.com/assets/1480253/7637601/ffde6198-fa23-11e4-832f-bb5582bfac4b.png)

**Comment by dasilva333** [comment] 2015-05-14 17:32
Seems to be working as expected, the engram will simply be moved out and not equipped so it shouldn't be an issue. Is something wrong when you try that? Do you get an error? Let me know Thx

**Comment by r3mus** [comment] 2015-05-14 17:33
Yeah - it completely blew up. I had to move the engram to the vault to get it to work. Didn’t drop an error though, which was strange, it just hung. I didn’t check the console for errors, but I could try and reproduce it to get you that.

On May 14, 2015 at 10:32:11 AM, Richard Pinedo (notifications@github.com) wrote:

Seems to be working as expected, the engram will simply be moved out and not equipped so it shouldn't be an issue. Is something wrong when you try that? Do you get an error? Let me know Thx

**Comment by dasilva333** [comment] 2015-05-14 17:34
Yes pls do and post and console errors you get Thx a lot man

**Comment by r3mus** [comment] 2015-05-14 17:40
Nothing in the console, but this time an error did come up:

**No more items to try to unequip the Abyss Defiant**
On May 14, 2015 at 10:34:40 AM, Richard Pinedo (notifications@github.com) wrote:

Yes pls do and post and console errors you get Thx a lot man

**Comment by dasilva333** [comment] 2015-05-15 00:48
Can you get it to say "No more items to try to unequip the " on a consistent basis? I can't reproduce either of the problems. The second time that error came up was it transferring an engram as the swap? What were the conditions for that? Please let me know as much detail as you can so I can try to reproduce it thanks.

**Comment by r3mus** [comment] 2015-05-15 01:01
I'll get it to reproduce again and send you a screenshot of the inventory in its current state. Would an extract of local storage help too?

**Comment by dasilva333** [comment] 2015-05-15 02:37
Not really but if you could figure out how to get it to trigger would be most excellent and enough for me to fix it hopefully. Let me know anything you can thanks

**Comment by r3mus** [comment] 2015-05-15 03:47
Sigh. Spent the last 20 minutes trying to reproduce it. No dice. All I know is I had the engram and Oversoul Edict (equipped) on my Titan, tried to use a loadout to transfer to my Hunter (who was active, in game). The Abyss Defiant in the error I posted was currently equipped on the hunter. 

If I manage to encounter it again, I'll let you know!

**Comment by dasilva333** [comment] 2015-08-15 18:28
As of version 2.9.2 transfers and loadouts was revamped I don't think this should be an issue anymore. Please let me know otherwise. Thanks

**Closed by dasilva333** 2015-08-15 18:28 UTC
Labels: bug
