### ISSUE TITLE
"Origin header does not match the provided API key"

### ISSUE THREAD

**Issue by euphoriccake** [dasilva333/TowerGhostForDestiny#672] opened 2016-10-25 22:59 UTC
I've been getting that error whenever I try to transfer any of my items. TGD worked just last night, then when the Festival of the Lost update dropped, my TGD stopped transferring items around and started getting that error with any item, whether I'm storing it in the vault, or transferring to any of my characters.

**Comment by dasilva333** [comment] 2016-10-26 01:15
I can confirm this is happening on Chrome appearing as that error, also appears as Please Sign In to Continue on iOS. I'll have to talk to Bungie and see what's going on. Thanks for the heads up @euphoriccake

**Comment by edmiller47** [comment] 2016-10-27 02:45
FYI This was also happening with other item managers - DIM and Ishtar Commander - and has been fixed in those tools

**Comment by dasilva333** [comment] 2016-10-27 15:55
Problem has been fixed let me know if this is still an issue for you @edmiller47 or @euphoriccake 
thanks guys

**Closed by dasilva333** 2016-10-27 15:55 UTC
Labels: bug

**Comment by edmiller47** [comment] 2016-10-27 16:51
Seems to be working now, thanks!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Richard PinedoSent: Thursday, October 27, 2016 11:55 AMTo: dasilva333/TowerGhostForDestinyReply To: dasilva333/TowerGhostForDestinyCc: edmiller47; MentionSubject: Re: [dasilva333/TowerGhostForDestiny] "Origin header does not match the provided API key" (#672)Problem has been fixed let me know if this is still an issue for you @edmiller47 or @euphoriccake 
thanks guys

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dasilva333/TowerGhostForDestiny","title":"dasilva333/TowerGhostForDestiny","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dasilva333/TowerGhostForDestiny"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dasilva333 in #672: Problem has been fixed let me know if this is still an issue for you @edmiller47 or @euphoriccake \r\nthanks guys"}],"action":{"name":"View Issue","url":"https://github.com/dasilva333/TowerGhostForDestiny/issues/672#issuecomment-256687281"}}}

**Comment by JakobHartman** [comment] 2017-12-18 22:58
How was this fixed?
