### ISSUE TITLE
Initiating a drag and drop move activates tooltips

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#353] opened 2015-09-04 20:17 UTC
Using the Chrome extension, every time I click and drag an item (even if for a short distance without actually moving it to a different location) it enables the "DestinyDB Tooltips", but without any indication in the UI (no checkbox next to the option). It then takes me to enable then disable the option for it to stop showing the tooltips. This process repeats itself every time I try to drag and drop an item.

This is still happening on 3.1.0, but I have noticed it in at least the last 2 or 3 releases.

**Comment by dasilva333** [comment] 2015-09-06 12:52
I can't reproduce it, works fine for me whether the tooltip is already activated or not I can't get the tooltip to stay once dragging begins, I also don't understand what you mean by the checkbox option. I think a good way to fix this problem is if you provide a short gif of the problem there's various free tools online here's a few you could try:

https://www.screenr.com/

https://gyazo.com/

**Comment by weborican** [comment] 2015-09-06 17:23
I'll have to check those out, my fav has always been http://cloudconvert.com  :-)

Here is the gif of the problem as I see it:

![tgd_tootip_bug_720](https://cloud.githubusercontent.com/assets/12019978/9705664/f99f646c-5491-11e5-8def-32272bb28526.gif)

**Comment by dasilva333** [comment] 2015-09-06 17:35
Thanks for the animation it seems there isn't a problem just a misunderstanding. The tooltips are still expected to function as normally when drag and drop is enabled the only change is that the tooltip will not be actively shown while drag and drop is in use (eg while an item is being dragged)

Thanks for your feedback

**Comment by weborican** [comment] 2015-09-06 17:37
But they tooltips are turned OFF, they automagically turn ON after a drag-n-drop action and the only way to turn them back OFF is to turn then ON and the back OFF again.

**Comment by dasilva333** [comment] 2015-09-07 21:42
Oh I see what you mean! I can reproduce it and fix it. Thanks for clarifying I really didn't get it until now

**Comment by dasilva333** [comment] 2015-09-10 19:27
problem fixed as of 3.1.5+ @weborican if you can confirm its fixed that'll be great

**Closed by dasilva333** 2015-09-10 19:27 UTC
Labels: bug

**Comment by weborican** [comment] 2015-09-10 19:37
Successful bug squashing confirmed.

Thanks!
