### ISSUE TITLE
level sections

### ISSUE THREAD

**Issue by Markyb0y** [dasilva333/TowerGhostForDestiny#16] opened 2015-04-10 21:56 UTC
more of a request than major issue really

I use this on my laptop more often than not so its great to see all 3 characters and the vault on a single screen, however it gets messy when viewing everything.
can you alter the layout or supply the option to have all sections line up, for example if my first character has 9 primary weapons it 3 rows, if my 2nd character only has 2 weapons then in the next section of special weapons for my 2nd character it starts halfway down my first characters primaries.

currently looks like this
Primary     Primary     Primary
XXXX        XXXX        XXX
XXXX        XXX       
XX                              Special
                 Special      XX
Special     XXXX
XXX

Would love it to look like this
Primary     Primary     Primary
XXXX        XXXX        XXX
XXXX        XXX       
XX                              
                      
Special     Special      Special 
XXX          XXXX       XX

I realise as I write this that it isnt the easiest thing to explain, hope you understand and can help

keep up the great work on the app!

Markyb0y

**Comment by dasilva333** [comment] 2015-04-11 19:03
Thanks for your feedback a screenshot or mockup would help me understand what you're trying to say. I'm going to be improving it with a swipe system for each profiles but I don't think that's what you're talking about. Let me know thanks

**Comment by wein3967** [comment] 2015-04-13 21:04
I'm pretty sure I know exactly what MarkyB0y is referring to. Basically the "sections" should assume a full inventory for each catagory (e.g., 6x6 plus 1 equipped).

Here is the the current view style:
![current layout](https://cloud.githubusercontent.com/assets/11590326/7125470/9fb6d510-e1f6-11e4-92b1-7c3fc9e239e8.png)
 Here is what it would look like if sections were aligned:
![aligned layout](https://cloud.githubusercontent.com/assets/11590326/7125476/aeb3b344-e1f6-11e4-9623-a517dfb7ef12.png)

This makes it much easier to see what is going on between characters.

**Comment by dasilva333** [comment] 2015-04-14 00:34
Ah yes, the original Chrome only version used to work that way and then I changed the layouts to be flexible for mobile and I lost it because of the way I handle the sizing. This is a good request that I agree to and would like to see put back however it's not easy so I'll leave this ticket open until I can get it done thanks guys

**Comment by dasilva333** [comment] 2015-04-16 00:29
@Markyb0y  and @wein3967 Try version 1.8.4 and report back to close this thanks

**Comment by Markyb0y** [comment] 2015-04-16 07:11
1.8.4 is great and does exactly what I requested, thanks

if you are feeling really awesome I have ahd another thought, now we have the vertical looking all lovely how about dynamic horizontal sizing to fill the browser? so instead of 4 columns of 4 icons maybe 4 columns of 6 pr 7 icons depending on browser width? this way we could almost get a full screen with no scrolling required, everything at your fingertips :)

keep up the great work!

**Comment by Titus-s** [comment] 2015-04-16 07:53
It looks really fine, but there is additional empty fourth row in each kind of items.
Please, take look at screenshot:
![screenshot_2015 04 16_09h36m23s_026-50_](https://cloud.githubusercontent.com/assets/11790750/7176386/2ecd2226-e41e-11e4-8d3a-a45d1ad63c2b.jpg)

**Comment by Markyb0y** [comment] 2015-04-16 10:12
I see the same behaviour

**Comment by dasilva333** [comment] 2015-04-16 11:39
Damn I hate to see that happen, try updating to 1.8.5 I simply added a longer delay for calculating the size of the box hopefully that fixes it, please report back soon because if it's not fixed in 1.8.5 I'll have to back out the change completely until I can get something that works.

Thanks guys

You can find the downloads for Chrome/Firefox here:
https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist

**Comment by wein3967** [comment] 2015-04-16 11:54
Just got around to testing this. I'm using Chrome on Windows 8.1

I am not seeing that issue (extra row) on 1.8.4
![1 8 4 inventory](https://cloud.githubusercontent.com/assets/11590326/7180238/701e4e12-e405-11e4-9dcc-ba9c759af03b.png)

**Comment by Titus-s** [comment] 2015-04-16 12:15
I've just downloaded new version - 1.8.5 and install on Chrome. Issue still persist:
![image](https://cloud.githubusercontent.com/assets/11790750/7180552/ef595b94-e442-11e4-8561-e4ad58decfba.png)

**Comment by lanejcf** [comment] 2015-04-16 12:46
I see the same  as Titus-s above whilst running 1.8.5.

I think the issue is that the section with the most rows of the 3 guardians  is used to size all sections of each guardian, rather than acting on each section separately.

Great program

**Comment by dasilva333** [comment] 2015-04-16 13:15
I realized the reason it's happening is because I'm assuming all buckets are 10 max where there's some buckets that are 15 or 20 so I didn't catch it because those buckets aren't that full for me. Try version 1.8.6 for Chrome/Firefox I changed the way it calculates the size. Thanks guys

**Comment by Titus-s** [comment] 2015-04-16 13:55
It looks fine now:
![image](https://cloud.githubusercontent.com/assets/11790750/7182317/ddc57a94-e450-11e4-84a0-4db285173f73.png)

**Comment by dasilva333** [comment] 2015-04-16 14:01
Perfect at last I can close this ticket! Thanks for all your help guys

**Closed by dasilva333** 2015-04-16 14:01 UTC
Labels: enhancement
