### ISSUE TITLE
TTK filter set not working

### ISSUE THREAD

**Issue by tmalfor** [dasilva333/TowerGhostForDestiny#480] opened 2015-12-01 03:31 UTC
I noticed in your most recent notes that we could use the TTK option under set to view all of our year 2 items. This doesn't seem to be true though. All of the raid items are automatically excluded. I do not know if I earn banner and trials of Osiris gear are also excluded. Worth checking

**Comment by dasilva333** [comment] 2015-12-01 15:01
Thanks I'll check it out and debug it, feel free to do more research and let me know if there's any other groups I missed. Thanks

**Comment by tmalfor** [comment] 2015-12-02 13:15
I downloaded 3.6.5.6 and still can't choose TTK to see all Year 2 items.  I don't play a lot of PvP so there is a limit to how much I can test be on the raid. The raid gear definitely isn't showing

**Comment by dasilva333** [comment] 2015-12-02 14:55
@tmalfor under Set there is a new option called "Year 2 Items" and "Year 1 Items" unfortunately tho it seems the auto update is not properly showing the new changes. I"ll have to check it out. Thanks

**Comment by tmalfor** [comment] 2015-12-02 15:07
Hey did look for that and when I didn't see it I just assumed you had it set up the same way you did before. Where you wanted us to select TTK

**Comment by weborican** [comment] 2015-12-02 21:25
Just checked out the changes made on version 3.6.5.8 for the Year 1 and Year 2 filter set, but found the "The Hothead" rocket launcher (drops as 150, and mine is still at 150) showing up as a Year 1 weapon. At first I was surprised this was a Year 1 item, but then I noticed the TTK icon on top-right corner.

**Comment by dasilva333** [comment] 2015-12-02 21:42
@weborican good man thank you. the set filter was officially available as of 3.6.5.6 but due to a problem w auto update it didnt become available to everyone until 3.6.5.8. Anyhow this revision deals with the filter in two ways:

Year 2 Items - Everything over 170 or sourced from TTK
Year 1 Items - everything under 170

Ideally this should put Hothead under Year 2 items because even tho its not over 170 it's still sourced from TTK. The way you can tell where it's sourced from is by looking at the Armory:

https://www.bungie.net/en/armory/Detail?type=item&item=3677466371&itemname=The%20Hothead

under Sources you can see The Taken King in the list so theoretically the Y2 Filter should display the hothead, @weborican please provide me with your Share URL so I can debug the problem.

Thanks!

**Comment by weborican** [comment] 2015-12-02 21:46
https://towerghostfordestiny.com/share/?psn/weborican

**Comment by dasilva333** [comment] 2015-12-03 20:24
@weborican I can't seem to reproduce the problem, the URL should be working today. Try it yourself under Set use the Year 2 Items and you should still see the Hothead in the list. Set it to Year 1 and it dissapears. Let me know if you can confirm. Thanks

**Comment by weborican** [comment] 2015-12-04 16:36
I can confirm it is working properly now. Thanks!

**Comment by dasilva333** [comment] 2015-12-04 16:37
Yup as of 3.6.6.1 it should be working properly. Thanks for confirming I'll go ahead and close this ticket now

**Closed by dasilva333** 2015-12-04 16:37 UTC
Labels: bug
