### ISSUE TITLE
Landscape Tablet Mode layout too large

### ISSUE THREAD

**Issue by mecster09** [dasilva333/TowerGhostForDestiny#448] opened 2015-10-26 08:50 UTC
Since latest update the landscape mode now only shows 2 characters next to the vault when previously it showed all 3. Not sure if this was a requested change however I personally preferred the old smaller layout. If you scroll down you view the third however you can't see the vault as it doesn't scroll with it. 
![screenshot_2015-10-26-08-46-49](https://cloud.githubusercontent.com/assets/10955614/10724702/615495ca-7bbe-11e5-84ad-b7761290feb3.png)

**Comment by Titus-s** [comment] 2015-10-26 12:41
Did you try to set Number of Columns in View -> View Options?

**Comment by mecster09** [comment] 2015-10-26 12:54
Thanks for this, didn't realise there was an extended view option as
previously it always showed 4 columns on the tablet.

Many Thanks!!!

**Comment by dasilva333** [comment] 2015-10-26 14:05
@mecster09 recently i changed the breakpoints to behave differently and I made worse the amount of columns for some devices, I will be going into the stylesheet at a later point and resolving all the breakpoints that are still not quite right. For reference can you provide me your exactly tablet model, the resolution, and how many columns you'd like to see in both orientations for example:

galaxy tab 10.1 - 1024x768 - 3 portrait, 4 landscape

Also as @Titus-s mentioned you are free to change the amount of columns per view manually in View Options until it is resolved. Thanks for your help

**Comment by lightmaster** [comment] 2015-10-27 00:57
Just to chime in on suggested number of columns for default, I've got a Note 4 SM-N910V 2560 x 1440 Quad HD and I feel the Note 4 should have 2 coumns on portrait and 4 on landscape.

**Comment by mecster09** [comment] 2015-10-27 08:12
Sony Xperia Z3 Compact tablet - 1920x1200 - 2 columns portrait, 4 landscape

Sony Xperia Z5 phone - 1920x1080 - 2 columns portrait, 2/3 landscape

Just to chime in on suggested number of columns for default, I've got a
Note 4 SM-N910V 2560 x 1440 Quad HD and I feel the Note 4 should have 2
coumns on portrait and 4 on landscape.

—
Reply to this email directly or view it on GitHub
<https://github.com/dasilva333/TowerGhostForDestiny/issues/448#issuecomment-151329363>
.

**Comment by dasilva333** [comment] 2015-10-29 15:32
@lightmaster the Note 4 was doing 1/4 I changed it to 2/4
@mecster09 the Z5 was doing 1/4 I changed it to 2/3
regarding the Z3 tablet I couldn't find a good resource to find the pixelRatio, can you visit this site and let me know what it is? Thanks http://devicepixelratio.com/

**Comment by mecster09** [comment] 2015-10-29 22:29
Z3 Compact tablet is 2 whilst Z5 mobile is 3

**Comment by wkearney99** [comment] 2015-11-15 21:45
I want to also point out that a recent version has caused problems on a nexus 7 2013 second generation model. This tablet was working just fine before showing four columns wide on its 1920 by 1080 resolution. But some recent update has caused it to fail to display all four side by side. Even if I go into the view options and change for 4 columns, like I had to do in the past, it still does not work. This is a new bug but I can't tell what version of the app on running because there's no about box! I still have whatever version that works installed on one tablet, but the newest ones that are auto-updated do not work properly.

 It's a great app, please find a fix!

**Comment by wkearney99** [comment] 2015-11-15 21:47
Correction, there is an about box! I checked and its version 3.4.6 that's still working fine, properly showing all four columns. I should also point out that these tablets are now being updated to Android 6

**Comment by dasilva333** [comment] 2015-11-16 17:48
@wkearney99 please post some screenshots of your device with the number of columns showing and then post another one with the View Options open so I can figure out the problem.

Thanks

**Comment by reallukx** [comment] 2015-11-16 18:52
same problem with two columns on my htc one 1080 x 1920 pixels
![2015-11-16 18 33 37](https://cloud.githubusercontent.com/assets/15876460/11191445/929b5f36-8c9b-11e5-86c4-0bb79abcb864.png)

**Comment by dasilva333** [comment] 2015-11-16 18:55
@reallukx so 2 columns on the HTC One is too small or too large? Also please provide the pixel ratio of your device found here: http://devicepixelratio.com/ Lastly if you'd like to manually change the # of columns to a preset amount you can go to View > View Options and set the appropriate row to the # of columns you want.

**Comment by Ken17** [comment] 2015-11-16 19:02
Same with 3 columns

**Comment by dasilva333** [comment] 2015-11-16 19:21
@Ken17 I can't help you w/o a proper description of the problem, a screenshot, and the details of your device. Thanks

**Comment by mecster09** [comment] 2015-11-17 19:16
No idea what the latest update has done but now cannot use the app at all.
Landscape mode only shows 2 columns even when changing options to 4, on
portrait mode cannot activate the 2nd or 3rd character.

Sony Xperia Z3 Compact tablet

**Comment by dombauer** [comment] 2015-11-20 18:08
Hey, thx for the really quick reply to my email. Yes, i checked the view options. Played around a bit and set everything back to default. Always the same: two cols in portrait and also two in landscape mode. It used to be one col in p and three in ls. Which was great for my nexus 5 (5" 1080x1920px).

Thx and gl!
Hope you find a solution.
Otherwise very nice work!
Dombauer

![screenshot_20151120-075803](https://cloud.githubusercontent.com/assets/15946759/11307650/e6656b40-8fb9-11e5-84df-803f958d0400.png)

![screenshot_20151120-075758](https://cloud.githubusercontent.com/assets/15946759/11307621/caf3e9ae-8fb9-11e5-9b8e-39005514324d.png)

**Comment by dasilva333** [comment] 2015-11-20 18:41
What about the view options? Did it work?

**Comment by dombauer** [comment] 2015-11-20 18:48
As i said, played around, tried different settings, but it didn't fix the column-count-issue... Only changed the margins/column widths.
Thx

**Comment by dasilva333** [comment] 2015-11-20 21:35
@dombauer for Vault Mode you can have Default or Custom, if you set it to Custom then you lose the ability to control the # of columns so make sure it's set to default. Once set to Default try changing the xs/md/lg values to different numbers and see if the changes the number of columns. Please provide a screenshot of your View Options open so I can see what happens if you try to enable 3 columns for example. Thanks

**Comment by dombauer** [comment] 2015-11-25 19:22
Hey, i never realised what that column number matrix in the view settings meant. Never had to, cause tgd worked fine for me with the default 1 2 3 4 setting. Now i set it to 1 1 3 3 and that fixes my problems. TYVM for this awesome app!

**Comment by dombauer** [comment] 2015-11-25 19:26
Ps: you got my appreciation by my friend ulrich@einweg, cause i dont have a pp account.

**Comment by dasilva333** [comment] 2015-11-25 21:26
@dombauer Right I'm trying to fix it so that the matrix can say 1 2 3 4 and it'll look at the 'right' settings or what looks best basically. Expect it fixed soon. Thanks for the feedback

**Comment by dasilva333** [comment] 2015-11-25 21:38
@Ken17 and @mecster09 @lightmaster @mecster09 does it look alright to you guys when it's set to the default 1 2 3 4 setting? Let me know thanks

**Comment by dombauer** [comment] 2015-11-28 20:59
So, my layout problem is fixed, but now i do not get any popups/tooltips. When tap or long-tap an item, nothing happens. But tapping an non-transferable item like weapon-order-packets, it still shows the api-message ("not transferable" etc). 

But this would be another ticket. 
I am in the middle of moving to anoter city. Get back to you, when i'm settled down...
Laters

**Comment by dasilva333** [comment] 2015-11-29 22:19
@dombauer it seems the input issue is caused by a bad update, clearing the app cache and reloading the app should fix it. Thanks

**Comment by dombauer** [comment] 2015-11-30 20:17
Is fixed. Tyvm!
Am 29.11.2015 11:19 nachm. schrieb "Richard Pinedo" <
notifications@github.com>:

**Comment by dasilva333** [comment] 2016-01-04 21:44
It seems the layout problems have been fixed haven't received any complaints about the way it looks, closing this issue as solved. feel free to open a new issue or comment on this one if there's still any problems. thanks guys

**Closed by dasilva333** 2016-01-04 21:44 UTC
Labels: enhancement
