### ISSUE TITLE
Using the 'Progress' tab and selecting 'Full XP' lists some maxed out weapons.

### ISSUE THREAD

**Issue by schubydoo** [dasilva333/TowerGhostForDestiny#198] opened 2015-05-17 16:54 UTC
This seems to be a newer issue as it didn't occur last week.  However when selecting 'Full XP' to view items that still require upgrades will occasionally list maxed out (gold border) items as well.

**Comment by schubydoo** [comment] 2015-05-18 17:47
![untitled](https://cloud.githubusercontent.com/assets/12485317/7686537/3bf8f9d4-fd4b-11e4-9a8e-4731d8c4def0.png)

**Comment by dasilva333** [comment] 2015-06-16 18:29
Unfortunately the APi is still buggy even after 30 days from when the issue is been reported, not much I can do to fix it, closing it out until Bungie comes up with a fix on their end

**Closed by dasilva333** 2015-06-16 18:29 UTC
