### ISSUE TITLE
Items retrieved from Postmaster not displaying without complete restart of app/plug-in

### ISSUE THREAD

**Issue by j-3-s** [dasilva333/TowerGhostForDestiny#603] opened 2016-05-06 20:33 UTC
Items pulled from the Postmaster do not show in the player's inventory, even with a category-specific and/or full refresh, until TGD is completely shut down and restarted. Neither waiting an extended period of time nor manually moving the item(s) to the vault and then back to a character resolve the issue.

Tested in Chrome, Firefox, and Windows standalone across multiple characters and item categories (weapons, armor, materials). Just started noticing it over the last few days, so I'm assuming it appeared in one of the most recent builds.

**Comment by dasilva333** [comment] 2016-05-10 13:19
Thank you for this bug report, so just to make sure I understand you're saying TGD loads, you do an activity and for whatever reason the loot goes to your Postmaster, at that point refreshing TGD via all the tools never updates the inventory? Only way to refresh it is to reopen the app? Alright I'll test it today Thanks for the report!

**Comment by j-3-s** [comment] 2016-05-11 01:45
In my case, the items are typically already in my Postmaster, so the steps to reproduce would be along the lines of:

1. Start TGD
2. Retrieve item from Postmaster
3. Wait 5 minutes
4. Refresh TGD, item doesn't show
5. Refresh item category (e.g. Armor), item doesn't show
6. Refresh item sub-category (e.g. Gauntlets), item doesn't show
7. Close and restart TGD, item shows

**Comment by macnode** [comment] 2016-05-11 15:54
While not fact in any way, I have a feeling this is related to the planetary materials not showing bug. Same symptoms.

**Comment by j-3-s** [comment] 2016-05-12 05:04
Issue can most likely be closed as it appears to have been resolved with a recent update. Just had someone else who was also experiencing the problem mention that they were once again able to successfully see items after a refresh. Decided to go ahead and test it myself, and, as far as I can tell, everything seems to be working as expected.

**Comment by dasilva333** [comment] 2016-05-12 15:42
@macnode let me know if it's still a problem for you in 3.9.0.4 otherwise the problem is fixed. There's still issues with materials and consumables but that will be fixed as part of another ticket.

Thanks guys!

**Closed by dasilva333** 2016-05-12 15:42 UTC
Labels: bug
