### ISSUE TITLE
[Bug] 3.3.8 won't transfer armor loadouts between my two titans.

### ISSUE THREAD

**Issue by nessus42** [dasilva333/TowerGhostForDestiny#427] opened 2015-10-10 20:23 UTC
Hi, incredible piece of software. Like with my TiVo, I can't imagine how I lived life before this program existed.

There's a bug, however, that I first noticed in version 3.3.8 (running in Chrome on a Mac). I can't transfer armor using a loadout between my two titans. (The first titan is in the leftmost colum and the second titan is in the rightmost column.) When the armor is on the first titan, for instance, and I try to transfer it to the second titan, TGfD acts as if I'm trying to transfer the armor onto the first titan rather than the second titan (I can tell b/c of the emblems displayed in the list of transfers it's going to make), and for each item TGfD says that it is not going to do anything with item.

If I try to transfer the armor onto the same titan that's is already on, instead, I actually see little bits of Javascript in the pop-up list of what TGfD wants to do. The Javascript looks like this: "function d(){if(0". 

|>oug

P.S. Just in case it's relevant, my third character is a warlock and is in the middle column. I have them columnized by creation date, rather than most-recently used.

**Comment by nessus42** [comment] 2015-10-10 20:50
Also, the Progress menu is broken. If I select anything other than "all", then all armor and weapons disappear completely from the display (ghosts stay there, though). Selecting "all" does not undo the damage, but using "Clear Filters" does.

|>oug

P.S. I used to be able to use Version 3.2.6 of the Mac application to work around the loadout bug, but now if I start up this program, all I get is an empty screen with no items in it. (The menus are there.) If I press the refresh icon, then it says that it is loading my arsenal from Bungie, but then the progress bar just churns forever, and nothing else happens.

**Comment by dasilva333** [comment] 2015-10-12 20:45
@nessus42 please confirm if the problem is still present in 3.4.0 once it's available thanks

**Comment by nessus42** [comment] 2015-10-12 22:48
Okay, will do.

**Comment by nessus42** [comment] 2015-10-13 06:52
I just checked, and the bug exists and is exactly the same in 3.4.0.

**Comment by dasilva333** [comment] 2015-10-14 13:15
@nessus42 Unfortunately I haven't been able to test the problem to fix it, I have 1 of each character and I don't have an account I can access that has 2 of the same classes. I'l mark this as help wanted so somebody can offer their assistance with their account.
Thanks

**Comment by nessus42** [comment] 2015-10-14 14:54
@dasilva333 I don't know for sure that the problem is actually related to having two characters of the same class. E.g., I can't transfer my Titan armor loadout onto my Warlock either. I didn't try that earlier, b/c it's not that sensible a thing to do, but it should still work. I get exactly the same error, though. The transfer pop-up shows that it wants to move all the armor onto the first character, and then says for each item that there's nothing to do. (

Is there a debug log somewhere that I can send you?

Also, I don't recall what happens when I try to transfer armor back from my second Titan to my first Titan. I can try that out too, if you would find that information to be useful.

|>oug

P.S. Weapon load-outs transfer just fine. I haven't tried making a combined weapons and armor loadout. Perhaps I should try that to see what happens.

**Comment by dasilva333** [comment] 2015-10-14 14:57
The problem is related to having two characters because there is code in place to prevent transferring armor to a class it doesnt belong to, in other words attempting to transfer Titan armor to a Warlock via loadouts will not allow you to do so because it know's its not applicable.

**Comment by nessus42** [comment] 2015-10-14 16:32
I see. Maybe as a work-around, the feature that protects you from transferring armor onto the wrong class could just be disabled until the bug is fixed. Personally, I don't need such protection myself because I tend not to make that mistake, and even if I did make the occasional mistake, that would be a lot better than not being able to use armor loadouts at all!

**Comment by dasilva333** [comment] 2015-10-15 01:54
@nessus42 found the issue problem fixed as of 3.4.3

**Comment by nessus42** [comment] 2015-10-15 02:18
Excellent. Thanks so much!

**Comment by nessus42** [comment] 2015-10-15 17:55
I have verified that the fix works for me. Thanks for making (and fixing) this invaluable tool!

**Closed** 2015-10-15 17:59 UTC
Labels: bug, help wanted

**Comment by nessus42** [comment] 2015-10-15 18:01
P.S. I just noticed another minor bug. Don't know if it's worth filing an issue, though. When I tell TGfD to maximize my light level it correctly maximizes it to 298, but the message that gets displayed says that it maximized it to 275.

I'm not losing any sleep over this one, but you probably want to add it to your bug list.
