### ISSUE TITLE
Vault fails to load on 1st Gen Amazon Kindle Fire

### ISSUE THREAD

**Issue by MostDefiantly** [dasilva333/TowerGhostForDestiny#58] opened 2015-04-17 20:50 UTC
Installed app from Amazon App Store directly. Authenticated with PSN on bungie.net as directed, page fully loads but never closes - so app sits empty with blue bar and nothing else.

App Version: 1.8.9
OS Version: 6.3.3
Hardware: Kindle Fire (1st Gen)

I tried uninstalling/reinstalling, letting the page sit till screen timeout (5 mins), manually closing the browsing session, as well as just hitting the back OS button to take me to the app.

Thanks in advance for your help!

**Comment by dasilva333** [comment] 2015-04-18 14:38
Please report back if you've had success loading the app with the latest version thank you

**Comment by MostDefiantly** [comment] 2015-04-18 17:22
I've tried the 1.9.0 version last night, and the 1.9.5 version this morning. Same behavior.

In 1.9.0 and 1.9.5 now the "Please sign-in to continue" notification never goes away after logging in, but the results are still the same as the browser never auto closes and vault fails to load.

**Comment by dasilva333** [comment] 2015-04-19 12:54
@MostDefiantly do you know how to manually install an apk file? If so we can make you a debug version that'll show us the crash during the load. Let me know thanks

**Comment by MostDefiantly** [comment] 2015-04-19 16:26
Yeah, I can side load. Shouldn't be a problem.

**Comment by dasilva333** [comment] 2015-04-19 22:14
Alright so here's what I need you to do:

1. Install this apk: https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny-release.issue-58.apk
2. Visit this website on your computer: www.jsconsole.com
3. type in this command in that website :listen 979D0DA6-E114-4AA9-BAB0-A7B251C272DB
4. open the app and click ok to the debug popup
5. look at the results on the website and copy and paste any output text or errors here: www.pastebin.com

thanks!

**Comment by MostDefiantly** [comment] 2015-04-20 01:35
I did the walkthrough, but there is no output besides the initial connection established:

http://pastebin.com/qy2vSbKV

The multiples are me re-starting the application three times. I logged into bungie.net using my PSN on the first login, zero output besides the connection confirmations. Tried letting the browser sit, tried hitting the X to close it, as well as the OS back button after the page loaded.

Then restarted the application twice more, went to options > PSN login, and verified it remembers my creds after the initial boot into app prompt. It auto logs into Bungie.net on the last two attempts using the app.

**Comment by dasilva333** [comment] 2015-04-20 12:03
thanks for your help, not sure what to try next considering it's not crashing for you at the javascript level.

**Comment by MostDefiantly** [comment] 2015-04-20 22:22
Hmm... that sucks. I'm not sure either and software development isn't exactly my strong-suite. :)

Is it making calls that rely on something in the android OS which isn't present in the "older" versions that Amazon is using in this hardware perhaps?

**Comment by dasilva333** [comment] 2015-04-27 18:37
@MostDefiantly I submit a new binary to Amazon this weekend of 2.1.4
http://www.amazon.com/gp/product/B00VQYLURG
Please try to install/reinstall that version and post back the results if it worked or not. Thanks!

**Comment by MostDefiantly** [comment] 2015-04-29 02:36
Thanks for the heads up! 

I re-installed the app but the behavior is the same. Banner to log in stays, and browser never closes after loading.

**Comment by dasilva333** [comment] 2015-04-30 22:41
@MostDefiantly please follow issue #115 and try that latest debug build, I know you're experienced with jsconsole already so might as well give it a try and see if anything shows up on this build. Thanks!

**Comment by MostDefiantly** [comment] 2015-05-02 16:22
I have installed the debug and re-ran the listen. Outcome is the same: no crash output, bungie site stays open after loading and the vault doesn't populate. But here are the results for posterity: http://pastebin.com/C7TsJLUW

The 2.2.3 version linked in that thread (2.2.6 after hydration) has no change as well.

As always, thanks a bunch for the assistance.

**Comment by dasilva333** [comment] 2015-05-02 20:24
@MostDefiantly ok so good news and bad news, the good news is that the reason my app doesn't work is not because of my code. the bad news is that there is a bug in InAppBrowser that causes this to happen someone else had this problem here:
http://www.developerblogger.com/100_22621746/

Based on that info I found I'll see if i can develop a fix for you guys. Thanks for your reports

**Comment by dasilva333** [comment] 2015-05-03 13:06
@MostDefiantly try 2.3.0 it has an actual fix for your device, I hope it works let me know

**Comment by MostDefiantly** [comment] 2015-05-03 20:56
@dasilva333 Sorry man, still stalled after browser load. Version reports as 2.3.1.

**Comment by dasilva333** [comment] 2015-05-03 21:05
@MostDefiantly sorry I forgot to mention for you the workflow will be different. Try it the following method:
1. open the app, sign in error should appear
2. click the link for either one
3. allow the redirect to happen and take you to the profile page
4. let it stay there for at least 30 seconds 
5. press close manually on the browser
6. onclose it should trigger the items to load

Sorry I didn't mention that sooner, let me know thanks!

**Comment by MostDefiantly** [comment] 2015-05-03 23:38
@dasilva333 No worries!

I tried that process using the pre-authenticated cookie as well as a fresh re-install to trigger the login but behavior is unfortunately still the same. I left the bungie site open just over a minute or so before closing the browser.

**Comment by dasilva333** [comment] 2015-05-04 01:50
I suppose it might be something I can't fix. At the very least I'll make post in the right forums so they can fix the problem with InAppBrowser. Marking this as help wanted in case anyone wants to help.

**Comment by MostDefiantly** [comment] 2015-05-04 04:52
Thank you so much for the effort so far. I really appreciate you taking time to try to fix this.

**Comment by dasilva333** [comment] 2015-05-05 21:57
Alright so here's what I need you to do:

Install this apk: https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny-release-issue-58.apk?raw=true
Visit this website on your computer: www.jsconsole.com
type in this command in that website :listen 61D5B245-CA98-4E53-9EDF-C4A14AF12B62
open the app and click ok to the debug popup
look at the results on the website and copy and paste any output text or errors here: www.pastebin.com

I changed it to this time to read your cookies regardless of any events every 30 seconds so if you try the last procedure I gave you again to login last time which is:
1. open the app, sign in error should appear
2. click the link for either one
3. allow the redirect to happen and take you to the profile page
4. let it stay there for at least 60 seconds
5. press close manually on the browser
6. after the 60 seconds the items should already be loaded, if not let it stay there for as long as 5 minutes (which equal 10 retries)

thanks!

**Comment by MostDefiantly** [comment] 2015-05-08 05:36
Sorry for the delay. It's still a no go, and here is the pastebin: http://pastebin.com/vtsxgiLT

I let it sit around 90 seconds before forcing the browser to close, and then 6-7 minutes ensuring no screen timeout. The output was literally 844 pages of the repeated "checking for window close undefined"" (in Word) :)

**Comment by dasilva333** [comment] 2015-05-08 16:35
@MostDefiantly I hate for you to keep trying all these failed attempts but whenever you have a chance try out 2.4.0 found in the store, it has some new logic for all devices so it automatically loads your inventory after you sign in once, maybe this change will work for you too. Let me know thanks

**Comment by MostDefiantly** [comment] 2015-05-09 02:14
@dasilva333 Don't worry about me man, if even one other person can benefit from this it's all worth it. :)

With that said, still no dice. On app reopen it still had the (new!) welcome XBL/PSN banner. Forcing a refresh leaves a blue loading bar.

**Comment by dasilva333** [comment] 2015-05-09 15:02
It's okay if it says "Please wait, loading your inventory" for up to 3 minutes don't press refresh. or are you saying it's stuck for you in the other blue loading bar that says "loading user data"? Sorry I didn't clarify there's two loading bars now to help debug this process

**Comment by MostDefiantly** [comment] 2015-05-09 19:15
It's the other "Loading user data..." only after I try and refresh, other wise it sits with just the Welcome banner after after the login.

**Comment by Cintron88** [comment] 2015-05-12 19:53
I have been following this thread for the past week hoping you could come up with something that would help us kindle users join the fun of not being forced to switch characters just to switch weapons or even a heavy ammo synthesis.....Thank you for all the time and effort your putting into this and just know that the issue is still just being able to log into the app. Instead of signing into the app it just signs into the bunge.net website and not your app. I wish I knew how to fix this myself but sadly I'm not that computer savy. Just know that all us Destiny players that still have the first gen kindle are still looking to you for help. Thank you again and if I could do something for you just leave a message here. I check back here daily just to see if there's any new break through.

**Comment by dasilva333** [comment] 2015-05-12 20:02
@Cintron88 thanks for following my app there is indeed a lot of Kindle users who can't use my app because of the limitations of some of the underlying tech.

The problem stems from here:
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/www/js/app.js#L755

That line never executes which makes it impossible for you guys to use the app. The community can help by posting a support thread in the proper channels alerting the developers of InAppBrowser to know that their stuff isn't working on the Kindle.

You can find community forums here:

https://groups.google.com/forum/#!forum/phonegap
http://community.phonegap.com/nitobi
https://issues.apache.org/jira/issues/?jql=project+%3D+CB
https://issues.apache.org/jira/browse/CB-247?jql=text%20~%20%22kindle%22

**Comment by dasilva333** [comment] 2015-05-12 20:12
@Cintron88 and @MostDefiantly 
I just thought of something else to officially call this an issue I can't fix and really make sure the problem is L755 so here's what I need you to do:

Install this apk: https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny-release-issue-58.apk?raw=true

(it's an older version but that should be fine)

Visit this website on your computer: www.jsconsole.com

type in this command in that website :listen 61D5B245-CA98-4E53-9EDF-C4A14AF12B62

1. open the app and click ok to the debug popup
2. sign in error should appear log in to live/psn
3. you should see the redirect happen and the popup stays stuck in Bungie.net
4. revisit jsconsole.com and type this in the command line:
> ref.executeScript({code: 'document.cookie'}, function(result) { console.log(result) });

At this point you should see a result that looks like this:

"bungledatk=1235654654; bungled= 12334565465; otherstuff=134546456546"

If you see this then there is hope for the Kindle yet, if you don't see it then proceed with my previous post on filing an bug report to the Apache Cordova team.

One more note, if you do see that result come up you can make the app work manually by running the next two lines:

> app.bungie_cookie = "<results from last line>"
> app.loadingUser(false)
> app.loadData();

At this point you should be able to close the popup and see your stuff. Good luck guys

**Comment by dasilva333** [comment] 2015-05-18 18:01
@MostDefiantly @Cintron88 any luck with the latest set of instructions?

**Comment by MostDefiantly** [comment] 2015-05-18 21:46
@dasilva333 Really sorry, I have been out of town all week. I will check it out once I get back mid Wednesday or so.

**Comment by dasilva333** [comment] 2015-05-18 22:38
@MostDefiantly no problem just have to follow up and make sure thanks

**Comment by MostDefiantly** [comment] 2015-05-23 19:21
Alrighty, sorry for the delay @dasilva333. So good-ish news is that when I ran your ref.executeScript line I did get a return with a series of GUID's.

I tried putting it in the jsconsole window as directed, but I was unable to get the vault to manually load using the app.bungie_cookie definition and followup lines - but I am very much down to that being user error. :)

It appears to have taken the variable as directed, but I used the entire set of information from the cookie, and wasn't clear if it's something I should have trimmed down first.

**Comment by dasilva333** [comment] 2015-05-23 21:16
if you like and have time set up the jsconsole again and send me a message here ill try to respond asap and try those same steps myself to see the results. thanks and let me know

**Comment by MostDefiantly** [comment] 2015-06-27 19:56
Hey @dasilva333! I'm down for a conference call or IM session or whatever if you want to hammer this out once and for all. Just give me a heads up and I can hop online. 

I still have my cookie information and whatnot from the jconsole output saved too if that helps. Thanks again.

**Comment by dasilva333** [comment] 2015-06-27 20:50
Join us at Slack so we can chat the details are here:
https://github.com/dasilva333/TowerGhostForDestiny/wiki/Slack-Group-Chat

I also have jsconsole up and running so when you connect I should be able to just start hacking away, Thanks!

**Comment by MostDefiantly** [comment] 2015-06-27 20:57
Great, I shot an email to @bluetidepro for an invite. Talk to ya soon.

**Comment by dasilva333** [comment] 2015-06-27 21:03
In the mean time you can also fire up the jsconsole session so I can debug it thanks

**Comment by MostDefiantly** [comment] 2015-06-27 21:06
Used the APK from your earlier walkthrough, and logging in now.

**Comment by dasilva333** [comment] 2015-06-27 21:28
He might not be available on weekends, you can also send me your email to support@towerghostfordestiny.com and I can invite you for now. Thanks

**Comment by MostDefiantly** [comment] 2015-06-27 21:34
Sent

**Comment by MostDefiantly** [comment] 2015-07-18 21:40
Just wanted to follow up that I haven't had the loading issue since we did the debugging sessions and rolled out the fix. Thanks again!

**Comment by dasilva333** [comment] 2015-07-20 13:12
No problem thanks for reminding me to close this out

**Closed by dasilva333** 2015-07-20 13:12 UTC
Labels: bug, help wanted
