### ISSUE TITLE
3.0.9 Chrome Extension won't load and becomes disabled

### ISSUE THREAD

**Issue by SeethingSage** [dasilva333/TowerGhostForDestiny#349] opened 2015-09-04 00:35 UTC
I'm using Chrome 45.0.2454.85 on an old XP laptop.  Prior versions of TGD worked fine, but when 3.0.9 tries to load/launch, it just stops, and then it becomes disabled in/by the browser.  If I re-enable it and try to launch it again, the same thing happens.  I uninstalled the extension, closed the browser, rebooted the PC, and then reinstalled the extension.  The same thing happens.  I found a .crx download for 3.0.6 and installed that again, and it works fine.  If it was a little more convenient, I would edit the browser's prefs manually and stop just this one extension from updating, but hopefully 3.0.6 will continue to work for me tonight w/o the browser updating it.  FYI, I noticed another user having issues with 3.0.9 that posted a comment on the Chrome store page for TGD.

**Comment by whtz** [comment] 2015-09-04 00:53
Same here - not sure of the versions, but I get a splash screen about the fixes in this update, then nothing.

**Comment by iamrockr** [comment] 2015-09-04 02:05
Same here. It worked fine until today's update.

**Comment by rkingsla** [comment] 2015-09-04 10:53
Fixed - much appreciated!

**Comment by dasilva333** [comment] 2015-09-04 17:59
FIxed as of 3.1.0 the cause is still unknown as to why it happened we're just on 3.0.8 until I can figure it out. Thanks for the feedback please let me know asap if you see this happen again

**Closed by dasilva333** 2015-09-04 17:59 UTC
