### ISSUE TITLE
Uncaught Type Errror while attempting to move weapon

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#125] opened 2015-05-02 06:55 UTC
This is a curious one, especially since it is hard to reproduce. In my case I'm unable to move the equipped heavy from my warlock to any other character or vault. There are two heavy weapons on my warlock, and I'm trying to move the one that is equipped to a different character. It fails.

If I add a 3rd weapon, it all seems to work fine. I can also move the non-equipped weapon without any issues. I've swapped around weapons too in order to make sure it wasn't weapon specific.

Here is the error I'm getting whenever I attempt to move my warlock's equipped heavy:
Uncaught TypeError: Cannot read property 'equip' of undefined
tryNextItem @ app.js:199
tryNextItem @ app.js:206
Item.unequip @ app.js:212
done @ app.js:367
Item.store @ app.js:422
(anonymous function) @ VM570:3
(anonymous function) @ knockout.js:83
m.event.dispatch @ jquery.js:3
r.handle @ jquery.js:3

**Comment by Titus-s** [comment] 2015-05-02 08:28
@weborican - As you said, you can't move equipped heavy to other character or vault.
I've reproduce it - it's probably the same case:
1. In heavy weapon bucket is two items - legendary (equipped) and exotic (stored)
2. in one of other bucket (primary or special) on source character is equipped exotic item. 
Right now it try to equip exotic heavy weapon - which is impossible due you have equipped exotic in primary or special. 
I get similar error:
![image](https://cloud.githubusercontent.com/assets/11790750/7440454/699052ae-f0b5-11e4-8d12-128fcb262ab1.png)

**Comment by Titus-s** [comment] 2015-05-02 12:25
It turn out, that point 2 is not required.

**Comment by rkingsla** [comment] 2015-05-02 12:44
True, all of this.  This should likely be closed as duplicate of Issue #91. the behavior and the root cause are likely one and the same.

As an interesting and possibly contributing cause, if you move an item in-game AND TGD has not been refreshed (For example, you've equipped a new weapon and moved a weapon from character to vault), TGD is now in a non-synced state. TGD *thinks* that the weapon you just put into the vault is till in the bucket and equipped.

Suggest that before any loadout or single item actions, force a refresh to sync in-game and TGD current state. This will, at least, allow for proper return of a prompt for notifying TGD user that the weapon is no longer on the user, or the action can be executed against the vault instead.

**Comment by dasilva333** [comment] 2015-05-02 13:23
Thanks guys good stuff, I re-read the simplified version of the test case @Titus-s provided me in issue #91 and it seems that's a scenario where I would provide an error state message where the system wouldn't be able to move the item.

@rkingsla i think your idea of refreshing prior to starting a loadout transfer is a great and simple idea I can implement to solve a lot of issues but there's still a few actual issues.

@Titus-s you provided another test case here that involves having two weapons in this scenario the system should be able to move the exotic as equipped and move the legendary out, I actually already wrote code to handle that contigency in the system so I'll try to reproduce it and make sure it's working right. 

I'll leave this ticket open because I want to test against the two cases provided separately. Thanks again

**Comment by dasilva333** [comment] 2015-05-02 21:34
Try 2.2.7 and let me know how it works thanks guys

**Comment by rkingsla** [comment] 2015-05-02 23:11
Excellent!  I think that #91 issue is gone.  However, the small nit of how to prompt a user on what to do is still present.  Your notice that you cannot do this on an equipped item is spot on. It makes 100% perfect sense.
However, let's consider the case where a weapon loadout is moving 6 weapons - like I do for Crota. If, for example, Swordbreaker cannot be moved because it's the ONLY Special weapon or the only other option is an Exotic with the primary or heavy already filled with an exotic - We're told you can't do that.  OK, that's fine.
The current gotcha is that if you don't know or aren't aware of WHY, you might just dismiss the 'you can't do that' prompt and then hit Transfer again. At this point, it seems that the logic is outside of the ability to actually catch the error.
IMHO, if this error occurs during a loadout cycle, Transfer should be disabled so that the only option is to Cancel.
What would be spectacular is to pop up a window telling the user, Hey - this is why it failed. You can't have both Ice Breaker and Gjallarhorn equipped on the same character at the same time.
Otherwise, EXCELLENT progress guys!  Very, very nice!
Oh, and thanks for putting up with Grammar Boy...  Much appreciated!  ;o)
![tgd-2 2 7-transfer-125-5 2 2015](https://cloud.githubusercontent.com/assets/2037051/7443064/701f3f54-f0f6-11e4-9b18-96a6f2c908e6.png)
![tgd-2 2 7-transfer--log-125-5 2 2015](https://cloud.githubusercontent.com/assets/2037051/7443066/7bace970-f0f6-11e4-83eb-8fc2fc89f909.png)

**Comment by weborican** [comment] 2015-05-03 00:28
Fixed at my end. Thanks!

**Comment by dasilva333** [comment] 2015-05-03 00:35
Yeah 2.2.8 has a fix for the last problem reported by @rkingsla try it out and confirm it's fixed thanks @weborican

**Comment by rkingsla** [comment] 2015-05-03 18:45
Functionality continues to improve.  Good job, really. A scenario that is still a part of this, yet not specifically addressed is what if there is only one item in a bucket on a character? If you click it, you get the options - currently not possible - to either equip or move to another character or to the vault. Obviously, if you continue and try the obviously bad scenario, you get the response "You cannot perform this action on an equipped item".
Instead, of the 'certain failure' scenario, are there options that can be presented, or should there simply be a prompt like the above Informational "You cannot perform this action on an equipped item" that would state "You cannot perform this action on the last item on this character in this item class".
At worst, this is going to notify the user what the issue is.
Just a thought.

**Comment by dasilva333** [comment] 2015-05-03 18:58
I think "You cannot perform this action on an equipped item is sufficient to indicate to the user they can't perform that action, having a more specific error message indicating they can' t because it's the last item is a bit redundant and not really necessary imo, as long as they know it's an error it's fine.

I'm marking this ticket closed as I think I've addressed all the actual crashes in the app, feel free to open a new ticket if you feel there's any bugs left unfixed. Thanks again guys and thanks for your feedback.

**Closed by dasilva333** 2015-05-03 18:58 UTC
Labels: bug

**Comment by weborican** [comment] 2015-05-04 18:51
Oh, to open a new t
![equip_bug](https://cloud.githubusercontent.com/assets/12019978/7459857/9f8bf8c6-f264-11e4-901b-10ba8d2a4194.gif)
icket or not... that is the question. I'll post it here since it is very much related to it, but I can always open a new one if necessary.

I was testing some scenarios I remember being problematic, and found one case that should work but isn't. Hard to describe, so attached is a gif of the process.

**Comment by dasilva333** [comment] 2015-05-04 18:53
@weborican good catch let's make this one a new ticket so it's easier to keep track of it and thanks for the bug report I agree that action should be working

**Comment by weborican** [comment] 2015-05-04 19:11
I will create a new ticket in a minute.

I just tested this scenario under the Special bucket, same result using version 2.3.2 on Chrome and Android, and version 2.3.3 on iOS.
