### ISSUE TITLE
Crash on iPhone 6 Plus...

### ISSUE THREAD

**Issue by psychotron83** [dasilva333/TowerGhostForDestiny#3] opened 2015-04-08 16:56 UTC
The app downloads and installs fine through appcake.  It crashes after entering my login/password for the bungie site while the bungie site is loading.  App goes black and crashes to springboard.  

Running iPhone 6 Plus
IOS 8.1- Jailbroken

**Comment by dasilva333** [comment] 2015-04-08 23:13
Alright good stuff thanks for the report I will be making a debug version for you to try to use and login along with instructions on what to do thanks.

**Comment by dasilva333** [comment] 2015-04-08 23:35
Alright it's ready heres what you do:

1. visit jsconsole.com and type this in the console:
:listen ?B5BB6177-DD75-460D-93C9-6F56A2E92EAC
that should enable a debug session between your browser and phone that'll output information that you will then share with me
2. open the app on  your phone, it should say connected and start spitting out information as you use it
3. copy that information and paste it here: www.pastebin.com
4. provide it to me and i'll try to figure out the solution
thanks

**Comment by psychotron83** [comment] 2015-04-09 02:21
I wasn't sure what to do with the pastebin stuff so I just copied the data here.  Let me know if you need anything else.  Can't wait until this works, for now i just remote to my desktop PC and use the chrome version but having an app would be incredible.

remote console.loglink
10
remote console.loglink
10
remote console.loglink
6
remote console.loglink
5
remote console.loglink
10
file:///var/mobile/Containers/Data/Application/6AC003D1-C92D-4E38-B25C-A80F5EF41F3B/Library/AppLoaderApps/787B13CA-0600-4583-A339-E2B38A04D2C0/cordova.js:1109link
TypeError: null is not an object (evaluating 'event.type')
remote console.loglink
10
remote console.loglink
"Error in Success callbackId: InAppBrowser1829555390 : TypeError: null is not an object (evaluating 'event.type')"
remote console.loglink
4
remote console.loglink
"adding homepage.js"
remote console.loglink
3
remote console.loglink
1
remote console.loglink
"code 99"
remote console.loglink
2
:listen B5BB6177-DD75-460D-93C9-6F56A2E92EAClink
Creating connection...
Connected to "B5BB6177-DD75-460D-93C9-6F56A2E92EAC"

<script src="http://jsconsole.com/remote.js?B5BB6177-DD75-460D-93C9-6F56A2E92EAC"></script>

**Comment by dasilva333** [comment] 2015-04-09 12:06
There is a new debug build available for you, please try downloading and installing the new version. Do NOT automatically upgrade to the latest version using the auto updater, instead download the newest file and reinstall it from scratch. Thanks

https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist

**Comment by psychotron83** [comment] 2015-04-09 12:45
Here is the debug info from the latest build.  

remote console.log
link
10
remote console.log
link
10
remote console.log
link
6
remote console.log
link
5
remote console.log
link
10
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
7
remote console.log
link
8
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
7
remote console.log
link
8
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
8
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
7
remote console.log
link
8
remote console.log
link
"found result in loadstop CkTst=G1428583397392; wlidperf=throughput=6&latency=493"
remote console.log
link
8
remote console.log
link
7
remote console.log
link
6
remote console.log
link
5
remote console.log
link
10
remote console.log
link
10
remote console.log
link
4
remote console.log
link
"adding homepage.js"
remote console.log
link
3
remote console.log
link
"code 99"
remote console.log
link
2
remote console.log
link
1
:listen B5BB6177-DD75-460D-93C9-6F56A2E92EAC
link
Creating connection...
Connected to "B5BB6177-DD75-460D-93C9-6F56A2E92EAC"

<script src="http://jsconsole.com/remote.js?B5BB6177-DD75-460D-93C9-6F56A2E92EAC"></script>

**Comment by dn4cer** [comment] 2015-04-09 14:31
I'm not sure what to do...

I followed the instructions and see no output in the console.

Couple of questions:
1. What version of the app do I use? Keep in mind, I'm using an Android APK. Is there a debug version? All I see is release. If I use the release version, do I update it?
2. The browser, is it from my PC or from my phone?

**Comment by psychotron83** [comment] 2015-04-09 14:38
Hi dn4cer, 

I know that the browser you use for jsconsole.com should be on a PC.  Otherwise once you close the browser and switch to the app the connection the browser made to the phone will be lost.  Not sure about a debug APK file though.

**Comment by dasilva333** [comment] 2015-04-09 17:24
@dn4cer  I will make a debug build of the apk and the android thanks
@psychotron83 so the latest build you tried outputs that debug and it still crashes during the login for you?

**Comment by psychotron83** [comment] 2015-04-09 18:48
@dasilva333 yeah still get the crash.  I just tried it again with a fresh install from iFunBox and got the same log and same crash. The debugger seems to spit out some data as i'm clicked through the login information but once I hit sign-in and it's trying to load the bungie website it crashes and there is not more data shown in the debugger.

**Comment by OUTFOXEM** [comment] 2015-04-10 07:48
I tried the latest debug version, here is a copy of the syslog after a fresh boot:

http://fnpaste.com/WJEn

Jsconsole.com reports pretty much the same thing as psychotron83's latest comment, but with different latency.  CrashReporter also is saying low memory again when I try authenticating on Bungie.net.

**Comment by dasilva333** [comment] 2015-04-10 12:16
It seems you are still getting out of memory issues, not sure why iPhone 6 would have memory issues and not iPhone 5 and not sure what I can do to to fix it yet. Stay tuned for more updates I'll figure it out

**Comment by OUTFOXEM** [comment] 2015-04-10 14:10
I'm not sure either.  I loaded it just fine on my jailbroken iPhone 5, which has the same amount of memory as the iPhone 6 Plus.  The only big difference there is the resolution, so maybe that plays a role somehow, I don't know.

**Comment by azleb** [comment] 2015-04-16 01:41
Hi 

I am part of the test flight version with iPhone 6 +. I am also getting the issue logging in and crashing on PSN.

**Comment by dasilva333** [comment] 2015-04-16 11:32
Sorry guys it seems it's a common problem on some devices where it crashes due to out of memory errors, I'm not sure how I can help or even debug the issue without having an affected device so I'm tagging this post as 'help wanted' in hopes we can get a developer in here to help us debug this thing.

Thanks

**Comment by dasilva333** [comment] 2015-04-16 19:36
@azleb @OUTFOXEM @psychotron83 Hey guys still no actual fix for crashing out of memory issues however while fixing the 4th horseman bug I managed to reduce the itemDefs from 2.25 to 1.5 mbs. Maybe this reduction in memory usage will help with the crash. Anyhow try version 1.8.8 if you're jailbroken and report back if you have success or not.

Thanks

Download Link for 1.8.8:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestinyAppStore.ipa

**Comment by psychotron83** [comment] 2015-04-16 20:07
@azleb @OUTFOXEM @dasilva333 just tried it and it still crashes:(

**Comment by azleb** [comment] 2015-04-16 23:41
Sorry, dont have Jailbroken device.

**Comment by koko949** [comment] 2015-04-17 18:40
im no expert, but could this be a 64bit issue? aside from the screen size the only difference in iphone 5 and iphone 6 is 64bit. does tower ghost work on iphone 5s? (which is also 64bit)

**Comment by ssoriche** [comment] 2015-04-17 18:41
Works no problem on my iPhone 6.

**Comment by koko949** [comment] 2015-04-17 18:41
ok nevermind.

**Comment by OUTFOXEM** [comment] 2015-04-17 23:00
Same deal with 1.8.8.

http://pastebin.com/g5UBrNKZ

**Comment by OUTFOXEM** [comment] 2015-04-18 12:57
Ok so, good news and bad news.  I don't know how helpful this will be to you in getting the problem solved, but I did actually manage to use the app on my iPhone 6 Plus last night.

First thing I did was load v1.9.0, and that still crashes.  Then it told me there was an update, and I let it update to v1.9.3.  That also still crashes.  This time though after logging in, I prematurely clicked Done.  It still said I wasn't logged in, but now when I clicked login, it loaded the browser and the bungie.net site was actually fully loaded, and then it crashed.  So I tried the same steps, but once I saw bungie.net was fully loaded, I clicked Done again.  The app still said I was not logged in, but after clicking login again and then quickly hitting Done after a second or two, it loaded my inventory.

So, it seems that if I leave the browser window open too long, it will crash.  Clicking Done will close it, but it apparently either a) continues to load in the background, or b) clears enough memory to make more progress.

The bad news is no matter how hard i tried, I was not able to replicate this feat.  I tried the exact same steps, but I could never get my inventory to load again -- it always crashes.

Anyway, I hope that's helpful in some way.  Thanks for all your hard work!

**Comment by dasilva333** [comment] 2015-04-18 14:35
try 1.9.5 that last bug report was helpful in thinking what I can change to get it to load for you. I'm glad you got to see your inventory once that means there's still hope for your phone yet.

**Comment by dasilva333** [comment] 2015-04-18 22:40
@OUTFOXEM @koko949 @azleb @psychotron83 @dn4cer and anyone else whose phone is crashing during the login phase please try any version over 1.9.5 I think the issue might be solved now thanks to OUTFOXEM's feedback. Try it out and report back thanks

**Comment by psychotron83** [comment] 2015-04-19 03:48
@OUTFOXEM @koko949 @azleb @dasilva333  @dn4cer I tried it with 1.9.7with and without hydration and it still crashed. Even tried playing with the done button before loading and clicking sign-in again but wasn't able to ever see my inventory.

**Comment by azleb** [comment] 2015-04-19 04:48
Can I access 1.9.7 though test flight?

**Comment by rccola85** [comment] 2015-04-19 05:24
Like psycho, I've also tried 1.9.7 using the two different ipa's with & without hydration, and still can't get past the login. Also tried tapping "Done" at various parts of the loading screen to see if it would catch, but no dice.

**Comment by dasilva333** [comment] 2015-04-19 12:44
@azleb not yet expect to see 2+ by Monday and sorry guys that's all I had for now I'll keep thinking of ways to make it better

**Comment by gojirra** [comment] 2015-04-19 18:36
Hello, I'm reporting the same issue as above with my iPhone 6 Plus, it crashes to the home screen when I attempt to login. I am doing this the app downloaded through Testflight for a non-jailbroken device. 

I will keep track of this thread as I see this is a known and common problem. Just reporting it and will pass on info as needed.

**Comment by traximilian** [comment] 2015-04-19 21:55
I have gotten the app to load now running 1.8.0 on an iPhone 6 Plus with iOS 8.3. I have a screenshot that I am attaching to this comment as proof. It seems that the app is crashing due to an overallocation of memory during the login frame. As the Bungie.net API is a 3rd party API for credentials (meaning it does not store the username/password as Bungie.net relies on Windows Live to be the 1st party API for the authentication of the Microsoft user ID/password) there is an issue with the way the app is trying to authenticate the login information first through Windows Live and then through Bungie.Net. I think that the process needs to be spilt into two as it is overloading the virtual memory allocated for the process in the login frame in the app. I am not a coder so I could be completely wrong and won't pretend to know what I am talking about but I feel like the issue is contained somewhere in the Windows Live API and Bungie.net API for authenticating the user's credentials. 
![screen shot 2015-04-19 at 2 44 17 pm](https://cloud.githubusercontent.com/assets/8412261/7221565/05e3fadc-e6a4-11e4-8fbf-c6294b98ae80.png)

**Comment by rccola85** [comment] 2015-04-19 22:02
So how did you get it to load, so I can also give it a try?

**Comment by dasilva333** [comment] 2015-04-19 22:07
Hey guys with nothing left to try I updated it to 1.9.9 with a possible fix for the crashing. Try it out and let me know thanks

**Comment by rccola85** [comment] 2015-04-19 22:11
1.9.9 (Hydrated version) on my 6 Plus, crashes still after log in. I'll try the regular version later.

**Comment by traximilian** [comment] 2015-04-19 22:17
Hey man before I dive into how I can get it to load just to let you know I can plug my phone into my laptop and run Xcode and get a device log while running the app or try to debug if that helps in anyway for you, just let me know. I want to help as much as I can as you do so much great work for this community! Also if the below doesn’t make sense I am happy to hop on a phone call and walk you through what I did, just let me know and I can give you my cell number.

I noticed the post yesterday on github from OUTFOXEM that said he managed to get the app to load by prematurely clicking done. From watching the progress on the development of PackMule (another destiny app) as well as yours I know that Bungie.net <http://bungie.net/> is actually just a third party API relying on Windows Live (the actual 1st party API in this case) to authenticate the credentials for the user. I also have been messing around with the app and noticed that there are two separate API calls/logins taking place. First when the user clicks on Windows Live the user will be given the Windows Live login in page. If the user clicks remember me and types in the username and password and clicks login the login page will be replaced with a white page with a sentence at the top that says ‘redirecting, if this page doesn’t close in a few seconds please click here’. If the user clicks to make the page will disappear then they will be back at the grey screen of the app telling the user to login through Windows Live. If the user doesn’t click to close the page and just lets the redirect happen then the user will be redirected to Bungie.net <http://bungie.net/> and will see the Bungie.net <http://bungie.net/> page start to load (and the user will be logged into Bungie.net <http://bungie.net/> because of the windows live credentials they already entered). However (and so far this has been inconsistent) when the Bungie.net <http://bungie.net/> page loads the app will quit/crash, sometimes halfway through loading the Bungie.net <http://bungie.net/> page and sometimes quits/crashes after Bungie.net <http://bungie.net/> fully loads. 

With that information in mind I decided to start to play around with the login loading/crash times to see if I could get the app to login me in through a combination of letting the app crash and hitting the ‘done button’ at the button left of the screen prematurely. I opened the app up and hit login with Windows Live, I also checked the remember me box. I then hit login with my credentials and let the app load till I saw the bungie page start to load and then waited one to two seconds after seeing the bungie.net <http://bungie.net/> page start to load and would hit done and the app would quit/crash. I did this three times in a row and then on the fourth time when the bungie.net <http://bungie.net/> page had started to load the outline of the page (but not the content) I hit done it the bungie.net <http://bungie.net/> page went away and was replaced by the screenshot I uploaded earlier of my vault with my weapons. 

Sometimes you will notice a blue loading bar underneath the red error message at the top of the app saying you need to log in. If you have this it means you are close to logging in but not close enough. Try to quit the app and reopen it and do the login hit done process again until you can get it to load.

Does that make sense? Don’t hesitate to let me know if you have questions or if you want me to try to clarify something…

Thanks,

Max

**Comment by traximilian** [comment] 2015-04-19 22:19
Is 1.9.9 uploaded to TestFlight or only github for jailbroken iPhones?

Thanks!

**Comment by dasilva333** [comment] 2015-04-19 22:56
@traximilian there's no 1.9.9 is only for broken phones however if you provide me your UDID (this applies to anyone, then you get access to the latest version always available) read my post here for more info: http://www.reddit.com/r/DestinyTheGame/comments/32vqua/discussion_tower_ghost_for_destiny_available_for/

@rccola85 that sucks man

**Comment by traximilian** [comment] 2015-04-19 23:09
OK cool, I can give you the UDID right now but I am not sure if I should share it here or message you privately somewhere else? If I do need to share it privately please let me know where and how to email/contact/message it to you?

**Comment by traximilian** [comment] 2015-04-19 23:18
I PM’ed you the UDID on Reddit. Let me know if you need me to send it here as well. Thanks!

**Comment by OUTFOXEM** [comment] 2015-04-19 23:51
It looks like Trax used the same method to login that I did.  I was only successful once, but the method that he described (in much more detail than I did) is the same as the one I used that one successful time.

Unfortunately as I said, I was never able to actually replicate that, and obviously once you close the app, it logs you out and you must start all over.  I will give 1.9.9 a try though.  Just assume that it crashes unless I say otherwise.

**Comment by traximilian** [comment] 2015-04-20 07:24
As of right now I'm not able to replicate my login with 2.0 (hydrated). I'm going to keep trying tonight and will post an update tomorrow.

**Comment by lambs0n** [comment] 2015-04-20 14:57
Hey man - I just sent you a PM on reddit of a guy's name who might be able to assist with the authentication piece.. He has an Item Manager app working correctly through TestFlight, and it's working without any issues on my iPhone 6+ (non-jailbroken).. maybe he can give you some insight or help with the bungie authentication issue that you're experiencing..

**Comment by dasilva333** [comment] 2015-04-20 16:09
Thanks for the info guys, unfortunately if it's still not working as of 2.0.0 then I'm out of ideas. I have friends and other people who have supported success on their iPhone 6/6+ so if it's not working on your devices it really is an isolated issue.  Perhaps in the future I'll come up with another idea of something I can change. Thanks again guys

**Comment by batmanofgotham** [comment] 2015-04-20 17:18
I'm also having this problem. Like a couple of others I had a singular success before the weekend when trying to press the 'done' button when the bungie page is loading. Like I said, got it to work once and once only.

Seems more than isolated based on the same reports from individuals. Hope you have some success with with what @lambs0n suggested - I believe the app he is testing is called loadouts and I'm currently using it on FlightTest too where the authentication works fine.

**Comment by rccola85** [comment] 2015-04-20 17:20
I'm in the same boat as batman. Also testing that other app and it loads perfectly, but I'd rather use this app as I already use it on Chrome and my Nexus 7.

**Comment by lambs0n** [comment] 2015-04-20 18:00
@batmanofgotham yeah, it was Loadouts for Destiny =) I sent @dasilva333 a PM on reddit with the creator's reddit username.. hopefully they'll be able to sync up and go from there

**Comment by traximilian** [comment] 2015-04-20 18:28
Yeah I'm also testing Loadouts via TestFlight. The app's creator is actually on Twitter as well and he and I go back and forth there as I provide feedback on his app.

@dasilva333 I think I found the issue. We don't need to call both Windows and Bungie's API as I believe it throws the login window into some kind of redirect loop that crashes the app (based on the architecture of the API's and Windows Live is the 1st party and Bungie.net the 3rd party as we have been discussing). I asked the creator of Loadouts on Twitter how he is calling the login in the app (see screenshots of my Twitter conversation below). I think we just need to call bungie.net API and not windows live and have the users log in with bungie.net. So instead of having the users login with Windows Live have them login with Bungie.net. Does that make sense? 



Let me know what you think and if that helps and or changes anything! 

Thanks,

Max

**Comment by traximilian** [comment] 2015-04-20 18:45
@dasilva333 Also the creator of the Loadouts app is in the beta for TowerGhost currently but wants to be added to the adhoc beta with his UDID if possible so he can help troubleshoot. Let me know and I can give it to you privately.

**Comment by lambs0n** [comment] 2015-04-20 18:46
thanks for your help with this @traximilian!

**Comment by dasilva333** [comment] 2015-04-20 18:49
@traximilian I sent him a PM asking him for help, no reply yet. I even offered him an invite to the flight test/adhoc test. He's free to reply with his details so I can add him unless he only wants to speak through you at which point I suppose it's fine if you send it to me, also make sure to include email address with the UDID. Thanks

**Comment by OUTFOXEM** [comment] 2015-04-20 18:54
@dasilva333  I'm glad that the developer of Loadouts has been mentioned.  I was going to mention him myself.  I tested an early version of his app, and guess what?  It also crashed on only the iPhone 6 Plus!  So whatever he has done to fix the crashes could help you in solving the crashes for your app too.  I would definitely recommend at least talking to him about it.

With that said, it's not an isolated issue.  There are lots of people here having issues with the iPhone 6 Plus.  I see you lumped the 6 and 6+ together, but they are not the same.  I am not calling you a liar, but I find it hard to believe there is even one person out there using your app on the iPhone 6 Plus right now -- perhaps the iPhone 6, but not the 6 Plus.  Please do not mistake one for the other, as they are not the same.

**Comment by lambs0n** [comment] 2015-04-20 18:55
@dasilva333 it looks like he's willing to help! He's on the Flight Test group already, twitter is: https://twitter.com/slavikus/ and he mentions his gmail in his twitter feed (a few tweets ago)

**Comment by traximilian** [comment] 2015-04-20 19:01
@dasilva333 I don't think he wasn't responding on purpose it probably got caught up in the noise of all the PM's I'm sure you both get. He only responded to me I think because I reached out on Twitter and have a good relationship with him there because of the feedback I provide. What's your best email? I'm going to intro you to him and connect you two directly so he can give you his UDID and hopefully help troubleshoot as well.

**Comment by dasilva333** [comment] 2015-04-20 19:29
@traximilian my email is richard.pinedo@yahoo.com if you want to use that let me know thanks

**Comment by traximilian** [comment] 2015-04-20 19:31
@dasilvia333 OK perfect I am emailing you now with Slav's info and introducing you. Thanks man!

**Comment by dasilva333** [comment] 2015-04-20 21:08
Hey guys so I got a co worker to help me test my app with his 6+ and despite various attempts I couldn't get it to load, I managed to strip down all the code so it's at the most basic barebones so memory is not an issue. I'm not sure what to try next perhaps I'll try having it redirect to a less memory intensive page after login rather than the homepage see if that helps.

Here's the binary if you want to try it:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny_issue3.ipa

Only applies to jailbreakers/UDID provided to test it open the app, visit the menu, click the gear, click PSN/Live Login, enter your info and hope it doesn't crash while loading the home page. Let me know guys thanks!

**Comment by psychotron83** [comment] 2015-04-20 22:10
@dasilva333 just tried the latest stripped down version and unfortunately still crashes.

**Comment by dasilva333** [comment] 2015-04-20 22:27
@psychotron83 @ traximilian Alright guys and anywho has access to the ipa I want you to test it one more time, the version should display 2.0.6 and after logging in you should see your bungie profile instead of the homepage.

**Comment by traximilian** [comment] 2015-04-20 23:00
@dasilva333 OK sounds good I will be able to test in 45 minutes to an hour as I'm heading back from a meeting right now (I work from home usually during the day). Will report back once I can test 2.0.6. Thanks!

**Comment by psychotron83** [comment] 2015-04-20 23:21
@dasilva333 @traximilian well good news is the app doesn't crash!! But it also doesn't load any of my destiny inventory.

**Comment by dasilva333** [comment] 2015-04-20 23:30
alright try 2.0.2 that's ready now in the normal distribution

**Comment by traximilian** [comment] 2015-04-20 23:46
@dasilva333 I just tried 2.0.3 and it's still crashing. 

Is there a way to force the login view/window to close after the page starts the redirect to bungie? I feel like the app trying to load the bungie.net webpage in the login view could be killing the memory allocated for the app causing it to crash. Just another random thought to throw out there.
 
I'll keep messing around with it and see if I can get it to load.

**Comment by dasilva333** [comment] 2015-04-20 23:49
@traximilian no it needs to load completely and fully for some reason the page is doing something during the page load the 'enables' the cookie that I already have so it's just retrying until it works. This is a step in the right direction perhaps I can find another page that's not the homepage that'll still load the cookie.

**Comment by traximilian** [comment] 2015-04-20 23:56
@dasilva333 OK that makes total sense thanks for the clarification. Slav says he waits for the login view to hit bungie.net root and load and then he takes the cookie. Is this different from how the cookie is being taken now? Maybe he can shed light on how he is grabbing the cookie from bungie.net.

Thanks for listening to all my crazy ideas and hopefully we are making progress in the right direction!

**Comment by dasilva333** [comment] 2015-04-21 00:12
The difference is he wrote it in native objective c and I'm using an InAppBrowser tech from Apache Cordova that seems to be buggy, not sure of a good fix yet I'm trying to work around the issue since there's not much I can do at the low level side.

**Comment by azleb** [comment] 2015-04-21 00:39
Just got the update. Working perfectly now, great work guys!

**Comment by traximilian** [comment] 2015-04-21 00:41
@azleb are you on iPhone 6 plus?

**Comment by azleb** [comment] 2015-04-21 00:41
Yes I am

**Comment by koko949** [comment] 2015-04-21 00:44
it works! im running 2.0.2 and its working on my iphone 6 plus. AWESOME! thanks dasilva333! ill be making a donation for all your hard work!

**Comment by azleb** [comment] 2015-04-21 00:45
![img_0041](https://cloud.githubusercontent.com/assets/11970599/7243685/5505798a-e80f-11e4-9398-d7e69fa25910.jpg)

**Comment by traximilian** [comment] 2015-04-21 00:48
Awesome! 

@dasilva333 I can confirm 2.0.4 is running as well!

**Comment by rccola85** [comment] 2015-04-21 01:03
Also working on my 6 Plus! Using the hydrated app at 2.0.4

**Comment by gojirra** [comment] 2015-04-21 01:08
Running 2.02 on 6+ non jail broken and is loading as well. Thank you. I will test it soon.

**Comment by dasilva333** [comment] 2015-04-21 01:13
Glad it's working for everyone @koko949 here's the link for ya: http://bit.ly/1Jmb4wQ

Closing this ticket and putting this issue to rest

**Closed by dasilva333** 2015-04-21 01:13 UTC
Labels: help wanted

**Comment by koko949** [comment] 2015-04-21 01:30
Donation sent! Thanks again!

**Comment by azleb** [comment] 2015-04-21 01:33
Can you tell me where I can donate? You guys defiantly deserve it!

**Comment by koko949** [comment] 2015-04-21 01:39
@azleb http://bit.ly/1Jmb4wQ

@dasilva333 if you can point me in the right direction to 2.0.4, that would be great. I didn't see it in the dist list.

**Comment by dasilva333** [comment] 2015-04-21 01:46
@koko949 the normal one is this: https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny.ipa it might say 1.9.8 but that's only because I dont update every version but it's hydrated so it'll auto update to the latest version

**Comment by OUTFOXEM** [comment] 2015-04-21 01:50
YES!  It works!  Thank you for sticking with it even though it only affected one specific phone.  It seemed like you were giving up, but I couldn't really blame you.  But here we are just a few hours later and it works.

Thanks a lot!

**Comment by koko949** [comment] 2015-04-21 03:22
Awesome! This is so great! Thanks!

**Comment by traximilian** [comment] 2015-04-21 05:25
Hi All,

Richard/dasilva333 is the one that has been developing the app and deployed the fix. I was just contributing to the thread here and trying to help as much as possible for the community. I am in no way officially affiliated with the app.

Please donate to dasilva333 as he does the project in his free time and any and all contributions help keep the app free for the community. Here is a mobile link to donate: https://mobile.paypal.com/us/cgi-bin/webscr?cmd=_express-checkout-mobile&useraction=commit&token=EC-6FK31197J77899706#m.

If you aren't on mobile please visit www.towerghostfordestiny.com and you will be able to donate via the site.

Thanks again and I hope everyone that's had issues in the past is now able to enjoy the app!
