### ISSUE TITLE
Side by Side Comparison

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#477] opened 2015-11-27 13:40 UTC
This is just an idea I had, after the issue I experienced with the tooltips not working for a bit.  Is it even a possibility to have multiple tooltips on screen to compare two (or three perhaps) items?  This would be almost identical to how you can do it in game by using right trigger to compare your equipped item with an item you're carrying.  Obviously this would apply to any item of the same category regardless of where it is stored; on what character, etc.  I think this would be an awesome feature.  It would be a huge asset to be able to do this.

**Comment by dasilva333** [comment] 2015-11-27 23:57
Duplicate of issue #165 thanks for the feedback

**Closed by dasilva333** 2015-11-27 23:57 UTC
