### ISSUE TITLE
Minimise number of rows of icons in each block keeping horizontal alignment.

### ISSUE THREAD

**Issue by lanejcf** [dasilva333/TowerGhostForDestiny#62] opened 2015-04-18 16:32 UTC
All the blocks for each Guardian line up across the page in Chrome. It always shows 3 rows of icons for Primary weapons etc. even when each guardian only has say 6 items in store.

So my suggestion would be that if Guardian 1 had 3 Primary in store, G2 had 6 Primary and G3 had 2 Primary, the minimum number of rows required for all 3 Guardians would be 2, rather than the default 3

This would minimise scrolling, but keep things aligned horizontally.

Great Product, keep up the good work.

**Comment by dasilva333** [comment] 2015-04-18 16:37
I don't understand the suggestion, please provide any screenshots or visual reference as to what you mean however be aware that having all sections take up 9 slots is by design. Thank you

**Comment by lanejcf** [comment] 2015-04-18 16:51
I have attached an image, so basically wondering if the rows i have marked with a red pen could be removed so minimising scrolling, fitting more on a page.  The Special weapons block remains as is because it requires 3 rows.  Apply this logic to armour and misc also.

![capture](https://cloud.githubusercontent.com/assets/11978393/7216312/fc7546e2-e5f2-11e4-8623-5de6cbd9cc0a.GIF)

Hope this helps.

**Comment by dasilva333** [comment] 2015-04-18 16:53
Sorry man that goes against issue #48 which I just finished closing in favor of that extra space. Perhaps in the future I'll make it an option or a setting under View. Thanks for your feedback

**Closed by dasilva333** 2015-04-18 16:53 UTC
Labels: enhancement

**Comment by lanejcf** [comment] 2015-04-18 17:00
Sorry, but my suggestion has nothing to do with number 48, i am happy with the way stored and equipped items are displayed, it's the removal of complete blank rows if they can be removed from all 3 guardians.

**Comment by SirLugash** [comment] 2015-04-24 00:46
If a little input is allowed, I'd rather keep it the way it is. Sure your suggestion would reduce scrolling, however the alignment as it is represents the game's way which we are all accustomed to. Also you can easily see that way how many slots are open without checking how many rows there are.

**Comment by Titus-s** [comment] 2015-04-24 07:23
I agree, but there should be an option to remove those empty lines. 
Keeping horizontal alignment is important if your view contains 2 or more columns. If you see only one column (like on mobile in vertical) keeping horizontal alignment should be automatically disabled as it is not needed. 
Remove empty lines is especially important on mobile and when filter(s) are applied. 
For example if you search for specified item on mobile you have to scroll all pages with empty lines to find the one you want. With this option it should be visible without scrolling.

**Comment by dasilva333** [comment] 2015-04-24 12:40
Hey guys let's move the discussion to issue #88 I decided I'll make it an option it'll be under settings and be called "Add Alignment Padding" or something like along those lines. Feel free to leave feedback there as to what to call the option so it's easy to understand thanks!
