### ISSUE TITLE
Windows Phone App is broken

### ISSUE THREAD

**Issue by hueligton** [dasilva333/TowerGhostForDestiny#524] opened 2015-12-23 21:55 UTC
WP app is returning a white page since 3.7.0.0. The version of today 3.7.1.0 is not working too. Using a Lumia 930. Tested reinstall, reboot system, delete reboot and install, and lot other combinations. First time its impossible to login, then everything comes white and stay in this way. Way 30minutes open and nothing. The version before that was working perfectly.

If possible, please, put the old one back until you can correct the error. I think this end of the year will be a busy time for you.

Thanks a lot.

**Comment by dasilva333** [comment] 2015-12-24 01:32
@hueligton thanks for the update I'll get it fixed ASAP

**Comment by dasilva333** [comment] 2015-12-24 13:16
3.7.4.1 is out in the WP store let me know if you still have any issues thanks

**Comment by hueligton** [comment] 2015-12-24 14:11
Same problem. When click in Xbox or psn nothing happens, and is reboot the app, just white screen. I tried reinstall.

**Comment by dasilva333** [comment] 2015-12-24 14:56
@hueligton did you try to install version 3.7.4.1 ? Let me know thanks

**Comment by hueligton** [comment] 2015-12-24 15:03
The version available in store is 3.7.4.0. Maybe I need wait same hours to see this new version. But, the version 3.7.4.0 was available today.

**Comment by dasilva333** [comment] 2015-12-24 16:33
@hueligton Right that's the one, please try to do a full uninstall and reinstall of the app no reboots required simply remove the app and then install it from the store and let me know if you're still having problems. Thanks

**Comment by hueligton** [comment] 2015-12-24 16:48
With 3.7.4.0 no results. Made full uninstall again and nothing. I will wait receive 3.7.4.1 and I update you with news

**Comment by hueligton** [comment] 2015-12-27 01:36
Version 3.7.4.1 not available in store. Maybe something was wrong with publishing. 3.7.4.0 still with error.

Thanks for the attention.

**Comment by dasilva333** [comment] 2015-12-27 18:55
3.7.4.0 is what it displays in a certain view in Microsoft's store system however if you press on the top left TGD word in the app it should display 4.7.4.1. I understand you are having a white screen problem that probably prevents you from loading the app? Try clearing the cache do a full uninstall and reinstall is the best advice I can give you, it seems to be working for me. Good luck

**Comment by hueligton** [comment] 2015-12-27 21:35
How can I clear the cache?

**Comment by dasilva333** [comment] 2015-12-28 00:08
I'm not sure actually, I've never had that problem and I've only ever uninstalled and reinstalled it. Just a quick google search turns up this app: https://www.microsoft.com/en-us/store/apps/cache-cleaner-pro/9wzdncrdc6mm Good Luck

**Comment by hueligton** [comment] 2015-12-28 01:26
Tested and no results. Made another test, took my moms Lumia 930 and installed (for the first time ever) and same thing. Maybe the problem is with Lumia's 930 in general, but not with another's.

**Comment by dasilva333** [comment] 2015-12-28 14:07
@hueligton thanks for the info I'm currently gathering feedback from others to try to see if it's an isolated issue or if there's something else going on. Do you remember what the last version that worked for you was? I'm guessing 3.6.8 since that was the last release I created since 3.7.0.1. Let me know thanks

**Comment by hueligton** [comment] 2015-12-28 15:40
I'm pretty sure is 3.6.8 (I believe was the version until december 17 or 18). I tested today in my friend's Lumia 920 (who has already installed) and same thing, white screen when trying login. I will try test in another's.

Maybe some new option in 3.7.0.0 and forward is incompatible with WP 8.1.

**Comment by hueligton** [comment] 2015-12-31 22:03
A friend tested with a Lumia 640 XL and same problem. He already re-install and the same.

**Comment by hueligton** [comment] 2016-01-04 05:51
First of all, Happy New Year.

I Updated, then full reinstall with cache clean and same white screen. Thanks.

**Comment by dasilva333** [comment] 2016-01-04 14:55
So I haven't been able to reproduce the problem completely, i got it to behave that way once by random mistake by building an app that has a mismatched manifest to what' bundled so the end result was the app unable to load any of the resources and it just got stuck on a white screen for me. After I fixed the manifest the app started working normally again that's how I was able to test and verify 3.7.6 as working before releasing it to the store. I'd like to say its a cache problem but you're saying this problem show itself on brand new devices also. The biggest issue in getting this problem resolve right now is simply reproducing it to be able to fix it. Thanks @hueligton

**Comment by hueligton** [comment] 2016-01-04 15:10
I have an idea. Maybe the problem is with the inside browser used to login, because when I launch for the first time the white screen appears only after try login and the second and beyond every time I launch. Maybe the browser is crashing. I don't know if it's really the problem. I'll try in another's WP to see if the problem persist and I tell you.

**Comment by hueligton** [comment] 2016-01-04 15:14
Ohhh, another tip, when I launch for the first time and click in Xbox or Psn nothing happens, but if I click in logout the white screen appears.

**Comment by dasilva333** [comment] 2016-01-04 15:27
Do you have the ability to sideload apps using the Application Deployment Tool? If so try this xap file and let me know if you still have problems with it: https://build.phonegap.com/apps/1441696/download/winphone Thanks

**Comment by hueligton** [comment] 2016-01-04 16:22
Unfortunately not, but if you tell what to do I do with pleasure.

**Comment by dasilva333** [comment] 2016-01-04 20:43
Follow this tutorial I found online on how to use the deployment tool: http://winphonehub.org/tutorials/tips-deploy-xap-using-application-deployment-tool-windows-phone-88-1/ Good luck

**Comment by hueligton** [comment] 2016-01-06 14:39
I tried, but I had a problem 0x81030120. I found online this:

"Remove ID_CAP_INTEROPSERVICES capabilities
 
<Capability Name="ID_CAP_INTEROPSERVICES" /> 

inside application manifest WMAppmanifest.xml file"

I understood  this arquive are inside the XAP file you send me, so, I wasn't able to change.

**Comment by DeviDarkL** [comment] 2016-01-07 12:54
Hi,

I have the same problem on Lumia 1320. It was working before december update and now it is stuck on white screen. If I uninstall and install it again the login GUI show up but when I click XBOX LIVE or PSN it does nothing. If I close and open the app again: White screen :/

**Comment by dasilva333** [comment] 2016-01-09 23:39
Hey guys try out 3.7.8 and let me know if it's still an issue, I was having a similar issue I'm not sure if it's the same one here's what would happen to me:

1. App opens and shows the GUI
2. Click on Playstation Network
3. Login with my account
4. loads fine

and then I try it again


1. App opens and shows the GUI
2. Click on XBox LIve
3. Login with my account
4. crashes during loading

If this is the problem you were having it should be fixed now

**Comment by hueligton** [comment] 2016-01-10 00:48
Hello Richard,

I updated, full reinstall, full reinstall with cache clean before and same error.

What happens to me is:
1)App open and show GUI
2.1)if I click in Xbox or Playstation nothing happens
2.2)if I go to settings and click in log out, white screens appears,
2.3)if I close and opens again, white screens appears,
2.4)but if I go to settings and click in PSN Login loads fine. If I click in "X" to close, everything continues normal, but GUI still not work and it's still impossible to login with Xbox.

The only way possible to login with PSN are for settings menu.

So, we have some progress with PSN.

**Comment by hueligton** [comment] 2016-01-10 00:51
P.S.: with you was able to handle with WMAppmanifest.xml file, send me the new XAP file to do the test you said before.

Thanks.

**Comment by DeviDarkL** [comment] 2016-01-10 16:35
For me it happens exactly the same as hueligton. It's not fixed yet with version 3.7.8 :(

**Comment by dasilva333** [comment] 2016-05-05 20:06
tracking issue in ticket #599 I'll update my status there once the WP app is up and running again, thanks guys

**Closed by dasilva333** 2016-05-05 20:06 UTC
Labels: bug, help wanted
