### ISSUE TITLE
Windows Phone app stopped working

### ISSUE THREAD

**Issue by marmau83** [dasilva333/TowerGhostForDestiny#113] opened 2015-04-29 23:03 UTC
The hydrated update that came down last broke my app.  The app says its v 2.1.9.  Everything was working great, but when I took the in app update it stopped working.  When the app re-launched, it did not take me back to the login prompt.  When I go into the settings menu, and select Live or Xbox account login - nothing happens.  In fact, none of the menu options are working now.  When I select something, nothing happens.  Playing destiny with 3 toons sucks now : .. - (

Note that I am running Windows 10 for phones preview build - so it may be my phone.  Was wondering if anyone else has reported anything (I didn't see anything here or the reddit forums).

**Comment by equesaspe** [comment] 2015-04-30 00:10
Same here.  Seeing if uninstalling/reinstalling fixes.

**Comment by equesaspe** [comment] 2015-04-30 00:14
yes it is broken.  Completely non-functional. Only shows "Weapons (/)" and otherwise completely unresponsive.

**Comment by whitesidema** [comment] 2015-04-30 02:50
It quit on me also. What's the use of having an app that is broken and get no response nor any decent response time for a fix. I'm on a Lumia 512 windows 8. It used to work and then told all my fellow gamers and theirs all work but mine. This isnt right. Please fix this. I don't even get to sign in. Just hydrated then white screen then grey blank screen sayin weapons and that's it. Can't even get a shot to sign in.

**Comment by whitesidema** [comment] 2015-04-30 02:52
I've even installed and uninstalled the software a dozen times and still don't work. Including hard and cold boots of my phone after uninstalls.

**Comment by marmau83** [comment] 2015-04-30 03:41
Sweet update fixed it.  Thanks dasilva, youre awesome.  Definitely will send some beer funds your way soon!

**Comment by dasilva333** [comment] 2015-04-30 13:18
@marmau83 I'm glad that fixed it for you, windows-phone has been behaving erratically where the same code running on other branches simply refuses to load on WP. The compromise hack was to disable local image caching for WP to get 2.2.2 to work properly.

Sorry for leaving it broken I didn't notice until last night and I was also in the middle of another big bug that just happened. Closing this ticket as the issue is fixed, if you're still having problems do a full uninstall/reinstall and 2.2.2 should be loading for you now.

Thanks guys

**Closed by dasilva333** 2015-04-30 13:18 UTC
Labels: bug
