### ISSUE TITLE
Some weapons (exotics only?) that are fully upgraded still show in "Missing XP" list

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#225] opened 2015-05-27 13:52 UTC
In general, Missing XP appears to be working.

However, Gjallarhorn and The Last Word (in my arsenal) still show as 'missing XP', where they are fully upgraded and ascended.

Let me know if you need more details!

![5-27-2015 8-50-20 am](https://cloud.githubusercontent.com/assets/2037051/7837595/ad90edf0-044d-11e5-8b53-2a48cd094825.png)

**Comment by M3Rocket** [comment] 2015-05-27 17:28
I can confirm this "weirdness." I have 3 Gally's with 2.6.3. Two are maxed and fully upgraded to 365, one is full XP but not maxed. Strangely, when I select Missing XP, one of the maxed 365 shows! When I select Maxed, the other 365 maxed appears correctly. Full XP seems to be working correctly with my third. 

But I can see all kinds of weirdness with other weapons as well with regard to XP.

**Comment by ssoriche** [comment] 2015-05-27 17:32
The last time this was discussed (issue #219), the values are fed from the Bungie API and the API was reporting incorrectly.

**Comment by M3Rocket** [comment] 2015-05-27 17:34
@ssoriche Ah yes! I remember it now.

**Comment by dasilva333** [comment] 2015-05-27 17:34
That's correct @ssoriche the API is still bugged so there's nothing I can do to fix it until Bungie fixes it on their side, closing this ticket as it's not something I can address

**Closed by dasilva333** 2015-05-27 17:34 UTC

**Comment by rkingsla** [comment] 2015-05-27 21:05
Darn it!  Completely forgot about the Bungie API issue...  Apologies....  Well, better reported and closed than not reported at all.  :o)
