### ISSUE TITLE
Sizing Issue as posted on Reddit.

### ISSUE THREAD

**Issue by JonathanRyanFrederick** [dasilva333/TowerGhostForDestiny#59] opened 2015-04-18 01:28 UTC
Hello Dasilva333,

Got some screen caps for ya..
https://farm8.staticflickr.com/7711/16995100998_c3b83a7d2e_z.jpg
That is how your app currently looks on my Galaxy Note 4 downloaded from the Play Store.

I feel like here the toolbar at the top and it's corresponding menus look and function great. My issue is with the sizing of the weapons/gear icons. As you can see here due to the size of the icons I see very little information at any given point in time. This is with only weapons being visible. 

If you look at this screen cap of the app Destiny Item Viewer you will see what is more desirable. 
https://farm9.staticflickr.com/8714/16995101248_271ee68e7d_z.jpg
Here, with again only weapons visible, I can see all my vault plus all the weapons on all three characters.

The only issue with that app, DIV, if that their toolbar and menus are so small I literally have to squint to make sure I flick the item. As you can see in that screen shot of the DIV app, you can hardly even read the menu font.

Want I would ideally want to see is the menu features you created but with the icon sizing of the DIV app so I can see much more at once.

Currently there are 3 great destiny apps in circulation. Your app (Tower Ghost), DIV, and the DIM chrome extension. 
Each one falls short in just one way. 
Tower Ghost doesnt give me enough info at once.
Destiny Item Viewer load outs will not save after app shuts down plus menus are tiny.
Destiny Item Manager is not in a mobile app and has no DBtooltips. 

If you could fix the sizing of your icons to view more like DIV then you sir would have the best app hands down.

One other issue I saw was while trying to make load outs I was having issues selecting weapons. It almost felt like my phone touch sensitivity was malfunctioning but it would ONLY happen when trying to create load outs. Once I clicked cancel I could easily click anything but once I clicked create load out I would have to click a weapon a couple times and press hard to get it to register.

Not sure what was going on there. 

Lastly. If at all possible it would be awesome if the app would remember I view weapons only so that every time I open the app I dont have to click only weapons again. 

Jonathan

**Comment by dasilva333** [comment] 2015-04-18 01:37
Tower Ghost and DIV are the same app I just renamed it.Thanks for the screenshot I haven't seen a good problem like that in a while. If you can tell me what device you have that would help too. Expect a lot of fixes in 1.9.0

**Comment by JonathanRyanFrederick** [comment] 2015-04-18 01:41
I am using a Galaxy Note 4 smartphone. It is a pretty large screen.
Honestly, DIV is a great app, I still have it on my phone. haha
Tower Ghost is great too. Ultimately I want to see the toolbar/menu of Tower Ghost with the gear icon/layout of DIV.

Great work! Cant wait to see the fixes in 1.9.0

**Comment by NoCodeLeftBehind** [comment] 2015-04-18 17:30
Jonathan, have you tried just using landscape orientation? You should be able to see much more there. In prior versions of DIV, the icons were too small for average-sized screens, so a balance must be struck.

**Comment by dasilva333** [comment] 2015-04-18 17:44
@NoCodeLeftBehind I think there really is a bug however it has to do with webkit-min-device-pixel-ratio, his device has an abnormally high value of 3 and none of my css is built to handle it. I'm having a terrible time getting an emulator to try to reproduce so I'm not sure how I'll end up fixing it.

Thanks guys

**Comment by dasilva333** [comment] 2015-04-18 22:44
@JonathanRyanFrederick To clarify what I said earlier based on the ratio (3x) and your resolution (1440x2560) of your device the pages should be running at a virtual 480px in width which means you should be seeing two columns on portrait mode and 3 columns in landscape mode. Please provide screenshots of TGD 1.9.5 or above in both orientations thanks

**Comment by dasilva333** [comment] 2015-04-24 22:37
@JonathanRyanFrederick Progress update I will have to use Browserstacks to test the layout in various browsers, so I have to recreate a static version of my items without any of the logic. Marking this as an enhancement since nothing is technically broken and help wanted in case any one is up for it.

**Comment by matthubb** [comment] 2015-04-26 17:18
Could the device mode under Chrome devtools be useful for mobile layout/style development?

I don't know what phonegap does for the other platforms, so my first guess Chrome device emulation doesn't load because of some multiplatform magic by phonegap missing from the git source?

There are some pixel layout issues on iDevices and trying to demo on desktop chrome has been a non-starter so far. 

Might it be possible to have a development code setting to override/hardcore the device detection for testing?

**Comment by dasilva333** [comment] 2015-04-26 18:01
@matthubb no it's useless I've tried setting the ratio to 3 and it doesn;t resemble at all what it looks like on a Nexus 6 or a Note 4, I created a branch called static in the repo that contains a ready to go html project that's testable under browserstacks.com just download it and run it locally

**Comment by dasilva333** [comment] 2015-05-03 21:12
@JonathanRyanFrederick hey man the css has been improved a lot since 1.8.9 could you provide some screenshots of the app running in 2.3.0? Thanks! I just want to make sure this is still an issue or if I should close it

**Comment by JonathanRyanFrederick** [comment] 2015-05-03 21:25
Yeah it looks fine. I still wish I could see 3 Guardians on screen in
landscape and 2 in portrait but I understand the limitations due to other
people owning smaller phone.
Would be nice if we could have an option to zoom in or out then lock it at
the size we want. I feel the icons are just twice as big as they need to
be.

Great app though. Good work.
Jonathan

**Comment by dasilva333** [comment] 2015-05-03 22:01
@JonathanRyanFrederick hey man I updated the app to 2.3.2 on master/android try it out now and let me know what you think. Also if you could provide me some screenshots of the layout in landscape I'd like to see it because it's doing 3 columns for me. Thanks again and I do agree you should have 2 and 3 columns on your device.

**Closed** 2015-08-15 18:45 UTC
Labels: enhancement, help wanted
