### ISSUE TITLE
Fix for Song of Ir Yut and other items like it

### ISSUE THREAD

**Issue by marmotpie** [dasilva333/TowerGhostForDestiny#115] opened 2015-04-30 08:29 UTC
I'm using a Note 4 with Android 5.0.1. Every time I start the app, Hydra detects a new update; the version number shown in the About page displays 2.2.2 regardless of whether I select to ignore the update or install and restart. Three finger tapping the screen does not detect a new update. This issue has gone on for weeks, though it was manageable as I could avoid it by minimizing the app rather than closing it.

The second issue just started happening a few hours ago. In addition to having to sign in each time I open the app, only my vault and my hunter's items are displayed, while the blue loading bar persists. I let it try to load for 30 minutes, to no avail.

I have tried uninstalling and re-installing (both from the Play Store and manually from the download page here) multiple times, including clearing cached data and restarting my phone.The Chrome extension and Bungie's official app both still work for me.

**Comment by weborican** [comment] 2015-04-30 14:43
I have seen both issues, but the issue with the loading not finishing just started happening yesterday. Loads my vault and my warlock, but stops at my Titan and Hunter. On the iPhone everything works fine, both running 2.2.2.

iPhone 6, running iOS 8.3
Nexus tablet, running Android 5.1

**Comment by dasilva333** [comment] 2015-04-30 16:37
@marmotpie 
- I don't control how the Hydra updater works it's part of Adobe's project
- The update should only show up when there is a new version, gestures has been known to be buggy
- You should only have to sign in once, if you have to sign in every time I'll test it on Android tonight to make sure it's working as expected.
-If your items are partly loading that's an indication of connection/network connectivity issues on your end because once it starts grabbing some of the data there should be no problem grabbing the rest.

I'll mark this ticket as a bug and try to reproduce the issues tonight. thanks @weborican I'm glad it's working on your Android too

**Comment by marmotpie** [comment] 2015-04-30 18:35
@dasilva33 Thanks for looking into it. I've tried it on different WiFi networks as well as on 4G/mobile, to the same result. This leads me to believe it is unlikely a network error from my end, though I suppose it could be my device (though I have restarted it multiple times).

Also, I think you may have misread, @weborican is having the same loading issue - he said it works correctly on his iPhone, not on his Android.

**Comment by NoCodeLeftBehind** [comment] 2015-04-30 18:55
Latest 2.2.2 hangs at blue loading bar on Android. Works fine on iOS.

**Comment by blackhawksq** [comment] 2015-04-30 19:47
I started getting the same problem this morning. It worked great last night, had an update this morning and now it will only show my titan. This is not a network problem.  I'm using Galaxy s5

**Comment by M3Rocket** [comment] 2015-04-30 19:56
Same here with me on both my Nexus 7 (2013) and Nexus 4. It started happening last night. It will only load one of my characters, but not the vault or the other two characters. Blue bar on the top stays. I've tried clearing cache, uninstall, reinstall. I don't think this is a network issue.

**Comment by dasilva333** [comment] 2015-04-30 20:35
Alright guys there's enough people having this problem that I don't think it's an isolated issue anymore, again I tested the latest version 2.2.2 on my Android device and it worked fine, I'll try it on my phone and tablet tonight and make necessary fixes. I also compared trunk to android and they are identical so I'm not sure what could be the cause. 
Thanks!

**Comment by M3Rocket** [comment] 2015-04-30 21:30
I deleted the cache, data and uninstalled the Google Play downloaded version and hydrate-upgraded version. Then I sideloaded the 2.1.4 version from this repo (https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist/), and declined the Hydrate update notice. This version seems to work.

I suspect Hydrate shenanigans.

**Comment by dasilva333** [comment] 2015-04-30 22:35
@M3Rocket I just uninstalled and reinstalled the app store version and let it update on the first prompt and it worked fine. I also just tried the one on my tablet also using the app store version just opened it and let it update and it worked fine.

So this apk goes out to @weborican @NoCodeLeftBehind @blackhawksq @marmotpie  and @M3Rocket here's what I need you all to do now it's going to be tricky because you are all going to be sharing one session so if you see someone is currently using it don't try it too. Thanks

1. install this debug apk:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny-debug-115.apk
2. go to jsconsole.com
3. type this in
> :listen C6781150-414A-4E02-8A48-B0B2A300DACF
4. open the app and try to get it to crash or only load one character
5. if a crash does happen it'll output something to the console just paste it in www.pastebin.com and report it here

**Comment by weborican** [comment] 2015-04-30 23:04
My Nexus will not install that .apk, I get the "app not installed" message  :-(

**Comment by M3Rocket** [comment] 2015-04-30 23:13
I'm going to try the debug version right now.

**Comment by ambrice** [comment] 2015-04-30 23:15
Also get the stuck loading bar.  Will try the apk, in the mean time here's the adb logcat: 

http://pastebin.com/raw.php?i=fRq7fPQ6

**Comment by ambrice** [comment] 2015-04-30 23:29
On jsconsole I get the same uri malformed at app.js:828 error from adb logcat, and also:

file:///data/data/com.richardpinedo.towerghostfordestiny/files/downloads/app_dir/scripts/bungie.js:188
Uncaught TypeError: Cannot read property 'type' of undefined

**Comment by M3Rocket** [comment] 2015-04-30 23:31
I'm also getting something similar like this:
file:///data/data/com.richardpinedo.towerghostfordestiny/files/downloads/app_dir/js/app.js:828
Uncaught URIError: URI malformed
-----------------------------
Connection established with file:///data/data/com.richardpinedo.towerghostfordestiny/files/downloads/app_dir/index.html
Mozilla/5.0 (Linux; Android 5.1; Nexus 5 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.129 Mobile Safari/537.36

**Comment by ambrice** [comment] 2015-04-30 23:52
app.js:828 was apparently updated yesterday in commit 41e5a9f8b6e1c1ee357d70f1bd961d549ed8b81e "Fix for Song of Ir Yut".  I don't have the Song but I do have the Fang..

**Comment by dasilva333** [comment] 2015-05-01 00:15
Thanks @M3Rocket I was trying to fix the encoding of the characters so they look right getting tired of seeing song of ir yacht. Anyhow I followed the some online advice and apparently there's problems between platforms, I couldn't even find references to Android and the technique used decodeURIComponent(escape anyways I backed out the change as part of 2.2.3 expect it soon and I'll rename this to Fix for Song of Ir Yut later.

**Comment by NoCodeLeftBehind** [comment] 2015-05-01 00:16
I have both Song and Fang. I assume that commit was intended to fix the way the accented letter in Yut was being displayed. Perhaps that broke things for some devices depending on language or font being used... Can you please make a build without that commit to test that theory?

**Comment by weborican** [comment] 2015-05-01 00:18
Bigo @NoCodeLeftBehind 

If I move my Fang to my Titan, both my Hunter and Warlock now load and it gets stuck on loading my Titan.

**Comment by ambrice** [comment] 2015-05-01 00:21
Can confirm.  It wouldn't show my Vault until I moved my "Façade of the Hezen Lords" out of it, and wouldn't show my Titan until I moved my "Dämmerung FR5"

**Comment by dasilva333** [comment] 2015-05-01 00:22
Alright guys its part of master and android branch so look for 2.2.3 under About to make sure you have the fix

**Comment by M3Rocket** [comment] 2015-05-01 00:29
Thanx for the quick fix @dasilva333 -- those pesky foreign characters. It bothers me too, but the Tower Ghost Android app not working altogether is worse. ;-)

Thanx @ambrice for the assist!

**Comment by ambrice** [comment] 2015-05-01 00:37
Confirmed, 2.2.3 shows everything.

**Comment by M3Rocket** [comment] 2015-05-01 00:40
Same here. 2.2.3 works now.

Also, I checked the names of Facade and Ir Yut on Android app, and it shows the proper accented characters.

**Comment by weborican** [comment] 2015-05-01 01:12
All is well on Andriod once again! Thanks @dasilva333 for that super-quick fix!!!

**Comment by dasilva333** [comment] 2015-05-03 13:42
Hey guys I introduced a new fix for the Song of Ir Yut as of 2.3.0, can anyone test and confirm it's still working on their device? Thanks! @marmotpie @M3Rocket @NoCodeLeftBehind @blackhawksq @ambrice @weborican

**Comment by matthubb** [comment] 2015-05-03 14:52
I have the Song. Displays and transfers fine on iOS.

**Comment by dasilva333** [comment] 2015-05-03 15:11
@matthubb ios wasn't affected by this bug only certain Android platforms that's why I asked those guys specifically to try it out. Let me know guys thanks!

**Comment by marmotpie** [comment] 2015-05-03 15:15
Everything appears to be working as intended on 2.3.0. Each character loads correctly and I'm able to transfer and equip both Fang and Song of Ir Yut with no issues.

**Comment by M3Rocket** [comment] 2015-05-03 18:21
Tried both Fand and Song. Works as intended for me.

**Comment by dasilva333** [comment] 2015-05-03 18:22
Alright thanks guys, hate to reopen a closed ticket but I just wanted to make sure there's no problem this time. Closing ticket as fixed

**Closed by dasilva333** 2015-05-03 18:22 UTC
Labels: bug

**Comment by weborican** [comment] 2015-05-04 18:23
I'm a day late, but all is well with all the "Yuts" on Android and iOS at my end as well.
