### ISSUE TITLE
(Expected) TGfD doesn't work w/ 2.0

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#359] opened 2015-09-08 18:41 UTC
GET chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/cordova.js net::ERR_FILE_NOT_FOUND
app.js:848 Uncaught ReferenceError: error is not defined(anonymous function) @ app.js:848cname.request.$.ajax.complete @ bungie.js:114m.Callbacks.j @ jquery.js:2m.Callbacks.k.fireWith @ jquery.js:2x @ jquery.js:4m.ajaxTransport.a.send.b @ jquery.js:4
ga.js:63 crash reported Uncaught ReferenceError: error is not defined
ga.js:64 ErrorEvent {}bubbles: falsecancelBubble: falsecancelable: truecolno: 90currentTarget: WindowdefaultPrevented: falseerror: ReferenceError: error is not defined
    at Object.complete (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/app.js:848:90)
    at Object.cname.request.$.ajax.complete (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/scripts/bungie.js:114:34)
    at m.Callbacks.j (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/dependencies/jquery.js:2:27295)
    at Object.m.Callbacks.k.fireWith (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/dependencies/jquery.js:2:28108)
    at x (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/dependencies/jquery.js:4:22189)
    at XMLHttpRequest.m.ajaxTransport.a.send.b (chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/dependencies/jquery.js:4:25980)eventPhase: 0filename: "chrome-extension://omlfmfglhhaencodijkaoijoggkcnogm/www/js/app.js"lineno: 848message: "Uncaught ReferenceError: error is not defined"path: Array[1]returnValue: truesrcElement: Windowtarget: WindowInfinity: Infinity$: (a,b)$ZamTooltips: ObjectAnalyserNode: AnalyserNode()AnimationEvent: AnimationEvent()AppBannerPromptResult: AppBannerPromptResult()AppView: appview()ApplicationCache: ApplicationCache()ApplicationCacheErrorEvent: ApplicationCacheErrorEvent()Array: Array()ArrayBuffer: ArrayBuffer()Attr: Attr()Audio: HTMLAudioElement()AudioBuffer: AudioBuffer()AudioBufferSourceNode: AudioBufferSourceNode()AudioContext: AudioContext()AudioDestinationNode: AudioDestinationNode()AudioListener: AudioListener()AudioNode: AudioNode()AudioParam: AudioParam()AudioProcessingEvent: AudioProcessingEvent()AutocompleteErrorEvent: AutocompleteErrorEvent()BarProp: BarProp()BatteryManager: BatteryManager()BeforeInstallPromptEvent: BeforeInstallPromptEvent()BeforeUnloadEvent: BeforeUnloadEvent()BiquadFilterNode: BiquadFilterNode()Blob: Blob()Boolean: Boolean()BootstrapDialog: (options)CDATASection: CDATASection()CSS: CSS()CSSFontFaceRule: CSSFontFaceRule()CSSGroupingRule: CSSGroupingRule()CSSImportRule: CSSImportRule()CSSKeyframeRule: CSSKeyframeRule()CSSKeyframesRule: CSSKeyframesRule()CSSMediaRule: CSSMediaRule()CSSPageRule: CSSPageRule()CSSRule: CSSRule()CSSRuleList: CSSRuleList()CSSStyleDeclaration: CSSStyleDeclaration()CSSStyleRule: CSSStyleRule()CSSStyleSheet: CSSStyleSheet()CSSSupportsRule: CSSSupportsRule()CSSViewportRule: CSSViewportRule()Cache: Cache()CacheStorage: CacheStorage()CanvasGradient: CanvasGradient()CanvasPattern: CanvasPattern()CanvasRenderingContext2D: CanvasRenderingContext2D()ChannelMergerNode: ChannelMergerNode()ChannelSplitterNode: ChannelSplitterNode()CharacterData: CharacterData()ClientRect: ClientRect()ClientRectList: ClientRectList()ClipboardEvent: ClipboardEvent()CloseEvent: CloseEvent()Comment: Comment()CompositionEvent: CompositionEvent()ConvolverNode: ConvolverNode()Crypto: Crypto()CryptoKey: CryptoKey()CustomEvent: CustomEvent()DOMError: DOMError()DOMException: DOMException()DOMImplementation: DOMImplementation()DOMParser: DOMParser()DOMSettableTokenList: DOMSettableTokenList()DOMStringList: DOMStringList()DOMStringMap: DOMStringMap()DOMTokenList: DOMTokenList()DataTransfer: DataTransfer()DataTransferItem: DataTransferItem()DataTransferItemList: DataTransferItemList()DataView: DataView()Date: Date()DelayNode: DelayNode()DeviceMotionEvent: DeviceMotionEvent()DeviceOrientationEvent: DeviceOrientationEvent()Document: Document()DocumentFragment: DocumentFragment()DocumentType: DocumentType()DynamicsCompressorNode: DynamicsCompressorNode()Element: Element()Error: Error()ErrorEvent: ErrorEvent()EvalError: EvalError()Event: Event()EventSource: EventSource()EventTarget: EventTarget()ExtensionOptions: extensionoptions()ExtensionView: extensionview()FastClick: FastClick(layer, options)File: File()FileError: FileError()FileList: FileList()FileReader: FileReader()Float32Array: Float32Array()Float64Array: Float64Array()FocusEvent: FocusEvent()FontFace: FontFace()FormData: FormData()Function: Function()GainNode: GainNode()Gamepad: Gamepad()GamepadButton: GamepadButton()GamepadEvent: GamepadEvent()HTMLAllCollection: HTMLAllCollection()HTMLAnchorElement: HTMLAnchorElement()HTMLAppletElement: HTMLAppletElement()HTMLAreaElement: HTMLAreaElement()HTMLAudioElement: HTMLAudioElement()HTMLBRElement: HTMLBRElement()HTMLBaseElement: HTMLBaseElement()HTMLBodyElement: HTMLBodyElement()HTMLButtonElement: HTMLButtonElement()HTMLCanvasElement: HTMLCanvasElement()HTMLCollection: HTMLCollection()HTMLContentElement: HTMLContentElement()HTMLDListElement: HTMLDListElement()HTMLDataListElement: HTMLDataListElement()HTMLDetailsElement: HTMLDetailsElement()HTMLDialogElement: HTMLDialogElement()HTMLDirectoryElement: HTMLDirectoryElement()HTMLDivElement: HTMLDivElement()HTMLDocument: HTMLDocument()HTMLElement: HTMLElement()HTMLEmbedElement: HTMLEmbedElement()HTMLFieldSetElement: HTMLFieldSetElement()HTMLFontElement: HTMLFontElement()HTMLFormControlsCollection: HTMLFormControlsCollection()HTMLFormElement: HTMLFormElement()HTMLFrameElement: HTMLFrameElement()HTMLFrameSetElement: HTMLFrameSetElement()HTMLHRElement: HTMLHRElement()HTMLHeadElement: HTMLHeadElement()HTMLHeadingElement: HTMLHeadingElement()HTMLHtmlElement: HTMLHtmlElement()HTMLIFrameElement: HTMLIFrameElement()HTMLImageElement: HTMLImageElement()HTMLInputElement: HTMLInputElement()HTMLKeygenElement: HTMLKeygenElement()HTMLLIElement: HTMLLIElement()HTMLLabelElement: HTMLLabelElement()HTMLLegendElement: HTMLLegendElement()HTMLLinkElement: HTMLLinkElement()HTMLMapElement: HTMLMapElement()HTMLMarqueeElement: HTMLMarqueeElement()HTMLMediaElement: HTMLMediaElement()HTMLMenuElement: HTMLMenuElement()HTMLMetaElement: HTMLMetaElement()HTMLMeterElement: HTMLMeterElement()HTMLModElement: HTMLModElement()HTMLOListElement: HTMLOListElement()HTMLObjectElement: HTMLObjectElement()HTMLOptGroupElement: HTMLOptGroupElement()HTMLOptionElement: HTMLOptionElement()HTMLOptionsCollection: HTMLOptionsCollection()HTMLOutputElement: HTMLOutputElement()HTMLParagraphElement: HTMLParagraphElement()HTMLParamElement: HTMLParamElement()HTMLPictureElement: HTMLPictureElement()HTMLPreElement: HTMLPreElement()HTMLProgressElement: HTMLProgressElement()HTMLQuoteElement: HTMLQuoteElement()HTMLScriptElement: HTMLScriptElement()HTMLSelectElement: HTMLSelectElement()HTMLShadowElement: HTMLShadowElement()HTMLSourceElement: HTMLSourceElement()HTMLSpanElement: HTMLSpanElement()HTMLStyleElement: HTMLStyleElement()HTMLTableCaptionElement: HTMLTableCaptionElement()HTMLTableCellElement: HTMLTableCellElement()HTMLTableColElement: HTMLTableColElement()HTMLTableElement: HTMLTableElement()HTMLTableRowElement: HTMLTableRowElement()HTMLTableSectionElement: HTMLTableSectionElement()HTMLTemplateElement: HTMLTemplateElement()HTMLTextAreaElement: HTMLTextAreaElement()HTMLTitleElement: HTMLTitleElement()HTMLTrackElement: HTMLTrackElement()HTMLUListElement: HTMLUListElement()HTMLUnknownElement: HTMLUnknownElement()HTMLVideoElement: HTMLVideoElement()Hammer: eb(a,b)HashChangeEvent: HashChangeEvent()Headers: Headers()History: History()IDBCursor: IDBCursor()IDBCursorWithValue: IDBCursorWithValue()IDBDatabase: IDBDatabase()IDBFactory: IDBFactory()IDBIndex: IDBIndex()IDBKeyRange: IDBKeyRange()IDBObjectStore: IDBObjectStore()IDBOpenDBRequest: IDBOpenDBRequest()IDBRequest: IDBRequest()IDBTransaction: IDBTransaction()IDBVersionChangeEvent: IDBVersionChangeEvent()Image: HTMLImageElement()ImageBitmap: ImageBitmap()ImageData: ImageData()Int8Array: Int8Array()Int16Array: Int16Array()Int32Array: Int32Array()Intl: ObjectItem: (model, profile, ignoreDups)JSON: JSONKeyboardEvent: KeyboardEvent()Layout: (layout)Loadout: (model)LoadoutItem: (model)Location: Location()MIDIAccess: MIDIAccess()MIDIConnectionEvent: MIDIConnectionEvent()MIDIInput: MIDIInput()MIDIInputMap: MIDIInputMap()MIDIMessageEvent: MIDIMessageEvent()MIDIOutput: MIDIOutput()MIDIOutputMap: MIDIOutputMap()MIDIPort: MIDIPort()Map: Map()Math: MathConstructorMediaElementAudioSourceNode: MediaElementAudioSourceNode()MediaEncryptedEvent: MediaEncryptedEvent()MediaError: MediaError()MediaKeyError: MediaKeyError()MediaKeyEvent: MediaKeyEvent()MediaKeyMessageEvent: MediaKeyMessageEvent()MediaKeySession: MediaKeySession()MediaKeyStatusMap: MediaKeyStatusMap()MediaKeySystemAccess: MediaKeySystemAccess()MediaKeys: MediaKeys()MediaList: MediaList()MediaQueryList: MediaQueryList()MediaQueryListEvent: MediaQueryListEvent()MediaSource: MediaSource()MediaStreamAudioDestinationNode: MediaStreamAudioDestinationNode()MediaStreamAudioSourceNode: MediaStreamAudioSourceNode()MediaStreamEvent: MediaStreamEvent()MediaStreamTrack: MediaStreamTrack()MessageChannel: MessageChannel()MessageEvent: MessageEvent()MessagePort: MessagePort()MimeType: MimeType()MimeTypeArray: MimeTypeArray()Modernizr: ObjectMouseEvent: MouseEvent()MutationEvent: MutationEvent()MutationObserver: MutationObserver()MutationRecord: MutationRecord()NaN: NaNNamedNodeMap: NamedNodeMap()Navigator: Navigator()Node: Node()NodeFilter: NodeFilter()NodeIterator: NodeIterator()NodeList: NodeList()Notification: Notification()Number: Number()Object: Object()OfflineAudioCompletionEvent: OfflineAudioCompletionEvent()OfflineAudioContext: OfflineAudioContext()Option: HTMLOptionElement()OscillatorNode: OscillatorNode()PageTransitionEvent: PageTransitionEvent()Path2D: Path2D()Performance: Performance()PerformanceEntry: PerformanceEntry()PerformanceMark: PerformanceMark()PerformanceMeasure: PerformanceMeasure()PerformanceNavigation: PerformanceNavigation()PerformanceResourceTiming: PerformanceResourceTiming()PerformanceTiming: PerformanceTiming()PeriodicWave: PeriodicWave()PermissionStatus: PermissionStatus()Permissions: Permissions()Plugin: Plugin()PluginArray: PluginArray()PopStateEvent: PopStateEvent()ProcessingInstruction: ProcessingInstruction()Profile: (character, items, index)ProgressEvent: ProgressEvent()Promise: Promise()PushManager: PushManager()PushSubscription: PushSubscription()RTCIceCandidate: RTCIceCandidate()RTCSessionDescription: RTCSessionDescription()RadioNodeList: RadioNodeList()Range: Range()RangeError: RangeError()ReadableByteStream: ReadableByteStream()ReadableStream: ReadableStream()ReferenceError: ReferenceError()RegExp: RegExp()Request: Request()Response: Response()SVGAElement: SVGAElement()SVGAngle: SVGAngle()SVGAnimateElement: SVGAnimateElement()SVGAnimateMotionElement: SVGAnimateMotionElement()SVGAnimateTransformElement: SVGAnimateTransformElement()SVGAnimatedAngle: SVGAnimatedAngle()SVGAnimatedBoolean: SVGAnimatedBoolean()SVGAnimatedEnumeration: SVGAnimatedEnumeration()SVGAnimatedInteger: SVGAnimatedInteger()SVGAnimatedLength: SVGAnimatedLength()SVGAnimatedLengthList: SVGAnimatedLengthList()SVGAnimatedNumber: SVGAnimatedNumber()SVGAnimatedNumberList: SVGAnimatedNumberList()SVGAnimatedPreserveAspectRatio: SVGAnimatedPreserveAspectRatio()SVGAnimatedRect: SVGAnimatedRect()SVGAnimatedString: SVGAnimatedString()SVGAnimatedTransformList: SVGAnimatedTransformList()SVGAnimationElement: SVGAnimationElement()SVGCircleElement: SVGCircleElement()SVGClipPathElement: SVGClipPathElement()SVGComponentTransferFunctionElement: SVGComponentTransferFunctionElement()SVGCursorElement: SVGCursorElement()SVGDefsElement: SVGDefsElement()SVGDescElement: SVGDescElement()SVGDiscardElement: SVGDiscardElement()SVGElement: SVGElement()SVGEllipseElement: SVGEllipseElement()SVGFEBlendElement: SVGFEBlendElement()SVGFEColorMatrixElement: SVGFEColorMatrixElement()SVGFEComponentTransferElement: SVGFEComponentTransferElement()SVGFECompositeElement: SVGFECompositeElement()SVGFEConvolveMatrixElement: SVGFEConvolveMatrixElement()SVGFEDiffuseLightingElement: SVGFEDiffuseLightingElement()SVGFEDisplacementMapElement: SVGFEDisplacementMapElement()SVGFEDistantLightElement: SVGFEDistantLightElement()SVGFEDropShadowElement: SVGFEDropShadowElement()SVGFEFloodElement: SVGFEFloodElement()SVGFEFuncAElement: SVGFEFuncAElement()SVGFEFuncBElement: SVGFEFuncBElement()SVGFEFuncGElement: SVGFEFuncGElement()SVGFEFuncRElement: SVGFEFuncRElement()SVGFEGaussianBlurElement: SVGFEGaussianBlurElement()SVGFEImageElement: SVGFEImageElement()SVGFEMergeElement: SVGFEMergeElement()SVGFEMergeNodeElement: SVGFEMergeNodeElement()SVGFEMorphologyElement: SVGFEMorphologyElement()SVGFEOffsetElement: SVGFEOffsetElement()SVGFEPointLightElement: SVGFEPointLightElement()SVGFESpecularLightingElement: SVGFESpecularLightingElement()SVGFESpotLightElement: SVGFESpotLightElement()SVGFETileElement: SVGFETileElement()SVGFETurbulenceElement: SVGFETurbulenceElement()SVGFilterElement: SVGFilterElement()SVGForeignObjectElement: SVGForeignObjectElement()SVGGElement: SVGGElement()SVGGeometryElement: SVGGeometryElement()SVGGradientElement: SVGGradientElement()SVGGraphicsElement: SVGGraphicsElement()SVGImageElement: SVGImageElement()SVGLength: SVGLength()SVGLengthList: SVGLengthList()SVGLineElement: SVGLineElement()SVGLinearGradientElement: SVGLinearGradientElement()SVGMPathElement: SVGMPathElement()SVGMarkerElement: SVGMarkerElement()SVGMaskElement: SVGMaskElement()SVGMatrix: SVGMatrix()SVGMetadataElement: SVGMetadataElement()SVGNumber: SVGNumber()SVGNumberList: SVGNumberList()SVGPathElement: SVGPathElement()SVGPathSeg: SVGPathSeg()SVGPathSegArcAbs: SVGPathSegArcAbs()SVGPathSegArcRel: SVGPathSegArcRel()SVGPathSegClosePath: SVGPathSegClosePath()SVGPathSegCurvetoCubicAbs: SVGPathSegCurvetoCubicAbs()SVGPathSegCurvetoCubicRel: SVGPathSegCurvetoCubicRel()SVGPathSegCurvetoCubicSmoothAbs: SVGPathSegCurvetoCubicSmoothAbs()SVGPathSegCurvetoCubicSmoothRel: SVGPathSegCurvetoCubicSmoothRel()SVGPathSegCurvetoQuadraticAbs: SVGPathSegCurvetoQuadraticAbs()SVGPathSegCurvetoQuadraticRel: SVGPathSegCurvetoQuadraticRel()SVGPathSegCurvetoQuadraticSmoothAbs: SVGPathSegCurvetoQuadraticSmoothAbs()SVGPathSegCurvetoQuadraticSmoothRel: SVGPathSegCurvetoQuadraticSmoothRel()SVGPathSegLinetoAbs: SVGPathSegLinetoAbs()SVGPathSegLinetoHorizontalAbs: SVGPathSegLinetoHorizontalAbs()SVGPathSegLinetoHorizontalRel: SVGPathSegLinetoHorizontalRel()SVGPathSegLinetoRel: SVGPathSegLinetoRel()SVGPathSegLinetoVerticalAbs: SVGPathSegLinetoVerticalAbs()SVGPathSegLinetoVerticalRel: SVGPathSegLinetoVerticalRel()SVGPathSegList: SVGPathSegList()SVGPathSegMovetoAbs: SVGPathSegMovetoAbs()SVGPathSegMovetoRel: SVGPathSegMovetoRel()SVGPatternElement: SVGPatternElement()SVGPoint: SVGPoint()SVGPointList: SVGPointList()SVGPolygonElement: SVGPolygonElement()SVGPolylineElement: SVGPolylineElement()SVGPreserveAspectRatio: SVGPreserveAspectRatio()SVGRadialGradientElement: SVGRadialGradientElement()SVGRect: SVGRect()SVGRectElement: SVGRectElement()SVGSVGElement: SVGSVGElement()SVGScriptElement: SVGScriptElement()SVGSetElement: SVGSetElement()SVGStopElement: SVGStopElement()SVGStringList: SVGStringList()SVGStyleElement: SVGStyleElement()SVGSwitchElement: SVGSwitchElement()SVGSymbolElement: SVGSymbolElement()SVGTSpanElement: SVGTSpanElement()SVGTextContentElement: SVGTextContentElement()SVGTextElement: SVGTextElement()SVGTextPathElement: SVGTextPathElement()SVGTextPositioningElement: SVGTextPositioningElement()SVGTitleElement: SVGTitleElement()SVGTransform: SVGTransform()SVGTransformList: SVGTransformList()SVGUnitTypes: SVGUnitTypes()SVGUseElement: SVGUseElement()SVGViewElement: SVGViewElement()SVGViewSpec: SVGViewSpec()SVGZoomEvent: SVGZoomEvent()Screen: Screen()ScreenOrientation: ScreenOrientation()ScriptProcessorNode: ScriptProcessorNode()SecurityPolicyViolationEvent: SecurityPolicyViolationEvent()Selection: Selection()ServiceWorker: ServiceWorker()ServiceWorkerContainer: ServiceWorkerContainer()ServiceWorkerMessageEvent: ServiceWorkerMessageEvent()ServiceWorkerRegistration: ServiceWorkerRegistration()Set: Set()ShadowRoot: ShadowRoot()SharedWorker: SharedWorker()SpeechSynthesisEvent: SpeechSynthesisEvent()SpeechSynthesisUtterance: SpeechSynthesisUtterance()Storage: Storage()StorageEvent: StorageEvent()String: String()StyleSheet: StyleSheet()StyleSheetList: StyleSheetList()SubtleCrypto: SubtleCrypto()SurfaceWorker: undefinedSymbol: Symbol()SyntaxError: SyntaxError()Text: Text()TextDecoder: TextDecoder()TextEncoder: TextEncoder()TextEvent: TextEvent()TextMetrics: TextMetrics()TextTrack: TextTrack()TextTrackCue: TextTrackCue()TextTrackCueList: TextTrackCueList()TextTrackList: TextTrackList()TimeRanges: TimeRanges()Touch: Touch()TouchEvent: TouchEvent()TouchList: TouchList()TrackEvent: TrackEvent()TransitionEvent: TransitionEvent()TreeWalker: TreeWalker()TypeError: TypeError()UIEvent: UIEvent()URIError: URIError()URL: URL()Uint8Array: Uint8Array()Uint8ClampedArray: Uint8ClampedArray()Uint16Array: Uint16Array()Uint32Array: Uint32Array()VTTCue: VTTCue()ValidityState: ValidityState()WaveShaperNode: WaveShaperNode()WeakMap: WeakMap()WeakSet: WeakSet()WebGLActiveInfo: WebGLActiveInfo()WebGLBuffer: WebGLBuffer()WebGLContextEvent: WebGLContextEvent()WebGLFramebuffer: WebGLFramebuffer()WebGLProgram: WebGLProgram()WebGLRenderbuffer: WebGLRenderbuffer()WebGLRenderingContext: WebGLRenderingContext()WebGLShader: WebGLShader()WebGLShaderPrecisionFormat: WebGLShaderPrecisionFormat()WebGLTexture: WebGLTexture()WebGLUniformLocation: WebGLUniformLocation()WebKitAnimationEvent: AnimationEvent()WebKitCSSMatrix: WebKitCSSMatrix()WebKitMutationObserver: MutationObserver()WebKitTransitionEvent: TransitionEvent()WebSocket: WebSocket()WebView: webview()WheelEvent: WheelEvent()Window: Window()Worker: Worker()XMLDocument: XMLDocument()XMLHttpRequest: XMLHttpRequest()XMLHttpRequestEventTarget: XMLHttpRequestEventTarget()XMLHttpRequestProgressEvent: XMLHttpRequestProgressEvent()XMLHttpRequestUpload: XMLHttpRequestUpload()XMLSerializer: XMLSerializer()XPathEvaluator: XPathEvaluator()XPathExpression: XPathExpression()XPathResult: XPathResult()XSLTProcessor: XSLTProcessor()_: (n)_collections: Object_ga: Object_itemDefs: Object_perkDefs: Object_raceDefs: Object_statDefs: Object_talentGridDefs: Objectactive: Objectapp: ObjectapplicationCache: ApplicationCachebungie: (cookieString, complete)caches: CacheStoragechrome: ObjectclientInformation: Navigatorclosed: falseconsole: Consolecrypto: CryptodataDir: "data"decodeURI: decodeURI()decodeURIComponent: decodeURIComponent()defaultStatus: ""defaultstatus: ""devicePixelRatio: 1document: documentencodeURI: encodeURI()encodeURIComponent: encodeURIComponent()escape: escape()eval: eval()event: undefinedexternal: ObjectframeElement: nullframes: Windowga: (a)gaGlobal: Objectgaplugins: Objectgoogle: Objecthistory: Historyhtml5: ObjectindexedDB: IDBFactoryinnerHeight: 264innerWidth: 1452isAndroid: falseisChrome: trueisFinite: isFinite()isIOS: falseisKindle: falseisMobile: falseisNWJS: falseisNaN: isNaN()isWindowsPhone: falsejQuery: (a,b)jQuery1112028061817679554224: Objectko: Objectlength: 0localStorage: Storagelocation: Locationlocationbar: BarPropmembershipId: "4611686018428399607"menubar: BarPropname: ""navigator: NavigatoroffscreenBuffering: trueopener: nullouterHeight: 1020outerWidth: 1462pageXOffset: 0pageYOffset: 0parent: WindowparseFloat: parseFloat()parseInt: parseInt()performance: Performancepersonalbar: BarPropresult: falsescreen: ScreenscreenLeft: 1898screenTop: 0screenX: 1898screenY: 0scrollX: 0scrollY: 0scrollbars: BarPropself: WindowsessionStorage: StoragespeechSynthesis: SpeechSynthesisstatus: ""statusbar: BarPropstyleMedia: StyleMediasupportsCloudSaves: truetgd: Objecttoolbar: BarProptop: Windowua: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"undefined: undefinedunescape: unescape()webkitAudioContext: AudioContext()webkitIDBCursor: IDBCursor()webkitIDBDatabase: IDBDatabase()webkitIDBFactory: IDBFactory()webkitIDBIndex: IDBIndex()webkitIDBKeyRange: IDBKeyRange()webkitIDBObjectStore: IDBObjectStore()webkitIDBRequest: IDBRequest()webkitIDBTransaction: IDBTransaction()webkitIndexedDB: IDBFactorywebkitMediaStream: MediaStream()webkitOfflineAudioContext: OfflineAudioContext()webkitRTCPeerConnection: RTCPeerConnection()webkitSpeechGrammar: SpeechGrammar()webkitSpeechGrammarList: SpeechGrammarList()webkitSpeechRecognition: SpeechRecognition()webkitSpeechRecognitionError: SpeechRecognitionError()webkitSpeechRecognitionEvent: SpeechRecognitionEvent()webkitStorageInfo: DeprecatedStorageInfowebkitURL: URL()window: Windowyepnope: (a)zam_tooltips: Object__proto__: WindowtimeStamp: 1441737559328type: "error"__proto__: ErrorEventbubbles: (...)cancelBubble: (...)cancelable: (...)colno: (...)get colno: ()constructor: ErrorEvent()currentTarget: (...)defaultPrevented: (...)error: (...)get error: ()eventPhase: (...)filename: (...)get filename: ()lineno: (...)get lineno: ()message: (...)get message: ()path: (...)returnValue: (...)srcElement: (...)target: (...)timeStamp: (...)type: (...)__proto__: Event

**Comment by Mulchman** [comment] 2015-09-08 18:41
Holy shit that copy and paste. My god, sorry.

**Comment by Mulchman** [comment] 2015-09-08 18:42
Lets try it this way:

![example](http://i.imgur.com/4gALO5W.png)

**Comment by SteffanLong** [comment] 2015-09-08 18:51
The Bungie Platform API is down. Nothing works at the moment.

**Comment by Mulchman** [comment] 2015-09-08 18:55
Ah, well now I feel dumb. Thanks for the heads up.

**Comment by SteffanLong** [comment] 2015-09-08 18:56
Well, this error appears to be a real error, but it's most likely caused by the API being down. Everyone is down at the moment. :/

**Comment by moeyjar** [comment] 2015-09-08 19:36
I would also expect major api changes for this version, so I would recommend just following this for the update :)

**Comment by fearbroner** [comment] 2015-09-09 03:09
Any idea when this API will be updated?

**Comment by SteffanLong** [comment] 2015-09-09 05:15
It has been.

**Comment by dasilva333** [comment] 2015-09-09 14:16
Fixed in 3.1.3 thanks guys

**Closed by dasilva333** 2015-09-09 14:16 UTC
