### ISSUE TITLE
Tower Ghost error: Please Sign in to Continue

### ISSUE THREAD

**Issue by abqwizard** [dasilva333/TowerGhostForDestiny#635] opened 2016-07-20 21:32 UTC
When trying to transfer items between characters, I keep getting ERROR: Please sign-in to continue. And I was already signed in. Tried restarting app, removed app and reinstalled. Updated to IOS 9.3.3 and same thing. This just started today, Wednesday 7/20/2016. Worked fine last night.

Tried on iPad, iPhone and Chrome same thing on all of them. The Firefox app seems to still work.

All are version 3.9.1.2

**Comment by daize17** [comment] 2016-07-20 21:53
I am having the same issue. Tried re-logging in multiple times, tried uninstalling the app and Chrome, and tried restarting, but continue to have the issue.

**Comment by dasilva333** [comment] 2016-07-20 22:06
Can confirm the issue as well, must be new API changes from Bungie I'll look into it thanks for the heads up

**Comment by edmiller47** [comment] 2016-07-20 23:56
Same thing happening in DIM, so most likely it's an API change relate to today's Companion update.

**Comment by MasterBry** [comment] 2016-07-21 00:35
Same problem here... All looks normal until you try to transfer anything, then says login, even when you are.

**Comment by Ziggy0011** [comment] 2016-07-21 02:24
Ditto - Chrome app looks normal but won't transfer. Uninstalled the extension and reloaded. No luck.
Love the app. Actually I'm kinda addicted to it.  :-)

**Comment by dasilva333** [comment] 2016-07-21 13:30
So it seems like DIM is working again despite no changes to their code, also TGD seems to work fine on Firefox but not on mobile/Chrome. I'll keep investigating to determine the issue, marking as help wanted if anyone wants to help

**Comment by macnode** [comment] 2016-07-21 13:45
I also have this specific issue "ERROR: Please sign-in to continue."

DIM is working for me.

**Comment by dasilva333** [comment] 2016-07-21 13:57
After further research I have concluded the problem is with Bungie actively blocking requests from unknown Origins.
It seems they changed the TransferItem API so it validates the Origin header if provided. If a value is provided it is checked against a whitelist of valid Origins.
DIM must have been added to the whitelist: "Origin:chrome-extension://apghicjnekejhfancbkahkhdckhdagna" whereas Tower Ghost is not in the whitelist:
"Origin:chrome-extension://nkplbklkoceoepkghofapmhjgidaialb". That would explain how it wasn't working between yesterday at 5 PM and it's working now without any code changes on their end.

Worthy of note is the Response header includes these two fields not provided to Tower Ghost when the request is made from DIM:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:chrome-extension://apghicjnekejhfancbkahkhdckhdagna

This is the resposne from Bungie when the request is made from Tower Ghost:
Access-Control-Allow-Origin:https://www.bungie.net

Also worth noting Firefox does not send any Origin headers and manually removing the Origin header from Chrome seems to fix the issue however pushing these changes requires me to update
the manifest and include new permissions for the app to modify the HTTP request in real time.

I messaged Bungie's Treton with a query as to what's going on hopefully I can be added to the white list to avoid any code changes on my side.

**Comment by macnode** [comment] 2016-07-21 14:10
Thanks for looking into it! If you need any testing/data Im a cloud engineer and Bungie API user, and have been using TG daily for a long time. I also helped fill in the 335 data spreadsheet a while back as I hit 335 the first day.

**Comment by dasilva333** [comment] 2016-07-21 15:04
Update from Bungie:
https://www.bungie.net/en/Clan/Post/39966/209412687/0/0

**Comment by macnode** [comment] 2016-07-21 15:42
Cool. Cause found! By the way theres a maintenance today and usually the API is down during so not a good time to test TG...

**Comment by jkewley** [comment] 2016-07-21 15:49
@dasilva333 TGD's chrome extention isn't mentioned in that thread. Did you message him directly? Don't make me use the destiny site gear manager again tonight - I won't forgive you.

**Comment by dasilva333** [comment] 2016-07-21 18:57
Yes I privately messaged them my Chrome Origin header it should be fixed soon enough, however it seems mobile will have to remain broken until I can push a workaround or until they can come up with a fix, I think i'll have a workaround sooner than their fix so expect 3.9.1.3 for mobile soon guys.

Thanks everyone

**Comment by edmiller47** [comment] 2016-07-21 20:57
TG Chrome is working again

**Comment by MasterBry** [comment] 2016-07-21 23:47
Still same error happening, after re-boot, log off and login, continues to say Must Login

**Comment by davefiley** [comment] 2016-07-22 08:02
Hi I'm on iPad using safari and suffering same issue signs in ok but as soon as I try to move anything app reports that I need to sign in.

**Comment by tonyNOS** [comment] 2016-07-22 16:30
Hi everybody. Just to report 1) my firefox plugin its ok, 2)my desktop not works

**Comment by dasilva333** [comment] 2016-07-22 17:17
As of 3.9.1.3 TGD works for iOS/Chrome/Firefox and Windows-Phone I'm still trying to figure out a way to get it working on Android again. Thanks guys

**Comment by selloutpunk** [comment] 2016-07-22 17:17
Following for updates. Tower Ghost is my go to app.

**Comment by iamlester55** [comment] 2016-07-23 03:24
Thanks for the update dasilva333 eagerly awaiting the android fix!

**Comment by grimmjoww** [comment] 2016-07-23 06:00
Hopefully it gets fixed soon miss farming

**Comment by CrazyPyro21** [comment] 2016-07-24 17:44
I'm also anxiously waiting an android fix. I love TG. I've been lost without it lately. Thanks dasilva333.

**Comment by CrazyPyro21** [comment] 2016-07-26 16:37
Any updates dasilva333?

**Comment by dasilva333** [comment] 2016-07-26 18:15
I tried it on one of my mobile android devices yesterday and it seemed to have worked, I'll try my tablet tonight and hopefully I can reproduce the problem, otherwise I won't have a device to test the problem against. *fingers crossed*

**Comment by CrazyPyro21** [comment] 2016-07-26 18:30
I just checked on my Galaxy S7 Edge, and I'm still having it.

**Comment by iamlester55** [comment] 2016-07-26 19:00
I also tried on a rooted Note 3 and a Galaxy tab S2 and still get the same error :(  I Uninstalled and reinstalled on both devices before trying.

**Comment by Harshlanguage** [comment] 2016-07-26 19:51
I have been having the issue on Amazon Fire tablet. Works fine on Windows phone.  Very frustrating.  Have to carry multiple devices to game....Just tried to uninstall and reinstall on Fire tab with no success

**Comment by krostyck** [comment] 2016-07-28 08:31
I am having the same issue. Tried re-logging in multiple times, tried uninstalling the app in Firefox, Windows 64x and Android, and tried restarting, but continue to have the issue.

**Comment by CrazyPyro21** [comment] 2016-07-29 21:33
Just wanted to check in again and let you know that I'm still unable to transfer items via tower ghost. I miss your app. Hope it's back up and running soon. Thanks.

**Comment by Mythrayn82** [comment] 2016-07-31 08:40
I LOVE your app! It makes me sad that it's not working. I've chosen to not play Destiny a few times simply because the app isn't working :'(
I've logged out and back in, uninstalled and reinstalled. Updated to latest android OS. All to no avail. It sounds like my android devices are ones not fixed yet. 
Galaxy Note 5 and Galaxy S4. 

I hope to hear good news soon! I REALLY don't want to go back to any of the other apps. Good luck in your search for answers!

**Comment by paulR3** [comment] 2016-07-31 14:23
Tower Ghost error: Please Sign in to Continue
Is. Still happening  10:31pm EST 7/31/16

**Comment by ryanhubbard69** [comment] 2016-08-02 06:28
Ok, i'm VERY patient. But waiting 2+ weeks for a bug fix? What the hell is going on!? I'm using a kindle and it STILL wants me to sign in to continue. Just... just give us a status update, what is going on.

**Comment by selloutpunk** [comment] 2016-08-02 06:32
Kindle... really..? You have bigger problems in life.

**Comment by iamlester55** [comment] 2016-08-02 07:20
@selloutpunk that is hilarious.

**Comment by ryanhubbard69** [comment] 2016-08-02 13:54
@selloutpunk what? Is there a problem with reading you un-cultured swine?

**Comment by CrazyPyro21** [comment] 2016-08-02 13:57
Well... That escalated quickly

**Comment by edmiller47** [comment] 2016-08-02 15:05
Folks - @dasilva333 stated earlier that he is working on a fix for Android, so if you've read this far, you already know that Android isn't working. No value added by posting more messages saying it doesn't work. The developer will let us all know when it's fixed as he always does.

**Comment by jkewley** [comment] 2016-08-02 15:26
I don't want to step on the toes of @dasilva333 here, but if you're a dev who is experiencing these problems it'd probably be useful to configure your device to work through a PC-based proxy such as Fiddler and capture the requests and responses. That data should be useful as he tries to get a better understanding of where things are falling apart. 

There is also an updated work around on the original thread https://www.bungie.net/en/Clan/Post/39966/209412687/0/0
which apparently fixed DIM. Might be worth a try.

**Comment by rkingsla** [comment] 2016-08-02 21:22
@ryanhubbard69 I just want to point one thing out: This isn't Microsoft, Apple, Oracle or any of the other big names that you're paying big bucks for an application and a support team. I work for a software house and we have dedicated support, engineers (who do this full time), and such. Our customers have a right to demand things from us. When you're not paying big dollars (or choose your currency), you don't have a right to bitch (frankly, you have a right to bitch regardless and I'll defend your right to do so). However, you nor I have any idea what is going on in @dasilva333 's life that might have put him off-track. Family issues? Dunno. Demands at his 'real job'? (No one believes that he's making enough off of this to make it a full-time job, do they?) Dunno.

Temper your expectations. If you choose to donate, great. Otherwise, @dasilva333 is giving this to you FOR FREE - and hence the reason that you should likely re-think 'demands' for a fix. In summary, no one was guaranteed anything.

**Comment by dasilva333** [comment] 2016-08-03 01:07
Thanks everyone for staying on top of this, so I can finally provide an update today I've got good news and bad news.

For the good news I have 2 Android devices, on the first one I'm able to login and make transfer requests without the Sign In bug, I wasn't able to test the same code on my other Android (a tablet running 4.0.4) because there was a problem with inAppBrowser that was fixed 2 weeks ago that prevented the sign in pop up from showing. So I built the code using the latest version provided with the fix, logged in, and to my surprise this device also doesn't send the Origin header. 

So for the bad news I am unable to reproduce the bug (though I know it exists because my buddy is able to reproduce it with his Android) with my two devices, I'm going to ask my other buddy @weborican if he can provide me with a test Android device I can reproduce the problem with.

As an interim solution @jkewley is not far off, if you can reproduce the bug on your device and you have knowledge with Fiddler or Charles to read the SSL-bound www.bungie.net requests for the TransferItem API all I need to know is what your device is using for an Origin header. I'm pretty sure it's dynamic based on where it's installed but I dont mind submitting to Bungie all the variations (if possible) for the time being just to get you guys up and running again.

Thanks again

**Comment by roland46** [comment] 2016-08-03 08:02
Hi,

I have the problem on a windows 10 pc.
On a Microsoft Surface windows 10.

My android phone works, no tablet to test on.

My windows phone works, I think this is on windows phone 8.1.

Not sure if this helps, but any input to help you get this solved gladly given.

I have had a look on the bungie site, but that does not appear to be much help, anything needed to help you out let me know, can try to run some trace tools, just need to know what you need.

Cheers,
Roland.

**Comment by dasilva333** [comment] 2016-08-03 13:37
Alright these instructions is for anyone receiving the 'Please Sign on to Continue' error whilst using Tower Ghost.

The gist of it is you'll set up a sniffing tool, configure it for Bungie, install the certificate on your device, and then use TGD.

Requirements
- Wifi Network
- Access to a computer
- Knowledge installing SSL certificates
- Knowledge setting up an http proxy

1. Install Charles Proxy on your computer
https://www.charlesproxy.com/download/

2. Open Charles and configure it for Bungie
Proxy > SSL Proxy Settings > Add > Host: www.bungie.net Port: *

3. Figure out the IP address of the computer you're using

4. On the device that uses Tower Ghost (Android, iOS, Win10) visit the section where you can configure the Proxy settings
iOS: Wifi > Click on the active Wifi (?) > Scroll to Proxy > Manual > Enter the IP of the computer and Port 8888
Android: Look for it under Advanced in the Wifi settings, if not available install "Proxy Settings" from the Play Store

5. On the device you're using you need to install the SSL certificate your computer generated
iOS: Open Safari, visit http://charlesproxy.com/getssl accept certificate and click Trust
Android: Try the same steps with the built in Browser, if that doesn't work install Certificate Manager and manually copy the file by downloading it from your computer

6. Open Tower Ghost and click Allow for Charles Proxy to read the traffic being routed

7. Attempt to transfer an Item and confirm you receive the error message

8. In Charles click [+] for www.bungie.net, drill down to the TransferItem request, click on the Request tab on top, click on the Headers tab at the bottom

9. Provide me with the value you see for the "Origin" header.

Good luck everyone!

**Comment by LordofthStrings** [comment] 2016-08-03 19:40
So is this just it for tower ghost  or are you working on a more convenient fix ? Because i am not familiar with pretty much anything involved in this fix lol. Also if anybody could post the phones/ tablets that ARE working with TG that would be appreciated as I am considering getting a new phone anyway.

**Comment by dasilva333** [comment] 2016-08-03 20:49
Problem can't be reproduced by the two testers who were able to previously confirm the problem was there. To everyone following this issue please retest your app and let me know if you're still having issues. If no one comes forward with the issue I'll assume Bungie ninja patched it within the last few hours and close this ticket later.

Thanks everyone

**Comment by CrazyPyro21** [comment] 2016-08-03 20:53
Just checked. Now working for me!

**Comment by LordofthStrings** [comment] 2016-08-03 21:03
Working for me as well yay!!!

**Comment by hendersj** [comment] 2016-08-03 21:37
Confirmed here as well on a Galaxy Tab S 10.5 and a Galaxy S6.

Thanks for the hard work resolving this - I was really missing farm mode last night - glad to have it back today. :)

**Comment by edmiller47** [comment] 2016-08-04 01:02
Working on my Blackberry now (yes, I have a Blackberry)...

**Comment by Mythrayn82** [comment] 2016-08-04 01:33
It seems to be working again for me too! Yay!

**Comment by iamlester55** [comment] 2016-08-04 02:33
Can confirm that the fix works in a rooted note 3 running cm12

**Comment by tonyNOS** [comment] 2016-08-04 21:56
Windows64 here, thanks god it works.

Of course thanks to dasilva too.

**Comment by grimmjoww** [comment] 2016-08-04 22:18
Did you already changed the header . App is working now

**Closed** 2016-08-05 02:01 UTC
Labels: bug, help wanted
