### ISSUE TITLE
iOS Version- Losing Icons

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#171] opened 2015-05-12 18:16 UTC
Hi -

Since I can PM you via GitHub, I figured I would file this "issue", which is more of a question. I've noticed that over the past few updates that icons are disappearing, such as my Vault and then the first 3 in the hamburger icon:

![tgfd 2-5-3](https://cloud.githubusercontent.com/assets/11835064/7594824/e646ee48-f8a8-11e4-8fdb-5d25ed8727a7.png)

Not sure if I need to grab the latest build from the website since the hydration only updates certain things? Or is this happening for other reasons?

Not a big issue since I'm familiar with the app and know what those buttons are, but not sure if it's happening for new adopters as well.

Thanks.

**Comment by dasilva333** [comment] 2015-05-12 19:47
Yeah I noticed that happened to me too a few times when I created a new hydrated build I'll have to investigate the cause and figure out if it's something I need to fix. Thanks

**Comment by dasilva333** [comment] 2015-05-13 16:59
@chrisdudek can you confirm a few things for me:
- are you jailbroken or flight test?
- what is the version number you are using?
- have you tried uninstalling and reinstalling?

Let me know thanks

**Comment by chrisdudek** [comment] 2015-05-13 17:13
Not Jailbroken. Gave you my UDID. 

Version 2.5.4

Not yet

**Comment by dasilva333** [comment] 2015-05-13 17:23
It could be a corrupted hydra update i've seen on windows phone where a hydra update messed up the javascript files perhaps on ios it messes up the graphics file. Try doing a reinstall just hold the icon, press X on the springboard and reinstall it via the FlightTest app and let me know how it goes. Thanks man

**Comment by chrisdudek** [comment] 2015-05-13 17:30
Thanks. I just submitted a request to join the TestFlight app. After that I am assuming it should show up in my TestFlight app.

**Comment by dasilva333** [comment] 2015-05-13 17:33
Oh I see sorry I misunderstood, if your not jailbroken and you gave me your UDID then I understand exactly what the problem is and I'll get it fixed by tonight, basically you used this IPA: 
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny.ipa

I've noticed the images are broken on that install package but not on this one:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestinyAppStore.ipa

However you can't install that one because it's not set up for Adhoc distribution so I'll fix by updating the binary to 2.5.4 Hydrated IPA. Thanks

**Comment by chrisdudek** [comment] 2015-05-13 17:35
No worries. I already deleted the app so I'll redownload it whenever I get back home. Thanks for looking into this!

**Comment by dasilva333** [comment] 2015-05-13 22:36
Closing out this ticket the app is now available in the App Store :)
http://www.reddit.com/r/DestinyTheGame/comments/35vpsl/discussion_tower_ghost_for_destiny_now_available/

**Closed by dasilva333** 2015-05-13 22:36 UTC
Labels: bug
