### ISSUE TITLE
Can't transfer heavy weapons to vault if in loadout

### ISSUE THREAD

**Issue by MrShanktastic** [dasilva333/TowerGhostForDestiny#478] opened 2015-11-27 21:47 UTC
Everything seems to work great other than it won't let me move any heavy weapons to the vault when they are in a loadout. I can transfer them if I click them individually.

I've tested on a loadout with just 1 heavy weapon, when clicking the loadout, and then the vault it doesn't pop the dialog box. If I click another character the box does come up.

Special and Primary weapons in a loadout including heavies transfer fine.

**Comment by dasilva333** [comment] 2015-11-27 23:56
I can't seem to reproduce the problem, I tried using multi select and loadouts, both from character to vault and vault to character. Could you please provide some sort of animation video/gif of the issue in action so I can try to reproduce it? You can try www.screencast-o-matic.com/ if you like. Thanks

**Comment by MrShanktastic** [comment] 2015-12-03 20:57
Hey - i've recorded a video of the issue here: http://youtu.be/YOvZ1iUheXs?hd=1
Hope this helps..!

**Comment by dasilva333** [comment] 2015-12-04 16:40
@MrShanktastic thanks for the video I got up to 2:10 where you tried xfering the heavy to vault and nothing happened. In that situation could you press F12 on Chrome, visit the console tab and provide me with any error logs displayed in that screen? I'll be attempting to reproduce/fix this issue today thanks for the video I find it helpful

**Comment by dasilva333** [comment] 2015-12-06 19:50
@MrShanktastic I fixed a whole bunch of transfer bugs between 9 days ago and today, let me know if you're still having an issue and I'll reopen it so we can look into it further. Thanks

**Comment by MrShanktastic** [comment] 2015-12-07 15:30
Hey, sorry, I can't get on very often to update.

Issue is still occurring:
- Vault is not full (it's practically empty and I can move the weapons individually to the vault)
- Pressing F12 to bring up the developer console the only thing it says in there is:
"Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/cordova.js"
- I've also tried this on a completely different system (mac instead of PC) and exactly the same issue occurs
- I've tried the android app, same issue occurs

**Comment by dasilva333** [comment] 2015-12-07 16:09
@MrShanktastic thanks for the info 

-Vault is not full: okay good we can rule out that issue then
-Pressing F12: Make sure it's open and you're watching it when the problem happens not when the page initially loads, the cordova.js error is normal, what I need to see is any errors that come up when youre having problems with the app (if nothing shows up there while youre still able to reproduce the problem let me know)
-Im glad you tried on a different systems and android it's def a real bug then
-Did you test it on your pc/android/different system  using 3.6.7.x or below?

I still can't reproduce the issue, I tried making loadouts, using multi/select and individually transferring heavy from char to char and char to vault and vault to char. No luck

**Comment by MrShanktastic** [comment] 2015-12-09 20:59
Hey,
I recorded another video with the console showing here:
http://youtu.be/pNZdH581sk4?hd=1

This time I got some additional errors but these are there from the start, I launched a fresh browser afterwards with console showing and got the same error FILE_NOT_FOUND..

The different systems were using the latest version at that time, I downloaded simply to test.
Just tried again on android (app version 3.6.7.0) and got the same behavior (ie, clicking V after selecting my heavy weapons set doesn't do anything). Clicking another char brings up the transfer box.

**Comment by MrShanktastic** [comment] 2015-12-09 21:05
I recorded another video here: http://youtu.be/tDb1xtaxzAs?hd=1
1) Making a loadout with a non heavy weapon, and transferring to vault. Correctly triggers the transfer weapon box.
2) Making a loadout with one heavy weapon, and transferring to vault. Same issue occurs. Console on screen.

Hope this helps

**Comment by dasilva333** [comment] 2015-12-09 21:09
@MrShanktastic thanks for the fantastic video once again that shows exactly what I needed to see. Unfortunately what I see is that despite being on the latest version (3.6.8.5) and despite transferring a loadout to the vault there is no console errors regarding the problem. It's very strange that I can't see a problem. If you don't mind could you provide me a video of the same set of steps except:

1. In Chrome make sure you're on the latest (3.6.8.5)
2. Change the Chrome URL to include ?debug so from this:
chrome-extension://nkplbklkoceoepkghofapmhjgidaialb/www/index.html
to this:
chrome-extension://nkplbklkoceoepkghofapmhjgidaialb/www/index.html?debug
3. Rerun the test with your heavy to vault, leave your console open when you hit vault
4. Copy and paste all the debug output provided to www.pastebin.com
5. Provide it here so I can try to figure out the problem

Thanks!

**Comment by MrShanktastic** [comment] 2015-12-13 20:34
Log on pastebin here:http://pastebin.com/kEwBRKix
Video of the test I did here: http://youtu.be/8UNLyAf3Mwk?hd=1

Nothing extra comes up in the console when clicking Vault, whereas it does when clicking other chars. It's like the button isn't triggering anything to happen at all. On the latest version 3.6.9.6 on this one.

**Comment by dasilva333** [comment] 2016-01-04 21:37
@MrShanktastic I made some good progress with transfers, if you dont mind testing version 3.7.6.5 try it out and let me know if you have problems with it. I think this fix should def resolve the problem you were having with heavy. I think the problem turned out the fact that you didn't already have heavy in the vault so the loadouts was getting hung up when an existing item of that type isn't already there.

**Comment by dasilva333** [comment] 2016-01-12 16:56
@MrShanktastic no response for over a week, I'm going to assume it's been fixed. Let me know otherwise so I can reopen this ticket.

**Closed by dasilva333** 2016-01-12 16:56 UTC
Labels: bug, help wanted

**Comment by MrShanktastic** [comment] 2016-01-18 11:27
Hey, sorry for the delay. I've tested this just now and all working. Thanks for resolving  :)
