### ISSUE TITLE
Closing Help Topics

### ISSUE THREAD

**Issue by DogBeatr** [dasilva333/TowerGhostForDestiny#443] opened 2015-10-25 07:36 UTC
How do you close the loaded help pages?  I can't find anyway other than closing the app and reopening every time I want to return to the help contents. Example:  choose help menu in the app and it opens the topic on the reddit page but there isn't a way to close that page and go back to the contents page which you can close. I use the iOS mobile version.

**Comment by dasilva333** [comment] 2015-10-26 14:09
There is an x on the top right corner of the Help pop up, also tapping anywhere on the pop up should close it, same goes for any other pop up like Donate or About. Please provide your device and ios version. Thanks

**Comment by DogBeatr** [comment] 2015-10-27 21:15
Yes the x on the menu I saw and I've tried just tapping once to close the reddit page pop ups. Running iOS 8 on iPad and the current version of tower ghost. I'll try tapping again later when I use the app. No biggie it was more a suggestion if there wasn't an option to close the reddit redirects.

**Comment by lightmaster** [comment] 2015-10-27 22:00
I can confirm that on Android, you cannot get back from the Reddit help pages to TGfD. While there is a working X on the help popup, there is no X that I can find on the Reddit pages, and pressing back a couple times ends up closing the app entirely.

https://drive.google.com/file/d/0By3gPSdtZt2lYTdGMTlVVEZsems/view?usp=docslist_api

**Comment by dasilva333** [comment] 2015-10-28 15:00
Thanks guys I'll improve the interface so that opening the Help Guides allows the user to return to the app easily. @lightmaster can you confirm if the problem is only on Android or does it exhibit itself in iOS too? Thanks again

**Comment by lightmaster** [comment] 2015-10-28 17:56
I've only got an Android phone, so no way of checking iOS for me

**Comment by DogBeatr** [comment] 2015-10-29 01:23
It happens in iOS too.

**Comment by dasilva333** [comment] 2015-10-30 18:30
problem fixed in 3.4.8 not yet available for mobile, please confirm once it's available thanks guys

**Closed by dasilva333** 2015-10-30 18:30 UTC
Labels: bug
