### ISSUE TITLE
Landscape Mode layout too small on  iOS (Phone 6) 3.4.7

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#450] opened 2015-10-28 14:00 UTC
Hi 

3.4.7 (debug version) on iPhone 6 (iOS8) has a width problem (too small) on landscape mode. 
![img_2114](https://cloud.githubusercontent.com/assets/5049663/10790507/f7ecdff8-7d83-11e5-81fd-2a5bcdc637c6.PNG)

As View Options I use the default with 4 columns
![img_2115](https://cloud.githubusercontent.com/assets/5049663/10790548/34655c08-7d84-11e5-8a2d-89b09189d711.PNG)
 
But it make no differents for the outer width when i change the configuration. Same problem for all configurations.

![img_2116](https://cloud.githubusercontent.com/assets/5049663/10790572/56b3a9c2-7d84-11e5-9632-ec0e7493713e.PNG)

![img_2117](https://cloud.githubusercontent.com/assets/5049663/10790573/599fe8bc-7d84-11e5-83eb-1b05cc1f624b.PNG)

**Comment by dasilva333** [comment] 2015-10-28 14:59
When SM is set to 4 on landscape for mobile it should properly fit 4 columns. I tested it on my phone ios 8 iPhone 5s and I'm able to reproduce the problem so this should be an easy fix. Thanks for letting me know

**Comment by mistral13** [comment] 2015-10-28 15:25
Hi 

I think i found the solution now, its the default (out of the box) configuration. 
On second image you can see, there is nothing set vor MD (and LG).
My iPhone 6 on landscape for mobile use the MD (not SM).
When MD is set to 1,2, 3, or 4 it fit.

**Comment by dasilva333** [comment] 2015-10-28 16:02
Oh I see, thank you I understand the problem now, I actually couldn't reproduce the problem I just thought I could but your information really helps @mistral13 I didn't notice in that screenshot that md and lg have no columns selected. So to clarify you're saying that by default out of the box fresh install those values are unselected and it's until you manually set it to any value that it starts to look right?

**Comment by mistral13** [comment] 2015-10-28 17:35
exactly

**Comment by dasilva333** [comment] 2015-10-29 14:15
problem fixed as of 3.4.8, it doesn't happen on a fresh install. the reason you see columns unselected for md/lg is because there wasn't any code to handle the migration from the old system to the new system. If the user never adjusted the view options between 3.4.6 and 3.4.7 there won't be an issue but if you use 3.4.6 or below and adjust the view options it will break the layout on 3.4.7 but not 3.4.8. Thanks guys for the bug report

**Closed by dasilva333** 2015-10-29 14:15 UTC
Labels: bug
