### ISSUE TITLE
boxes too small and dead areas issue on latest updates

### ISSUE THREAD

**Issue by lllgurulll** [dasilva333/TowerGhostForDestiny#214] opened 2015-05-21 05:31 UTC
Your most recent version updates have made this app unusable for me.  The icons are too small and the numbers overlaying them too large.  I can't tell what I am clicking on because of this. 

There is also an issue in that the items I click on won't do anything. Its almost as if the touchscreen programming for the app is broken. Some areas work yet others don't. This only happens in your app and none of my other apps have this issue.  Also this is an issue on two different devices a phone and a tablet. 

I'll try to include a screenshot of what 2.1.4 looked like and what 2.6.1 currently looks like.

**Comment by lllgurulll** [comment] 2015-05-21 05:32
http://imgur.com/0CB5WH8
http://imgur.com/1XN1CkN

**Comment by lllgurulll** [comment] 2015-05-21 05:33
Top one is 2.1.4. Bottom is the current unusable version.

**Comment by dasilva333** [comment] 2015-05-21 10:28
Please provide your device type, also is landscape good for you? I'll take care of this with issue #172
Thanks

**Comment by lllgurulll** [comment] 2015-05-21 11:15
Phone is an LG G2 for att.  Tablet is Samsung galaxy note 10.1 2014
edition.
Landscape makes no difference in sizing on the phone.

**Comment by lllgurulll** [comment] 2015-05-21 11:17
Also the dead screen exists on both in portrait and landscape.

**Comment by M3Rocket** [comment] 2015-05-21 18:23
The top photo is single column, the bottom photo is two column. The problem is simple! Just post your preferences for your phone in issue https://github.com/dasilva333/TowerGhostForDestiny/issues/172. (Click on the number to get to the other issue)

**Comment by lllgurulll** [comment] 2015-05-21 21:05
I replied but I also see everyone wanting multi column.  On a phone that is
th ok much and makes the icons too small as you see in my photos, keep. It
simple, the app doesn't need to do everything.

**Comment by M3Rocket** [comment] 2015-05-21 21:16
No worries--I think there is a solution to please everyone on that front here in issue https://github.com/dasilva333/TowerGhostForDestiny/issues/174

**Comment by lllgurulll** [comment] 2015-05-21 21:26
Nothing in that thread really addresses the dead screen issue I pointed out
in y submission.

The app needs to default to single column regardless.  Making things
smaller is not a good option on phones.  Large icons are neccessary.

**Comment by dasilva333** [comment] 2015-05-21 21:30
@lllgurulll I dont really understand or can reproduce this issue, perhaps you could explain it in a way that I would be able to notice or get the problem to activate? Thanks

**Comment by lllgurulll** [comment] 2015-05-21 22:48
I upgraded to your 2.6.2 and the dead screen issue seems to have been
fixed.

Basically I would try to select an item and it just wouldn't let me select
it.  Some items would respond while others would not.  It was inconsistent
with previous versions.

**Comment by dasilva333** [comment] 2015-05-27 22:28
@lllgurulll try 2.6.5 it has the ability to manually set the number of columns I'm closing this out. I cannot reproduce the item click issue

**Closed by dasilva333** 2015-05-27 22:28 UTC

**Comment by dasilva333** [comment] 2015-06-16 19:04
@lllgurulll hey i was able to reproduce the 'dead screen' issue thanks for reporting it i found it a few days ago and was surprised you're the only one who ever mentioned it as a problem. thanks again

**Comment by lllgurulll** [comment] 2015-06-16 22:35
Glad to hear you have discovered the issue.  I figured I would just have to
live with it.  Having the bigger boxes back made a big difference though.
When do you expect to have a fix for the issue?  Or did you already?

**Comment by dasilva333** [comment] 2015-06-17 01:04
Coming out 2.7.3
