### ISSUE TITLE
Incorrect swap logic in loadout

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#31] opened 2015-04-15 10:35 UTC
Tested on version 1.8.1 on Chrome. 

Take a look at this example.
Here are target characters:
![screenshot_2015 04 15_11h14m19s_020_](https://cloud.githubusercontent.com/assets/11790750/7156208/f21e2fe6-e364-11e4-9480-8377d151960d.png)
I created loadout:
![screenshot_2015 04 15_11h14m29s_021_](https://cloud.githubusercontent.com/assets/11790750/7156245/4ee06f14-e365-11e4-80bf-955e9a2ae300.png)
Scenario 1:
When I click on my third character (the green one) nothing happen. "Transfer Confirm" dialog doesn't appear. 
In this case "Transfer Confirm" dialog should appear with 1 item to swap. 

Scenario 2:
When I click on my second character (the pink one) I get:
![screenshot_2015 04 15_11h14m45s_022_](https://cloud.githubusercontent.com/assets/11790750/7156288/9c1fed36-e365-11e4-9f04-40e4e06b6acb.png)
This is incorrect because only 3 items should be swapped, not 6. 
This is the result after transfer:
![screenshot_2015 04 15_11h16m35s_023_](https://cloud.githubusercontent.com/assets/11790750/7156380/76e3035e-e366-11e4-8a4e-7fc7eac0a21c.png)

**Comment by dasilva333** [comment] 2015-04-15 14:58
Hey @Titus-s titus thanks for following up on the loadouts there is two things you said I'd like to address:

1." When I click on my third character (the green one) nothing happen. "Transfer Confirm" dialog doesn't appear. "
If this is happening to you that means the transfer is crashing for you, I'll try to reproduce it and see if I can catch the bug and fix it, otherwise if you could provide me debug logs. Visit Chrome, press F12, go to console, reproduce the problem and copy & paste any errors to this thread

2. " This is incorrect because only 3 items should be swapped, not 6. "
The way the logic is supposed to work is all or nothing, so your loadout has 6 items, your target bucket has 6 items 6 + 6 = 12 which will make you full if I do a simple transfer for them all, the code isn't going to split the difference and transfer some and swap others so that's why you see it swaps all 6 items. If you were to have 6 items in your bucket and create a loadout with 3 items it'll do a simple transfer in that situation because 6 + 3 = 9 which wouldn't make you full. Hope that clears it up for you.

Thanks

**Comment by Titus-s** [comment] 2015-04-16 10:11
Ad 1. I get error: 
TypeError: Cannot read property 'description' of undefined   loadouts.js:221

Ad 2. I hoped that it will work in the way:
Variables:
MaxInBucket = 9 (max number of items in bucket after transfer/swap - we don't wan't to fulfill bucket so it is 9)
ItemInTargetBucket - number of items in target bucket
ItemInLoadout - number of items in loadout for specific bucket (Primary, Special, Heavy ect.)
ItemsToSwap - number of items to swap
ItemsToTransfer - number of items to transfer

Logic:
If ItemInTargetBucket = 10 then display error "No slots available to transfer item" and finish
ItemToSwap = ItemInTargetBucket + ItemInLoadout - MaxInBucket 
If ItemToSwap < 0 then ItemToSwap = 0
ItemsToTransfer = ItemInLoadout - ItemToSwap
then swap ItemToSwap and transfer ItemsToTransfer 

To be true, I don't understand "the code isn't going to split the difference" - in code you can do everything :), but I know it can be hard to do.
So, if it's too hard / impossible to implement you can skip it

**Comment by dasilva333** [comment] 2015-04-16 11:49
Thanks for your feedback:
1. Regarding this error you can make it happen every time you transfer to your third character no matter what or is there something more specific you have to do to make it crash (have the dialog not show)

2. It's really simple the loadouts was built around the one truth that 10 items means you're full assuming loadouts only apply to characters and not vaults, once start trying to apply loadouts to the vault the static 10 has to become a variable 10 or 24 or 36 depending on which bucket it is. That's all there is to it really. 

Lastly to clarify the statement regarding splitting the difference if you have this condition:
iteminTargetBucket = 6 (and targetBucket is a normal character not the vault)
itemsInLoadout = 6
(assuming all items are part of the same bucket, lets say Primary)
the result would be 
itemsToSwap = 6
itemsToTransfer = 0
Splitting the difference would result in something like this:
itemsToSwap = 3
itemsToTransfer = 3

The app is not going to do that so expect it always to swap those 6.

**Comment by dasilva333** [comment] 2015-04-16 16:08
playing with cloud load out:
“Uncaught TypeError: Cannot read property 'equip' of undefined”
 app.js:245

**Comment by Titus-s** [comment] 2015-04-17 12:47
Tested on version 1.8.4 with reduced definitions on chrome
Ad 1. I've try to reproduce issue with transfer loadout using primary weapon. 
There is regularity in items number in target bucket and loadout when dialog not show. 
Please take a look at table:
![image](https://cloud.githubusercontent.com/assets/11790750/7202187/472c01dc-e510-11e4-8005-994e09579574.png)
Notice, that all items in loadout were in Vault. 
Hope it helps.

**Comment by AAraKKe** [comment] 2015-04-17 21:16
Sorry to come here and comment but I just wanted to point out what I said in #50 , since I see that this thread talks abou tproblems when transferring, it is a little bit different. In the issue I posted the problem was that I couldn't create a loadout with materials, it didin't matter what material I picked to include it always included the same (in my case Plasteel). I looked more to me like an interface error than an architecture error. Just to let you what I saw.

**Comment by dasilva333** [comment] 2015-04-18 01:14
@Titus-s thank you for coming through on that chart man I just looked at your comment and within 10 minutes I fixed the bug and managed to reproduce it, it's people like you who keep the world moving. In my experience the 8 / 9 scenario did not work for me but then I tried the 4/6 scenario and I realized why it's a problem. Expect the fix in the next version

**Comment by dasilva333** [comment] 2015-04-18 16:31
I finally managed to tackle the last part of the loadout bugs. The new logic says maxBucketSIze is 10 unless I'm transferring to the vault at which point it's 36 otherwise it's 24 for general/armor. Expect to see the fix in 1.9.6 thanks

**Comment by Titus-s** [comment] 2015-04-18 17:03
Works great. Unfortunately today I found (hope last) bug:
Precondition:
You are in battle (important) and have equipped Exotic Heavy weapon
To simplify in loadout have first exotic Primary weapon set to equip, and second - legendary Special

When you click in loadout to move on the character that is in battle loadout stop working on first item. Probably because it can't equip another heavy weapon (you are in battle) and then equip exotic Primary. 
Can you handle this behavior and skip step if it can't equip weapon (just store) and continue next steps?

Can you also add some progression in loadout? It would be useful in larger loadout. 

Thanks once again for your great work. I fully recommend this app to all my friends and encourage to use it.

**Comment by dasilva333** [comment] 2015-04-18 17:06
I'm not going to change the logic for it to continue if something fails. It's too risky to allow the app to run wild and free despite something has failed. As for the progression that's a good idea thanks.

**Closed** 2015-04-18 17:07 UTC
Labels: bug
