### ISSUE TITLE
3.9.0.10 Item Transfer Getting Stuck

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#620] opened 2016-06-10 13:33 UTC
I am constantly having this issue trying to move a loadout on version 3.9.0.10. It gets like half-way and then constantly shows the blue refresh icons on the right and doesn't move anything else. I have to completely refresh the page and re-transfer that loadout and it will typically complete.

Just looking at the image, perhaps it's because it's trying to transfer a gunsmith pkg.
![image](https://cloud.githubusercontent.com/assets/2903357/15965876/5ffc6e8a-2eee-11e6-93dc-5fee1e59c3f2.png)

**Comment by rkingsla** [comment] 2016-06-10 13:52
From what I gather with other tools (Guardian GG, DestinyTracker) Bungie has done a great job on doing an update to their systems. Well, except for the fact that the API seems to be lagging well behind. IOW, tools like TGD and other interfaces using the Destiny Bungie API aren't working correctly. I suspect that this is the reason why things aren't transferring.

**Comment by pattont** [comment] 2016-06-10 14:02
They are in-fact transferring, but it gets stuck refreshing. I then refresh the entire page and re-do the transfer and it's fine.

**Comment by dasilva333** [comment] 2016-06-10 20:12
Ill try a couple of examples with a variety of cases with guns and a ghost and see if I have any issues. I know the Bungie server's have been problematic lately and my transfer code depends on Bungie's server to reliably update when asked to refresh, I know that if the server is caching a certain item somewhere even though it's been moved it can cause real problems with the transfer code. Anyhow I'll check it out thanks for the heads up

**Comment by pattont** [comment] 2016-06-11 14:20
Ever since I have manually swapped out any gunsmith orders from the
transfer attempt there has been no issue. Perhaps you can exempt those from
the transfer algorithm and it should be fine.

**Comment by dasilva333** [comment] 2016-06-15 14:25
Good catch guys, that was a tricky bug to find and I thank you all for helping me figure out this problem. I changed the transfer algorithm to only consider Equippable guns when unequipping a gun therefore preventing any Armsday Orders from trying to get equip and mess up the transfers. It should be ready as of 3.9.1.1 I'll let you guys know when it's available to try out. Thanks again

**Comment by dasilva333** [comment] 2016-06-22 20:04
@pattont can you confirm if the problem is still present as of 3.9.1.1? Let me know thanks!

**Comment by pattont** [comment] 2016-06-23 04:26
Confirmed - resolved

You also resolved another issue I was about to post about and that was
weirdness with transferring items between characters by clicking on them
with Chrome for Mac. The character box wouldn't come up and I was forced to
drag them. It didn't happen on Chrome for Windows, but it appears resolved.
Will keep my eye out for any thing else.


Thanks for the great work!!


Travis

**Closed** 2016-06-24 14:15 UTC
Labels: bug
