### ISSUE TITLE
Saved loadouts equipped weapon checkbox behavior

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#69] opened 2015-04-19 15:30 UTC
Seems like previously saved loadouts are having issues with the equipped weapon checkbox. If I open a previously saved loadout in the latest version (1.9.8) on Chrome I sometimes see either multiple checkboxes for weapons in the same category (primary, special, heavy), or none checked at all. When I try to uncheck them (either by clicking on the checkbox, or another checkbox for a weapon in the same category) it doesn't work. Along these lines, clicking on the checkboxes of weapons in my loadout doesn't cycle ALL the checkboxes of the other weapons in the same category.
![screen shot 2015-04-19 at 10 29 27 am](https://cloud.githubusercontent.com/assets/12019978/7220011/1296702c-e67f-11e4-9046-25f6ae18ef75.png)
![screen shot 2015-04-19 at 10 29 44 am](https://cloud.githubusercontent.com/assets/12019978/7220013/15f41972-e67f-11e4-81fc-a2597f677f50.png)
![screen shot 2015-04-19 at 10 29 54 am](https://cloud.githubusercontent.com/assets/12019978/7220014/185a8462-e67f-11e4-9690-3f4249f35cbd.png)

**Comment by dasilva333** [comment] 2015-04-19 22:58
Problem noticed expect a fix in 2.0.0 thanks

**Comment by weborican** [comment] 2015-04-20 02:15
Thanks, but the problem still exists in 2.0.0 :-(

**Comment by dasilva333** [comment] 2015-04-22 17:09
@weborican I haven't been able to reproduce or recreate the problem you're seeing can you walk me through the step by steps you're doing and what you're seeing. I know you provided me a pretty detailed report previously but it's not much help, here's the steps I'm taking:

1. load app
2. click on loadouts > click on any loadout that has stuff checked
3. verify stuff is properly checked
4. open more loadouts randomly indifferent times to see a problem with the checks
5. check and uncheck stuff to see if that's a problem

cannot see it at all, also check to see if u have any debug error messages in your console (for Chrome it's F12 and then the console tab)

Thanks

**Comment by weborican** [comment] 2015-04-22 20:42
No console errors. Here is what happens when I open a loadout created with an older version (back when it was DIV I believe):

![tgd_checkbox_bug](https://cloud.githubusercontent.com/assets/12019978/7284874/0e936e56-e906-11e4-957d-55595f75df74.gif)

**Comment by dasilva333** [comment] 2015-04-22 23:32
hey man so I created a debug build under the div-mobile-dist branch you can find the file here:
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tower_ghost.zip

Try it out I made some benign changes and cleaned stuff up, I couldn't reproduce the issue but I hope this at least sheds some light on what's going on so run it with console on and reproduce the bug and report back to me what the debug output said.

Thanks!

**Comment by weborican** [comment] 2015-04-23 00:25
Can’t get it to run locally:

> Uncaught TypeError: Cannot read property 'getAll' of undefined_getAllCookies @ bungie.js:41_getCookie @ bungie.js:62_getToken @ bungie.js:79_request @ bungie.js:117user @ bungie.js:158app.loadData @ app.js:1024(anonymous function) @ app.js:1255


-Luis

**Comment by weborican** [comment] 2015-04-23 00:30
Nevermind, I’m an idiot. Working now :-)

Will send back info shortly.


-Luis

**Comment by weborican** [comment] 2015-04-23 00:40
OK, here are the results:

> true
> loadouts.js:64 checked
> loadouts.js:66 is Oversoul Edict the only equipped: Primary
> loadouts.js:68 removing [{"bucketType":"Primary","_id":"6917529045201540483"}]
> loadouts.js:71 equipping Oversoul Edict
> loadouts.js:62 true
> loadouts.js:64 checked
> loadouts.js:66 is Fang of Ir YÃ»t the only equipped: Primary
> loadouts.js:68 removing [{"bucketType":"Primary","_id":"6917529042732942928"}]
> loadouts.js:71 equipping Fang of Ir YÃ»t
> loadouts.js:62 true
> loadouts.js:64 checked
> loadouts.js:66 is Fatebringer the only equipped: Primary
> loadouts.js:68 removing [{"bucketType":"Primary","_id":"6917529043129828337"}]
> loadouts.js:71 equipping Fatebringer
> loadouts.js:62 true
> loadouts.js:64 checked
> loadouts.js:66 is Found Verdict the only equipped: Special
> loadouts.js:68 removing [{"bucketType":"Special","_id":"6917529041498269568"}]
> loadouts.js:71 equipping Found Verdict
> loadouts.js:62 true
> loadouts.js:64 checked
> loadouts.js:66 is Two To The Morgue the only equipped: Special
> loadouts.js:68 removing [{"bucketType":"Special","_id":"6917529047088002511"}]
> loadouts.js:71 equipping Two To The Morgue
> loadouts.js:62 true
> loadouts.js:64 checked
> loadouts.js:66 is Oversoul Edict the only equipped: Primary
> loadouts.js:68 removing [{"bucketType":"Primary","_id":"6917529045201540483"}]
> loadouts.js:71 equipping Oversoul Edict


I don’t see anything here that helps us :-(

Basically it is seeing both the Oversoul Edict and the Fang of Ir Yut as primaries, but not the Fatebringer (so checking either of the first two does not uncheck Fatebringer).

Same goes for Two To The Morgue and Found Verdict (checking one does not uncheck the other).


-Luis

**Comment by dasilva333** [comment] 2015-04-23 00:58
Thanks for the results the mystery still remains however. I'll figure it out I'm sure if it's happening for you it's also happening for other people.

**Comment by weborican** [comment] 2015-04-23 02:11
I suspect the issue is on the saved data, creating an edge-case condition you are not accounting for in your code. Any way to see the data for the saved loadout?

**Comment by dasilva333** [comment] 2015-04-23 10:31
yeah try to provide it for me maybe it'll shed light on what's going on, to output it just type this:
JSON.stringify(app.loadouts()) and don't work it doesn't have any personally identifiable information

**Comment by weborican** [comment] 2015-04-23 12:12
Where do I type this in?

**Comment by Titus-s** [comment] 2015-04-23 12:35
Press F12, type it in console and press Enter :)

**Comment by weborican** [comment] 2015-04-23 13:12
"[{"name":"Old Faithful","ids":["6917529043736779985","6917529042732942928","6917529043129828337","6917529041390347272","6917529045705241244","6917529045477411473","6917529046079800638","6917529041359488769","6917529040231443897","6917529044702469183","6917529046667087210","6917529042425188112","6917529045181953943","6917529042330903462","6917529047088004721","6917529046289857945"],"equipIds":[{"bucketType":"Heavy","_id":"6917529042330903462"},{"bucketType":"Special","_id":"6917529042425188112"},{"bucketType":"Primary","_id":"6917529045477411473"}]},{"name":"Arc Burn","ids":["6917529042732942928","6917529045201540483","6917529043129828337","6917529046667087210","6917529041498269568","6917529042306172315","6917529045181953943","6917529041708427054","6917529042235339896","6917529047088002511"],"equipIds":[{"bucketType":"Subclasses","_id":"6917529037500672201"},{"bucketType":"Primary","_id":"6917529045201540483"},{"bucketType":"Heavy","_id":"6917529041708427054"},{"bucketType":"Special","_id":"6917529047088002511"}]},{"name":"Crucible Weapons","ids":["6917529045705241244","6917529046079800638","6917529044702469183","6917529041498269568","6917529045181953943","6917529046289857945","6917529047088004721","6917529047591919750"],"equipIds":[{"bucketType":"Helmet","_id":"6917529045700704504"},{"bucketType":"Gauntlet","_id":"6917529045016328933"},{"bucketType":"Chest","_id":"6917529044291671935"},{"bucketType":"Boots","_id":"6917529045014415777"},{"bucketType":"Heavy","_id":"6917529046289857945"},{"bucketType":"Primary","_id":"6917529046079800638"},{"bucketType":"Special","_id":"6917529045181953943"}]},{"name":"Test","ids":["6917529045705241244","6917529045477411473","6917529043129828337","6917529040301701723","6917529047279947184","6917529041498269568","6917529042425188112","6917529040231443897","6917529047579921945","6917529044474810469","6917529047278152225","6917529046289857945","6917529042991284857","6917529043738607785","6917529039432018935","6917529039493376931","6917529043899098711"],"equipIds":[{"bucketType":"Heavy","_id":"6917529046289857945"},{"bucketType":"Primary","_id":"6917529043129828337"},{"bucketType":"Special","_id":"6917529041498269568"}]},{"name":"Void Burn","ids":["6917529046620248897","6917529045291589755","6917529044702469183","6917529042330903462","6917529047447484734"],"equipIds":[{"bucketType":"Primary","_id":"6917529046620248897"},{"bucketType":"Special","_id":"6917529045291589755"},{"bucketType":"Heavy","_id":"6917529047447484734"}]}]"

**Comment by dasilva333** [comment] 2015-04-23 13:30
Something weird that stands out in the data:
good:
-bucket types in equipIds is unique and not repeated
-ids are also unique and not repeated 
bad:
The loadout Arc Burn and Crucible Weapons has some inconsistencies to it:
Arc Burn has a sub class marked as equipped that's not actually part of the loadouts (I'm not sure if you're arc burn actually has a subclass equipped I'm trying to say that the id for that subclass item is in the list of things to equip but not in the list of things in the loadout)
Crucible Weapons: Helmet, Gaunlet, Chest, Boots theres 4 items that are marked as 'to equip' that dont actually exist in that loadout anymore.

Maybe this is the source of the problem? I'll let you know thanks

**Comment by weborican** [comment] 2015-04-23 14:35
I noticed that too. Subclass and armor were initially added to the loadout, but were later deleted since it was equipping Titan armor to my Warlock. Not sure why they have stuck around, but this was done on a much earlier version - pre TGD.

**Comment by pattont** [comment] 2015-04-24 01:04
I guess I have a similar issue with the load outs and I will try to explain with an example:

Loadout - Main Weapons - Includes my primary, secondary, and heavy along with a couple of non-equipped guns. The main ones (one for each slot) are checked. 

Loadout 2 - Arc - Includes my arc primary, secondary, and heavy along with a couple of others.

The problem is that if I open up "Main" weapons which includes Fang of Ir Yut (equipped) and Fatebringer (non-equipped) everything is fine. If I then close that loadout and look at my "Arc" load out where I want Fatebringer equipped, it's unchecked and Fang is checked just like in "Main". If I make the change to eqip Fatebringer and unequip Fang it does the same for the "Main" loadout which shouldn't be happening. 

I would imagine and this is how I want it as well is that load outs are completely independent of each other so that I can chose the guns I want equipped and which ones are just transferred.

**Comment by weborican** [comment] 2015-04-24 02:17
Hmmmm, starting to see a pattern here with that crazy Fang of Ir Yut and it's crazy u-circumflex:

http://en.wikipedia.org/wiki/%C3%9B

**Comment by dasilva333** [comment] 2015-04-24 12:38
@weborican do you experience issues with the checkboxes in all your loadouts or just those two?
@pattont Thanks for the feedback I think I'll end up rewriting the damn thing so conditions like orphaned equipIds aren't a problem.

**Comment by weborican** [comment] 2015-04-24 12:47
I'm seeing it on these:
"Old Faithful"
"Arc Burn"
"Crucible Weapons"

**Comment by dasilva333** [comment] 2015-04-24 19:36
@weborican  I created a beta build (it has no debug logging or output so no need to report back anything from the console unless it crashes).

You can find it here: https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tower_ghost_issue69.zip

Please try it and let me know if it works better thanks

**Comment by weborican** [comment] 2015-04-24 20:25
Your rewrite seems to have done the trick, at least for my misbehaving loadouts. Wonder if it also fixes pattont's issues.

I see you have added code to update loadouts, and looking at the loadout data I can definitely see that. My question is, if your "ids" array has all the necessary info now (id, bucketType, doEquip), why keep the "equipIds" array as well?

**Comment by dasilva333** [comment] 2015-04-24 20:27
Great I'm glad it fixed it, expect it in 2.1.1. I left equipIds around for legacy compatibility with existing loadouts everyone created. I'd hate for everyone to have to recreate them you know. :)

Cheers

**Comment by weborican** [comment] 2015-04-24 20:35
Undertood. Thanks for all your hard work!

PS> Would it make sense, since you are converting the data and all, to save the loadout in order?
Subclasses
Primary
Special
Heavy
Helmet
Gauntlet
Chest
Boots

**Comment by dasilva333** [comment] 2015-04-24 22:55
@weborican 2.1.1 is out and yes the loadout should save in the same order however if it doesn't I'm sorry for your loss sir anyhow try it out and let me know thanks!

**Comment by pattont** [comment] 2015-04-25 05:24
My issue is resolved in 2.1.1 and the load outs. Nice work

**Comment by weborican** [comment] 2015-04-25 06:34
Oh no, nothing has been lost and everything is working great now.

What I was suggesting is presenting the items in a loadout in groups, essentially sorted in the order suggested on my post. That way, when I decide to add a new primary and secondary to my loadout they won't get stuck at the end of the list. Checkboxes on items that are not grouped can get a bit messy.

**Comment by dasilva333** [comment] 2015-04-26 16:05
@weborican Expect it in the next version 2.1.4 thanks

**Comment by weborican** [comment] 2015-04-28 12:56
Will definitely keep my eye out for that. Thanks!
----
Well, in testing 2.1.7 it seems my loadouts have gone bye-bye. Here is the error I'm seeing:
loadouts.js:101
Uncaught TypeError: Cannot read property 'bucketType' of undefined

Then, when doing a JSON.stringify(app.loadouts()) I'm getting this:
"[]"

**Comment by dasilva333** [comment] 2015-04-28 13:04
It seems the code was trying to migrate your old loadouts and you had an item in one of your loadouts that you later deleted, if you post your membershipId i can check the server and see if I still have the data so you can manually restore it. I'll add some code to prevent this in the future. I'm closing this ticket at this point since the original bugs has been fixed and this would be a separate issue.

thanks

**Closed by dasilva333** 2015-04-28 13:04 UTC
Labels: bug
