### ISSUE TITLE
Must login every time on iOS

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#133] opened 2015-05-05 13:23 UTC
I have to login every time I open the iOS app. It's very frustrating and I usually opt for other apps on mobile because of it. I only play on PSN though so I can't say if this is an issue for Windows Live login. 

![img_1144](https://cloud.githubusercontent.com/assets/4229542/7473288/ff2a3024-f2ee-11e4-9d9d-297511b724ed.jpg)

**Comment by dasilva333** [comment] 2015-05-05 13:25
It's by design, on Android it works fine. It's not something I can fix it's due to InAppBrowser's cookie policy. Sorry @wickles closing this ticket as it's something out of my control

**Closed by dasilva333** 2015-05-05 13:25 UTC

**Comment by wickles** [comment] 2015-05-05 13:28
Okay. Just wanted to make sure since I didn't see any other tickets on this.
