### ISSUE TITLE
Tower ghost keeps asking me to log in?

### ISSUE THREAD

**Issue by iamlester55** [dasilva333/TowerGhostForDestiny#636] opened 2016-07-21 06:21 UTC
I am logged in and for some reason the app won't let me transfer items. It keeps telling me (error. Please log in). I've Uninstalled and reinstalled multiple times and I get the same error.

**Comment by Reeffreak** [comment] 2016-07-21 11:40
I am having this same issue. I've tried everything including uninstalling and reinstalling several times. Please fix ASAP. I can't play without Tower Ghost!!!

**Comment by yzpmpgq** [comment] 2016-07-21 12:09
Same here for the last 2 days.  Really tough in IB when you need something and have to switch chars just to transfer.  I have the issue at 2 different locations, so I don't think it's on my end.

**Comment by rkingsla** [comment] 2016-07-21 12:48
It’s not you…. Bungie (Bungo?) updated their API servers and changed things to an updated API. The fact that they rolled out a new version of their very own Gear Manager with no notice to anyone else may kind of give you an idea how much 3rd party providers of tools matter to whoever OK’d these changes.

 

Kind of sad, really.

**Comment by dasilva333** [comment] 2016-07-21 13:06
Hey guys thanks for the support and looking out, this issue is a dupe of #635 I'll fix up the title and you may follow that issue for future updates on whether it's been fixed yet. From what I've gathered TGD and DIM are both having the same Sign in issue but Ishtar Commander still works (not tested personally).

Thanks again

**Closed by dasilva333** 2016-07-21 13:06 UTC
