### ISSUE TITLE
PSN log in screen freezes up upon opening

### ISSUE THREAD

**Issue by megaslaytallica** [dasilva333/TowerGhostForDestiny#399] opened 2015-09-23 09:44 UTC
I have been unable to even use the app so since I can't log into PSN via your app. Once I click on PlayStation Network link it goes to the log in page then freezes up and won't let me type or go back. I have to force close every time. I am using a Droid Turbo. This app seems very helpful. Please help me get passed this issue. Thank you.

**Comment by dasilva333** [comment] 2015-09-23 13:41
Try 3.2.6+

**Comment by megaslaytallica** [comment] 2015-09-23 14:17
I updated to 3.2.7 and still the same issue.

**Comment by dasilva333** [comment] 2015-09-23 14:21
Just to confirm you never managed to log in or even enter your credentials right? You simply open the app, a prompt with two buttons for xbox and playstation show up, you click playstation, a pop up shows up to log in to Playstation, then it freezes or does it freeze before the pop up even shows? Thanks let me know

**Comment by megaslaytallica** [comment] 2015-09-23 14:25
Correct, i have not been able to log in or enter my credentials. The pop up for PlayStation loads up, then it freezes.

**Comment by JintoLin** [comment] 2015-09-23 23:06
3.2.7 on Firefox gives me the same api error 
"Error: Please add valid X-API-Key header to request. Visit https://www.bungie.net/developer for details." - and im already logged in through the plugin 

I hate having to use the bungie site to move stuff
![screen shot 09-23-15 at 06 06 pm](https://cloud.githubusercontent.com/assets/14193112/10061373/ceb8dc9e-621d-11e5-9ac6-da0cdbbf8007.JPG)

**Comment by dasilva333** [comment] 2015-09-23 23:58
@JintoLin that is a seperate problem please track that in issue #400

**Comment by dasilva333** [comment] 2015-09-26 00:49
@megaslaytallica are you on android? if so try 3.3.1 and let me know how it goes. thanks

**Comment by megaslaytallica** [comment] 2015-09-26 03:32
I am. Ok, I'll give it a try.

**Comment by drinkc0ke** [comment] 2015-09-26 14:54
@megaslaytallica Did the new patch (3.3.1) work for you on Android? This bug also affects iOS, though we don't have a new version to try right now, so I'm very interested in whether 3.3.1 resolves the issue. Thanks!

**Comment by megaslaytallica** [comment] 2015-09-26 18:26
No luck, it still freezes up at the same spot.

**Comment by drinkc0ke** [comment] 2015-09-27 00:54
@megaslaytallica Bummer, but thanks for trying!

@dasilva333 At this point, would it be prudent to revert the latest release back to 3.2.5 and push out an update? This is 3 days now that I've been without a functional TGD and I'm deep in withdrawal. 3.2.5 was stable for the majority of the userbase, so I say let's revert back so we have a functional app to use. But thanks again for all the hard work you do developing & maintaining TGD!

**Comment by dasilva333** [comment] 2015-09-27 21:56
Hey guys so I can't figure out the problem some of you are having with 3.2.6 in the Apple App Store and 3.3.1 in the Google Play Store, from what I understand it seems that from a clean install/ after entering your credentials the app freezes during loading? What happens after you close the app and open it back up? Does it never load?

Just to make sure this is the proper login procedure:
1. green prompt comes up with xbl or psn link
2. you enter your login info into playstation network
3. you wait until that window closes itself
4. after it's closed itself the stuff should just load

So I made a few debug binaries for you guys to try out see if you can get it to crash and produce an error message. What you'll do is visit jsconsole.com in the prompt type :listen BC63347B-0A77-4632-91F3-3C01BADDF717 Once listening you can open the app and attempt to get it to crash if it produces any error messages share them with me here using pastebin.com or whatever you'd like.

iOS IPA: https://build.phonegap.com/apps/1398768/download/ios
Android APK:

You may only test the iOS IPA if you're jailbroken, if you're on iOS 9 and you'd like to help please provide me with your UDID (http://whatsmyudid.com/) so you may install the IPA using iTunes or iFunBox.

Thanks guys

**Comment by megaslaytallica** [comment] 2015-09-27 23:29
The app opens fine, when I click on the PSN button to log, the window pops up and loads fine. But at that point is when it freezes. I can't back out of the app, nor will it let me click on anything in this PSN window. It also does not close using the back button on my droid. I have to hit the open apps menu and close it that way.  When I re-open the app it does the same thing.  I had done the clean re-install to 3.3.1 yesterday and got the same thing.  Well I did it again today and now it is working. I was able to log in for the first time. I will keep you posted if this issue arises again. Thank you very much.

**Comment by Khaaang** [comment] 2015-09-28 02:45
I was asked to follow up on my issue on this thread. My issue is a little different. I open the app, click the Xbox live button, allow it to load and self close, it gives the loading prompt, then goes the a blank screen. When I say blank, I mean a empty screen with the app's background. Menu still works, the app is not frozen. App was working fine a few days ago. Is it possible the issue is a change on bungie's side? Or possibly my account? However, I also have Loadouts for iOS and it continues to work fine for iOS9. Can't get udid at the moment , will try to fwd it later.

**Comment by n34panda** [comment] 2015-09-28 11:17
Just joined in here too, i've got the same problems on 3.2.6 on IOS 9.0.1 but also on the windows desktop version.  See my self-closed issue #411 for more details.  I've tried re-installing from the app store without success.

**Comment by cmille34** [comment] 2015-09-28 21:31
I too am in the same boat as all the other IOS folks.  I get past the Xbox Live login but instead of loading my arsenal its just a gray screen.  All the menu items are at the top but no weapons/gear.  This seems to have just started with 3.2.6.  I have an iPhone 6 with 9.0.1 and a jailbroke iPad2 (maybe iPad3, hell if I know) that is IOS 8.1.   Both have the same problem.

On the iPad I loaded the iOS IPA that you said dasilva333 and then went to jsconsole.com and pasted in that string you said to (:listen BC63347B-0A77-4632-91F3-3C01BADDF717) but nothing shows up on the jsconsole really indicating a crash or anything.  It does appear to be a crash but Im no developer.  If youd like any screenshots or need someone to go through more specific steps to narrow this problem down let me know.  I can follow instructions here or via email if its easier to send screenshots or whatever that way.

Looking forward to getting this resolved, I miss the app!

**Comment by dasilva333** [comment] 2015-09-28 21:44
@cmille34 thanks for the info. Perhaps it wasn't your fault that you weren't able to get any debug information, let me ask you a few questions:
-Did you see a pop up after opening the app stating that jsconsole.com was active?
-Did you see jsconsole.com ever say connected to device and provide you with the model number it connected to?
If these things didn't happen you probably downloaded the wrong IPA, a mistake on my behalf I apologize however I have fixed the link and you may try so again here:
https://build.phonegap.com/apps/1398768/download/ios
https://build.phonegap.com/apps/1398768/download/android
If anyone else on Android having problems would like to test it out use the link provided and instructions in my earlier post. Thank you all for your help

**Comment by cmille34** [comment] 2015-09-28 22:07
Here are screenshots of jsconsole and what I see in TGD.  Do I need to
completely delete TGD before installing that IPA you linked?

[image: image1.PNG]

[image: image2.PNG]


Sent from my iPad

On Sep 28, 2015, at 5:48 PM, Richard Pinedo <notifications@github.com>
wrote:

@cmille34 <https://github.com/cmille34> thanks for the info. Perhaps it
wasn't your fault that you weren't able to get any debug information, let
me ask you a few questions:
-Did you see a pop up after opening the app stating that jsconsole.com was
active?
-Did you see jsconsole.com ever say connected to device and provide you
with the model number it connected to?
If these things didn't happen you probably downloaded the wrong IPA, a
mistake on my behalf I apologize however I have fixed the link and you may
try so again here:
https://build.phonegap.com/apps/1398768/download/ios
https://build.phonegap.com/apps/1398768/download/android
If anyone else on Android having problems would like to test it out use the
link provided and instructions in my earlier post. Thank you all for your
help

—
Reply to this email directly or view it on GitHub
<https://github.com/dasilva333/TowerGhostForDestiny/issues/399#issuecomment-143882762>
.

**Comment by dasilva333** [comment] 2015-09-28 22:07
images are not showing

**Comment by cmille34** [comment] 2015-09-28 22:18
Replied via email the first time, i drag/dropped images in this time.  Links appear to work now.  Doesn't appear to be a crash, but heck if I know.  Let me know how I can help.

**Comment by cmille34** [comment] 2015-09-28 23:04
dasilva333, any chance there is something wrong with that latest IPA you linked? I deleted the copy I had on my iPad and and I can't get your version to install. I tried from Safari and Chrome from the iPad and it just gets stuck on installing. I rebooted iPad and then tried installing it through iTunes and it just gets stuck on installing there as well.  Installs fine from App Store.

**Comment by n34panda** [comment] 2015-09-29 22:13
FYI on the ios 9 upgrading to 3.3.3 fixed this issue for me.

**Comment by Tsothoga** [comment] 2015-09-29 22:26
The new TGD 3.3.3 works on ios 9.0.1, confirmed as of now!

**Comment by dasilva333** [comment] 2015-09-29 23:17
great thanks guys

**Closed by dasilva333** 2015-09-29 23:17 UTC
Labels: bug

**Comment by drinkc0ke** [comment] 2015-10-01 00:22
Thanks @dasilva333!
