### ISSUE TITLE
Display Only Duplicate items

### ISSUE THREAD

**Issue by Joshbuss** [dasilva333/TowerGhostForDestiny#103] opened 2015-04-27 12:17 UTC
For some of us vault space is still an issue,  and getting rid of those pesky duplicates is sometimes a pain. 

Can we add a filter that shows only the duplicates? We could then transfer to a character and dismantle the one we don't want.  

The filter should stack on top of current filters.  Weapon/arrmor/general etc

**Comment by dasilva333** [comment] 2015-04-27 12:55
The filter would probably exist under the Set filter and just be a modifier, thanks for the feedback

**Comment by dasilva333** [comment] 2015-05-03 14:13
@Joshbuss feature coming in 2.3.1

**Comment by lanejcf** [comment] 2015-05-04 07:37
I have tried this in version 2.3.2 in Chrome on my laptop and I don't seem to be able to get it to work, when I select it it still shows items that I have only of. Please can you explain how it is supposed to work or is it bugged ?

**Comment by Joshbuss** [comment] 2015-05-04 11:29
Works great for me,  some items I have duplicate of but differ in the
roll/damage type ldr I have void and Arc...borh shown up under duplicate,
which is exactly what I would expect

Thanks

**Comment by dasilva333** [comment] 2015-05-04 13:07
@Joshbuss thanks i'm going to consider this complete and I'm going to assume @lanejcf retracted the comment bc it started working. Closing ticket

**Comment by lanejcf** [comment] 2015-05-05 17:49
Sorry to open this one up - I have found that when running 2.3.5 in Chrome if I
1) Select show duplicates
2) Select refresh
it then shows all the items, with duplicates in the menu still selected, then the option for duplicates does not work.

**Comment by rkingsla** [comment] 2015-05-05 18:01
I can repro this....

One addition: If you select Reload in Chrome, the issue is resolved.  Not optimal and not expected behavior, but a viable workaround for a short term.

**Comment by dasilva333** [comment] 2015-05-05 22:08
Expect the fix in 2.3.6, feel free to close the ticket once you confirm it's fixed thanks

**Comment by lanejcf** [comment] 2015-05-07 19:49
Sorry but i believe it may not working as hoped in 2.3.7 in Chrome
if I
1) Select show duplicates
2) Select refresh
it then shows some of the duplicates that were originally shown,but not all

**Comment by dasilva333** [comment] 2015-05-07 22:40
Agreed I too can replicate the issue, thanks I'll get it fixed

**Comment by lanejcf** [comment] 2015-05-08 13:57
I think it is fixed in 2.4.0
:-)

**Comment by dasilva333** [comment] 2015-05-08 16:32
Great thanks for all your help closing this issue now

**Closed by dasilva333** 2015-05-08 16:32 UTC
Labels: enhancement
